### ISSUE TITLE
Make 'What our Clients say' fully responsive

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#109]
Our wrapping 'section-boxes' div did not work for this section.

**Comment by iteles** [comment]
I know this section was commented out, but did it get the same fixes applied to it as #108 #106 etc @hdrdavies?

**Comment by hdrdavies** [comment]
@iteles it's difficult to remember, but I'm fairly sure it would have as we applied section containers to each respective section, it would just need a dark / light class toggling for it to fit into place. Unless @mantagen remembers better than me?

**Comment by markwilliamfirth** [comment]
Closing - irrelevant with new redesign
