### ISSUE TITLE
User testing on 12th Feb Data

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#119]
With particular focus on areas:
-Landing page 
-Scrolling links 

Will record feedback here.

---

testing web: https://dwylio-test.herokuapp.com/

**Comment by iteles** [comment]
As I mentioned this morning, also worth recording what your plan is for the 5 minute sessions and the questions you plan to ask before you start so @nelsonic and I can feed back on them :+1:

**Comment by hdrdavies** [comment]
@iteles @nelsonic 
(My first ever(so go easy(please))) User testing plan:

Sit beside the user and understand their experience while exploring the webpage, some questions I plan to ask:

1. When you land on the site, how do you feel?
2. How easy is it to navigate the page?
3. How would you like to navigate the page?
4. Is the content easy to read?
5. Is the content easy to understand?
6. Are the fonts big enough?
7. Is the content well-written?
8. How well are the pages organised?
9. Was there something missing you were expecting to see?
10. What do you think of the colour scheme?
11. If you could change one thing about the site, what would you change?

**Comment by iteles** [comment]
You might want to start with setting the context - ideally we would be user testing with potential customers, but using FAC people, who need to prime them to imagine they're a business owner who wants to create a technology system of some sort (give an example) and put them in that mind set.
You can even ask what kind of things they'd be looking for/care about before you even open the page. Then ask how they would answer those questions once you're on the website.

I would say that some of these questions are too specific. When someone navigates to a website they're looking for information and forming a first impression. They won't be looking in detail at the font size etc - this is the kind of thing you want the user to pick up on rather than you asking specifically (if there's no problem with it, they won't mention it and that's ok too).

Asking 'Is the content well-written' puts them in a bit of a corner, it's like asking friends and family 'is my idea good?'... well, sure it is honey! You want them to scan the page and tell you what they grasp from what they see and read - a little more general if that makes sense.

I picked up on two specific examples here, but you get the gist?

**Comment by hdrdavies** [comment]
I get the gist :+1: 

As I was writing the questions I sensed they were too *leading* as per Mom test. Will try to be more general.

**Comment by hdrdavies** [comment]
So I'm setting the context for the user as a business owner looking for a product / service to be built who doesn't necessarily have technical experience.

Before they go on the site I ask them:
1. What would you be looking for on the site?
2. What about the company would you care about?

Then taking notes on their thoughts when they're on the site.

Finally I ask them:
3. Do you feel you've found what you're looking for?
4. Any comments on the layout?
5. Any comments on the colour scheme?
6. Any comments on the navigation?

**Comment by tunnckoCore** [comment]
:+1: yea last looks better :)

**Comment by iteles** [comment]
YES! Agree with @tunnckoCore.

 And If you looked at this website and had no further information would you hire these people? Why?

And if you _do_ consider hiring these people, what would your next step be?

**Comment by hdrdavies** [comment]
# User Feedback

If there is no feedback on a section, it has been left out.

## User 1 - Conor (has an idea for a long-board route tracker app)

#### What would you be looking for on the site?
* Wants a concise strapline that explains services
* Wants case studies of past projects, hopefully with some similar to mine
* Wants to know who the team are, which details how experienced they are
* Doesn't want to be bamboozled with tech jargon
* Wants to be able to show the site to clients - so it needs to look trustworthy & professional

#### What about the company would you care about?
* Really cares about there being testimonials

#### While on the site
* Felt like people will look at Values first because of positioning on navbar
* Likes the idea of fully tested code
* Confused by what 'agile development' is
* What Open-source? People can see my work? --it doesn't sound like a positive thing
* Under 'Ethics Driven' - 'carbon positive' doesn't seem very relevant & seems wooly
* In the tagline 'community' almost sounds like there's no one in charge - what about 'Team'?
* In Our Offering, the products seem like they're only on mobile- what if I want them for desktop?
* Contact - 'Let's talk' might be a bit too big - maybe have another prompt saying you're interested in hearing about projects / ideas

#### Do you feel you've found what you're looking for?
* No previous work!
* No list of services - maybe offer this in the Nav Bar

#### Any comments on the layout?
* Doesn't like the links in the content blocks
* Headings could be bigger

#### Any comments on the colour scheme?
* Liked it

#### Any comments on the navigation?
* Splash links might not be necessary, have all of it in the nav bar

## User 2 - Ruth (has an idea for a chocolate delivery app)
 
#### What would you be looking for on the site?
* Wants examples of previous work
* Wants prices
* Would like a timeframe of how long the project would be

#### What about the company would you care about?
* Would like a well designed website 

#### While on the site
* Highlighted tick needs to fade-out & fade-in properly
* Nav bar is a little too big - could be 2/3 of size
* Splash links are not obvious

#### Do you feel you've found what you're looking for?
* No examples of previous work
* Budget section of contact form partially answers question about price

#### Any comments on the navigation?
* The links on each section don't make much sense 

## User 3 - Katherine (has an idea for a Game of Thrones costume delivery app)

#### What would you be looking for on the site?
* Wants to see past work & testimonials
* Wants to know how to contact us 
* Would like an FAQ section

#### What about the company would you care about?
* Cares about amount of experience
* Cares about company philosophy
* Cares about price ranges

#### While on the site
* Splash links difficult to see especially since I'm attracting to the Navbar
* In 'Our Offering', what's an MVP?
* In the User Testing section - does this mean I need to find users? That sounds scary
* Likes the info about budget in the contact form

#### Do you feel you've found what you're looking for?
* No past work

#### Any comments on the layout?
* 2 different menus (links) are confusing

#### Any comments on the colour scheme?
* Fan of background image - seems as though you could have a friendly discussion with the people at dwyl

#### Any comments on the navigation?
* Links are confusing on the splash, especially since the first instinct is to scroll down

## User 4 - Tom (has an idea for a violin purchasing app)

#### What would you be looking for on the site?
* Wants simple language
* Wants quick information as he doesn't have much time
* Wants a prioritisation of the information he's after e.g. prototype building etc.
* Wants to know how much it will cost and how long it will take
* Wants straight forward contact information
* Wants it to be friendly & not too imposing

#### What about the company would you care about?
* Cares about previous projects, wants info about them
* Cares about success stories & testimonials

#### While on the site
* On landing, likes that there aren't too many things to click on
* The flashing tick without it leading anywhere is confusing. Perhaps it should lead to information about previous work
* In the ethics driven section of values, he wants a link to who has influenced the website - who are the people doing great things?
* What's open source?
* Contact form is good but how long will it take to be replied to?
* He didn't know he could scroll because of the links!
* What's an MVP? and why mobile-first?
* Our Process needs full-stops
* What's iterating? and what's a tight feedback loop?
* Diagram doesn't make it completely clear what the waterfall process is. It almost suggests it's quicker and easier as it's 4 steps instead of 5... 

#### Any comments on the layout?
* Words could be a bit simpler

#### Any comments on the navigation?
* Didn't mind splash links but maybe the heart tick would lead to somewhere

**Comment by iteles** [comment]
❤️ **Super useful**. Great job.

**Comment by tunnckoCore** [comment]
damn, just realized that today is 12th feb, lol xahxhahxha

As of first results.. i can say - reasonable - i can agree with most of them. While reading them i realized that they are not for the actual dwyl.io web, so i search and find the dwyl-test heroku app. And actually I don't like the site so much.

Most people can't realize that they shouldn't expect "how much it will cost and how long it will take", "prices" and etc. IMHO. That's very specific thing and depends on what project they want to be done.

> :heart: Super useful. Great job.

Absolutely! i formed in my mind some things. And realize that that "feedback" work looks very exciting.

**Comment by iteles** [comment]
@tunnckoCore Whilst it's true that it's completely unrealistic to ask for price and timelines upfront, it's what _all_ clients want. Github is our community for all of our open source work, but the website is what clients who want us to help them build apps will see - we need to gently explain to them that this isn't the way it works ;)

That link isn't the latest version that @hdrdavies was testing, just pull down https://github.com/dwyl/dwyl.github.io/pull/96 and run `npm i` and `npm start` to run it and see what @hdrdavies and @mantagen are proposing :+1: 

Would be good to know more about what you don't like, it's always useful to have more people's thoughts! :relaxed:

**Comment by iteles** [comment]
@hdrdavies Could you please also drop in a time estimate of how long this took you (broken down into its component parts) so that we know how long it may take to replicate in future?

**Comment by hdrdavies** [comment]
Of course! 

Skim reading The Mom Test :wink:: 30 minutes
Preparing questions & incorporating feedback: 30 minutes
Selecting users, running demos & recording feedback: 20-30 minutes each (x4 in this case)
Curating & recording feedback: 30 mins - 60 mins

(conservative) Total time for 4 users: 4 hours

**Comment by iteles** [comment]
@hdrdavies Very useful, thanks!

**Comment by iteles** [comment]
Still love this <3

**Comment by hdrdavies** [comment]
:+1: @iteles

**Comment by Cleop** [comment]
@iteles can this now be closed or would you like to keep it open for the next redesign? Or should we open a new issue for that if we want to do testing?

**Comment by markwilliamfirth** [comment]
Closing - new issue will be opened (and can be inspired by this) for testing new redesign if required
