### ISSUE TITLE
Firefox nav bar display bug - nav jumps to the next line

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#120]
<img width="1721" alt="screen shot 2016-02-15 at 00 51 16" src="https://cloud.githubusercontent.com/assets/4185328/13037691/b07b8574-d37e-11e5-8678-0e69f7516611.png">

**Comment by hdrdavies** [comment]
Myself and @mantagen had a look at this together but couldn't figure it out as of yet. Will have a look with fresh minds :+1:

**Comment by iteles** [comment]
@mantagen What do you suggest a long term fix for this needs to be? Should we add some comments into the CSS to explain this is a tempo fix for this particular bug?

**Comment by markwilliamfirth** [comment]
Closing - irrelevant with new redesign
