### ISSUE TITLE
Experiment: Will prospective/existing clients call a number if we put one on the site?

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#124]
As per #116

**Comment by nelsonic** [comment]
@hdrdavies I think it makes *sense* to have a phone number especially one people can click-to-call. 
please put my personal mobile number in there and if I get more than 5 prank/PPI calls we can change it.

**Comment by hdrdavies** [comment]
Ok! Does a prank call from me count?

**Comment by nelsonic** [comment]
lol. only if you call me to order takeout. :wink: 
for every other reason your calls are legit! :+1:

**Comment by hdrdavies** [comment]
:laughing:

**Comment by iteles** [comment]
No calls so far!

**Comment by markwilliamfirth** [comment]
Confirmed that this does occur
