### ISSUE TITLE
Review of 'Values' content

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#129]
Drawing some data from #119, it might be a good idea to reconsider some of the content in the 'Values' section:

Open-source - Although we know this is great, a client may not think 'having code out in the open' is necessarily a positive. We could phrase it in a different way that doesn't mention that part and focuses more on being able to make use of the expertise of dwyl members

Ethics Driven - 'carbon positive' may not be particularly important to a client (unfortunately). User Tom suggested we include a link to somewhere else which shows our advocacy for people doing great things / people who have influenced our website. 

Simplicity - add a link to something demonstrating this. The portfolio section would do this well in the meantime, but is there something we can add in the short term?

**Comment by markwilliamfirth** [comment]
Closing due to redesign
