### ISSUE TITLE
How to Make Perspective Mockups in Photoshop

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#134]
![multideviceswebsitemockupspreview1-f](https://cloud.githubusercontent.com/assets/194400/13054460/e45c8b58-d401-11e5-8655-54212fddbfb3.jpg)
- From Scratch Tutorial: https://www.youtube.com/watch?v=eeNJr3YBw6Q
- Mobile-specific tutorial: https://www.youtube.com/watch?v=AnPcD0s3eDc
- With multi-device template: https://www.youtube.com/watch?v=boNGteIfknc (Costs $8)

We have Photoshop CS6 on our MacMini @dwylhq if anyone is interested in learning how to do this...

**Comment by iteles** [comment]
Very much a VA task in my view.

**Comment by nelsonic** [comment]
@iteles agreed. :+1:

**Comment by iteles** [comment]
Linked to #26 and #76

**Comment by markwilliamfirth** [comment]
Closing due to redesign
