### ISSUE TITLE
MD File: History of the dwyl website

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#143]
I think I have a few screenshots of the various incarnations (in fact, I know there's an issue about this, I just can't for the life of me find it!). So using this as a place to log them.

**Comment by iteles** [comment]
November 2015 - February 2016
![fireshot capture 1 - dwyl - do what you love - http___www dwyl io_](https://cloud.githubusercontent.com/assets/4185328/13510869/9737752c-e18a-11e5-86c8-4188ebd9c2ca.png)

**Comment by markwilliamfirth** [comment]
Closing as this is easily found in closed issues or by looking at previous commits to the repo

**Comment by iteles** [comment]
Sure, if you think you're not going to forget to do it without an _open_ issue.

**Comment by markwilliamfirth** [comment]
@iteles sure let's keep it open and transfer to MD file

**Comment by nelsonic** [comment]
Loved seeing this ancient photo. 😍 
Closing as no longer relevant. ✅

**Comment by nelsonic** [comment]
Snapshot of current site before we archive it:

![image](https://user-images.githubusercontent.com/194400/195075433-f44967c9-d2a6-4e67-8529-1af3c5b6751e.png)

![image](https://user-images.githubusercontent.com/194400/195075469-978e7ddc-723e-4f11-9d0b-0ac8f1cf0b3b.png)

![image](https://user-images.githubusercontent.com/194400/195075497-aa70510f-9557-4b9a-b023-2eaa73077498.png)

![image](https://user-images.githubusercontent.com/194400/195075575-fe4c9ff6-fadf-4853-9e84-defb8d4d1d28.png)


![image](https://user-images.githubusercontent.com/194400/195075709-66697414-2857-4d3e-85ad-8282a6e68d04.png)

[Productivity](https://github.com/nelsonic/nelsonic.github.io/issues/651) indeed ... 🙄

**Comment by nelsonic** [comment]
https://dwyl.com/team
![image](https://user-images.githubusercontent.com/194400/195075883-937a8f29-28ab-4708-b5af-bb469a4bba49.png)

All these lovely people! 😍

**Comment by nelsonic** [comment]
https://dwyl.com/values
![image](https://user-images.githubusercontent.com/194400/195076064-e321f4eb-260f-4ad4-96d2-a9dd316d450d.png)
