### ISSUE TITLE
Repo for proposed emailing 'schedule' and content?

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#16]
Is it a good idea to have a separate repo with some information/discussion around  emailing people? For example what the appropriate content/frequency would be, better the understanding of the reasons _why_ people sign up to get emails from us, what the alternatives to emailing people are (blog, etc) and complimentary communication methods.
Or maybe a more general repo on communication with people who are interested in dwyl?

@nelsonic Thoughts?

**Comment by nelsonic** [comment]
What do *you* prefer?

**Comment by iteles** [comment]
I wouldn't have suggested it if I didn't think it was worth exploring. What I'm looking for is a 'maybe we could use this other place instead' or 'No, that's terrible because of this one thing you haven't considered' or a 'No, github isn't the right place for that' type answer if you have one.

**Comment by nelsonic** [comment]
So... you're *expecting* a *negative response*...?

**Comment by iteles** [comment]
No, I'm _expecting_ either a positive or negative response. It's the _insight_ that may be negative as I have already considered the positives.

**Comment by Cleop** [comment]
- Do we currently have any means for people to sign up to a newsletter/ email subscription via the website?
- Would we like this integrated into the new design?
- If not, is this a broader issue around communications and outreach to the community/clients and is it better off in hq rather than the website specifically?

@iteles

**Comment by iteles** [comment]
@cleop This issue is probably better off in HQ (marketing sits with @markwilliamfirth ).

We do need an email sign up in the `app` page, but I don't know if we plan to have a newsletter just yet, I don't think @markwilliamfirth has had a chance to think about it yet!

**Comment by iteles** [comment]
👍 Thanks @cleop
