### ISSUE TITLE
Should we add a link to our Github community into the nav?

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#170]
We speak to a lot of developers, but when they land on our website, there's nothing there for them. It's fully geared towards client work.
But a big part of what we do is open sourcing modules and having a 200+ strong community. So shouldn't we give them a way to find us on github easily if they land on the site?

**Comment by SimonLab** [comment]
Something like:
![dwylcommunity](https://cloud.githubusercontent.com/assets/6057298/15548314/b2e58790-229f-11e6-835f-784678331237.png)

Or another name for the item tag?

**Comment by nelsonic** [comment]
@iteles should the link go directly to GitHub *or* should it go to a page the explains *why* we have an open community of developers?

**Comment by SimonLab** [comment]
I link the community page of Elm (http://elm-lang.org/community). It display all the links to irc, slack,...
We could have the same kind of page with the link to Github and to the gitter dwyl chat. Like @nelsonic said we could also have more info/explanation the why of the open community.

**Comment by iteles** [comment]
YES! This is a great idea @nelsonic and @SimonLab

**Comment by iteles** [comment]
I guess I need to write a little content for this. Will do so asap.

**Comment by SimonLab** [comment]
linked to this issue too #77 ?

**Comment by markwilliamfirth** [comment]
Closing in favour of #225
