### ISSUE TITLE
We Need a Photo or Video for each thing in our "Offering"

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#185]
Currently our "offering" on the website http://www.dwyl.io/#offering is bland/boring:
![dwyl-offering-training](https://cloud.githubusercontent.com/assets/194400/21466361/cd60d8a4-c9c0-11e6-903d-624821ff11ef.png)

In 2017 we need a photo or (_preferably_) ***video*** for each item. 
+ **Product Development**: we need an "***our process***" (_the Google Ventures Sprint: http://www.gv.com/sprint ..._) blog post and initially a few good photos. We need to ideate/story-board a 5sec "_nano intro_", 30sec "_spot_" and 3min "in-depth" video where:
  + ***Intro*** the concept of a Design Sprint and why it's great to solve difficult/complex challenges by focussing on what _can_ be done in a week of concentrated effort.
  + Show ***examples*** of us _doing_ the sprint with our clients, photos or video
  + Testimonial from one of our clients
  + Results from the _end-user's_ perspective not just the product owner/sponsor
+ **User Testing** is probably the most important thing that we do. Writing code or building products is _totally_ meaningless if it's done without the input of _real people_. So, we need to setup our "***Mobile Testing Lab***" _ASAP_ then take it out into the field and film people using our apps over 3G (_i.e. slow connection_) and ask them to perform basic user-story-tasks where we _film_ the experience! We can also do more "formal" user-testing, but the main thing we want to demo is getting out into the "real world" and _learning_ from People!
+ **Training**: this is the area of DWYL that is going to expand the _most_ in 2017. we are going to be _widely_ recognised as the go-to place in London for learning the "Sprint" Method and New Technologies organisations can use to **build ("_digital_") products that _solve real challenges_ and people _love_ using**! 

If _anyone_ has any other ideas/suggestions please share! ❤️  ✅

**Comment by iteles** [comment]
Linked to #235

**Comment by nelsonic** [comment]
Our "offering" will become _dramatically_ simpler in the next few weeks/months. One thing in fact. an **`App`**. 📱 ✅
