### ISSUE TITLE
Blog: Blog Post: Maslow Hierarchy of Needs ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#192]
On _more-than-one_ occasion I have mentioned this to people in our team and in discussions with family/friends, and to my surprise quite a _few_ had not _heard_ of it. It's _easy_ to take knowledge for granted when we think "_it's obvious_", but _apparently_ not _everyone_ spent their 20's wikipedia-article-hopping 😮  so for some, this is new information...! 🤔 

> Should we write a (blog) post about **Maslow's _hierarchy_ of _human needs_**?

![image](https://cloud.githubusercontent.com/assets/194400/21961428/6b4057a6-db01-11e6-9595-52ce254e7917.png)

+ https://en.wikipedia.org/wiki/Maslow's_hierarchy_of_needs
+ http://www.npr.org/programs/ted-radio-hour/399796647/maslows-human-needs

This one is _amusing_
![image](https://cloud.githubusercontent.com/assets/194400/21961414/18756db8-db01-11e6-92e8-62e1e0ec1639.png)

This one de-emphasized the "pyramid":
![image](https://cloud.githubusercontent.com/assets/194400/21961416/200598c8-db01-11e6-88db-3859ae9c7977.png)

IMO we _cannot_ ***contextualise*** dwyl without first introducing people to the hierarchy of human needs.

**Comment by Charlotteis** [comment]
Happy to review this, put my Psychology degree to good use.

**Comment by iteles** [comment]
That'd be amazing @Charlotteis, thank you!
