### ISSUE TITLE
HTTPS warning!

### ISSUE THREAD

**Issue by ronanyeah** [dwyl/dwyl-site#193]
Site triggers a security warning on HTTPS!

**Comment by nelsonic** [comment]
@ronanyeah thanks a _ton_ for reporting this. I think we "just" haven't added an SSL/TLS cert to the Heroku config. we should prob get that done... 
do you have any recommendations for SSL? 
(_last time we used GoDaddy when we were hosting our site on DigitalOcean...
but I'm **sure** there are better options..._)
thanks! 🎉

**Comment by Jbarget** [comment]
@nelsonic https://letsencrypt.org/ these guys/gals?

**Comment by nelsonic** [comment]
@Jbarget good shout! let's do that tonight and update https://github.com/dwyl/learn-security with a _complete_ guide to setting up SSL/TLS for your Heroku-based Web App! 😉

**Comment by nelsonic** [comment]
Haven't "_forgotten_" this. ⌛️ 
I wrote up the Let's Encrypt instructions in a step-by-step guide: https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md

I will get this done soon. 👍

**Comment by markwilliamfirth** [comment]
@nelsonic https://certsimple.com/ (one of the startups from EF5) do this in case you need to look for a company to do it

**Comment by nelsonic** [comment]
@markwilliamfirth I've heard they're _really_ good for "EV" Certs. 
we will use them for the _product_. thanks! 👍

**Comment by nelsonic** [comment]
DNS Settings are currently: 
```
heroku domains --app dwylio
```
![image](https://cloud.githubusercontent.com/assets/194400/26760357/cfdec70e-490d-11e7-8cda-9c6c52afc215.png)

When I attempt to run:
```
curl -vI https://www.dwyl.com
```

I get:
![image](https://cloud.githubusercontent.com/assets/194400/26760374/24e47b72-490e-11e7-8c72-f03561b7138b.png)

Checked DNS Settings for dwyl.com:
![image](https://cloud.githubusercontent.com/assets/194400/26760412/f62926d8-490e-11e7-860c-d9ad1f1cabc0.png)

Added rule:
![image](https://cloud.githubusercontent.com/assets/194400/26760408/ee9092da-490e-11e7-9e1a-094741f07c0e.png)

Still getting:
![image](https://cloud.githubusercontent.com/assets/194400/26760424/6595eb28-490f-11e7-81d6-fc8ac1c831dc.png)

Going to wait a while for change to propagate.

**Comment by nelsonic** [comment]
Currently the heroku domain & certificate settings are:
![image](https://cloud.githubusercontent.com/assets/194400/26760639/32ad1400-4916-11e7-96a1-f76b568e3bb3.png)

Two of the settings are "failing".

But visiting https://www.dwyl.com we get:
![image](https://cloud.githubusercontent.com/assets/194400/26760688/127c122a-4917-11e7-93cd-a121b3b151a5.png)

So it's working. 👍

**Comment by nelsonic** [comment]
@iteles please confirm SSL/TLS is working for https://www.dwyl.com
by visiting the domain in your choice of web browser. 

or run the following command in your terminal:
```
 curl -vI https://www.dwyl.com
```
You should see:
![image](https://cloud.githubusercontent.com/assets/194400/26760711/765343ea-4917-11e7-958c-d0ac1c329bfc.png)

**Comment by iteles** [comment]
Seems to be working fine for me 👍 Thanks for this @nelsonic, let's reopen if it pops up again.

**Comment by nelsonic** [comment]
@iteles not much chance it will "pop up again" given that it's set to auto-renewal... 😉
