### ISSUE TITLE
Redesign: add favicon and ensure home screen icon works across devices

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#194]
- [x] Add favicons and home screen icon for new dwyl site

I'm using an iPhone 6 and was trying to save your Web Application as a shortcut on my home screen.
But the icon does not appear.

![unable-to-add-home-screen-icon](https://cloud.githubusercontent.com/assets/24758860/22227149/b583697c-e1c1-11e6-81ba-d23a9f53f4f7.png)

Running IOS 10.2 (_latest update_)
Any help much appreciated! Thanks!

**Comment by sohilpandya** [comment]
Need the following link tags in our html page, Do we have an idea of what we want the icons to look like on a mobile home screen? (existing designs?)

```html
<link rel="apple-touch-icon" href=".link/to/icon">
<link rel="icon" type="image/png" href="./link/to/icon">
```

**Comment by markwilliamfirth** [comment]
@Cleop to check if this is still an issue with redesign

**Comment by Cleop** [comment]
This will be an issue as you have to create images for this purpose. I will update the time estimate to how long it will take to implement this.

**Comment by markwilliamfirth** [comment]
@Cleop 👍 

Linked to https://github.com/dwyl/best-evidence/issues/100

**Comment by markwilliamfirth** [comment]
Solved by https://github.com/dwyl/dwyl-site/pull/386

Works on Android - gonna assume works elsewhere too 👍 
![screenshot_20170929-155709](https://user-images.githubusercontent.com/5732209/31021844-03ce9396-a52f-11e7-951f-66108d1a471c.png)
