### ISSUE TITLE
dwyl icon does not appear on LinkedIn

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#197]
Similar to issue #194 

When adding the dwyl website as a Media Link on LinkedIn, the icon does not appear

<img width="312" alt="screen shot 2017-01-30 at 15 59 55" src="https://cloud.githubusercontent.com/assets/5732209/22430266/9ab49334-e705-11e6-8634-b1ff2d8a61bb.png">

**Comment by nelsonic** [comment]
@markwilliamfirth that's lame. please investigate how to fix.

**Comment by markwilliamfirth** [comment]
This should be revisited once the new design has been pushed out

**Comment by iteles** [comment]
Well remembered @markwilliamfirth 👍

**Comment by Cleop** [comment]
I've checked this on linked in using the new gh-pages site and the newly added in wider homescreen/favicon icons in the hope one of them would be assigned but it still doesn't work.

**Comment by markwilliamfirth** [comment]
Can confirm it still doesn't work

If you're the developer of your website, you'll need to make sure the source code complies with Open Graph Protocol (OGP) and certain image requirements specific to LinkedIn. Our developer website contains more details on setting display tags for shares (available in English only).
Below are the og: tags that must exist and their correct format:
<meta property='og:title' content='Title of the article"/>
<meta property='og:image' content='//media.example.com/ 1234567.jpg"/>
<meta property='og:description' content='Description that will show in the preview"/>
<meta property='og:url' content='//www.example.com/URL of the article" />
Here are the image requirements specific to the LinkedIn sharing module:
Max file size: 5 MB
Minimum image dimensions: 1200 (w) x 627 (h) pixels
Recommended ratio: 1.91:1

**Comment by markwilliamfirth** [comment]
complete #270 before this

**Comment by nelsonic** [comment]
Not posting to LinkedIn for the foreseeable future. Closing. ✅
