### ISSUE TITLE
Old site: Burger menu doesn't auto close on mobile

### ISSUE THREAD

**Issue by rub1e** [dwyl/dwyl-site#199]
Android/chrome - when you're on the homepage (www.dwyl.io) and click a nav link in the burger menu, the menu doesn't autoclose after you scroll to the content - you have to manually close it

**Comment by nelsonic** [comment]
@rub1e thanks for reporting the issue! 👍

**Comment by markwilliamfirth** [comment]
@Cleop to check if this is still an issue in the redesign

**Comment by Cleop** [comment]
This is no longer an issue on the redesign having tested this on both iOS and Android.

**Comment by markwilliamfirth** [comment]
👍
