### ISSUE TITLE
Subscription to User Interface Engineering?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#20]
See: http://aycl.uie.com/

**Comment by iteles** [comment]
There are some epic looking talks here is love to listen to for sure. The question is whether with _everything else_ there is to read and listen to, will we (all of us) have time to make use of and absorb this information as well?
We could certainly do a one month trial starting from when we're in Portugal.

**Comment by Cleop** [comment]
@nelsonic / @iteles - would this issue be better off in hq? is it still applicable?

**Comment by markwilliamfirth** [comment]
Closing as this does not appear to be relevant to the site project
