### ISSUE TITLE
Headshots

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#200]
Sam's headshot needs to be made circular

Natalia's headshot needs to be cropped

Andrew's headshot needs to be centred more

**Comment by iteles** [comment]
On Sam's headshot, seems to be oval:
<img width="629" alt="screen shot 2017-02-13 at 17 22 54" src="https://cloud.githubusercontent.com/assets/4185328/22894539/3a769be0-f211-11e6-908d-1e10ecbb431d.png">

@markwilliamfirth Would be good to see a time estimate on here as well :)

**Comment by markwilliamfirth** [comment]
PR already submitted - took less than 5 min 👍

**Comment by nelsonic** [comment]
should we have a standard dimension for our headshot photos?
