### ISSUE TITLE
Blog Building Time Estimate

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#202]
@nelsonic can you estimate the amount of time it would take to build the DWYL Blog (to be added to the website)?

Feature requests:
- Standard blog features
- Author/writer profiles linked in article
- Authors/writers can remove their posts after they've been published if they wish to
- Simple interface for allowing anyone (including non-tech people) to submit a blog article for review before publishing
- Calculates and displays estimate of approximate time it takes to read the post
- Option for reader to 'like' posts
- Option for reader to comment on posts
- Tracking and metrics

**Comment by SimonLab** [comment]
To create easily (and quickly) a simple version of the blog on the website my preference would be to create a repo "blog" on the dwyl organisation where anyone can create a new blog by just opening a PR containing a markdown file.

By using Giithub we can:
- [ ] Add a new blog
- [ ] Update a blog
- [ ] Delete a blog
- [ ] Display automatically the authors of blogs without building a new user management system
- [ ] Display time of creation or last update of blogs

I think for a first version we only need these features. If we need to, we can then later on add more features (comments, metrics, likes,...) but I don't think we need to focus on that at the stage.

Then the website/app will just need to read the markdown file from Github and display an html version. I don't mind to have a bit more thoughts on these but I think in 2 days we could already have a blog section on the website, just need some content after!

@markwilliamfirth @nelsonic @iteles any comments or thoughts?

**Comment by iteles** [comment]
@SimonLab :tada:

I think we'll need some basic analtics for the blog from the very beginning but the website already has google analytics!

Also, check out https://github.com/dwyl/adoro ;)

**Comment by SimonLab** [comment]
Thanks @iteles for reminding me about Adoro, I'll have a look on how to integrate it with the website, it might need a bit of update before.

**Comment by nelsonic** [comment]
@SimonLab are you in the QuietSpace tomorrow?

**Comment by SimonLab** [comment]
Oui and most of the week I think

**Comment by markwilliamfirth** [comment]
@SimonLab thanks for this! How long do you think it would take to make all the features described in the issue description? We're currently deciding whether to utilise [Medium](https://medium.com/) or build an in-house blog. The time estimate / cost and amount of work involved creating and maintaining the in-house blog influences this decision.
