### ISSUE TITLE
Street Address on Website

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#203]
Hi @harrygfox the gentleman who was meant to be meeting with you this afternoon has _just_ spoken  to me on the phone an informed that he is in ***SE5***! 😕 
Apparently it was _unclear_ from the meeting invite that the meeting would be in **E2** ... 😢 

We need to change the address on the website from to **16 Palmers Road** "***stat***" to avoid this kind of misunderstanding again. 👍

**Comment by iteles** [comment]
@nelsonic @harrygfox By law, our registered address SE5 needs to be on the website.

**Comment by nelsonic** [comment]
@iteles we _understand_ that. We can _either_:
+ have two addresses on the website and clearly indicate that one is a registered address and the other is a our office.
+ only have one address to avoid confusion and risk getting a fine...
+ _temporarily_ change our registered office address with Companies House to 16 Palmer's Road so it's all legit.

**Comment by iteles** [comment]
@markwilliamfirth Were you going to change the CH address temporarily anyway?
Let's get that done now so we can go with option 3!

**Comment by markwilliamfirth** [comment]
Was already half-way through PR so did option 1

registered address will be changed to 2 Palmers Road soon

**Comment by harrygfox** [comment]
Was also half-way through a PR so also did option 1 @markwilliamfirth 😉

**Comment by markwilliamfirth** [comment]
lol so many PRs e'rybody be like

# QUICK FIX THE WEBSITE IN CASE SOMEONE ELSE GET'S LOST

**Comment by markwilliamfirth** [comment]
(p.s. my bad for not following contributing guide and assigning myself + in progress) sorry!

**Comment by harrygfox** [comment]
Over to you to test, @nelsonic

**Comment by nelsonic** [comment]
@harrygfox / @markwilliamfirth _thanks_ for collaborating on making this update to the website.
![image](https://cloud.githubusercontent.com/assets/194400/23090609/74418e08-f599-11e6-8404-7dd9c8aa71c6.png)

Looks good. 👍 
Hopefully it avoids future confusion.
Hope you have a great weekend! 🛌  ☀️ ❤️
