### ISSUE TITLE
Creating our custom domain for herokuapp

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#207]
Our website (www.dwyl.io) is a herokuapp and we are often asked how to change the `herokuapp` domain to a custom domain. 

I'd like to have some documentation on this to point people to!

+ [ ] Why? What?
+ [ ] Step by Step instructions
+ [ ] Screenshots
+ [ ] Explanation of what is happening around the bullet points
+ [ ] ⚠️ Understanding whether the CNAME should be pointing to just the herokuapp url as it does with dwyl.io or whether it should have the target DNS provided by heroku (in this case www.quodl.co.uk.herokudns.com)
+ [ ] ⚠️ Discussion of application configurations and SSL certificates which has been giving us the biggest headache until now
+ [ ] Swapping out this example for healthlocker

**Comment by markwilliamfirth** [comment]
Closing as this has been merged
