### ISSUE TITLE
Redesign: hosting

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#209]
As far as I understand this is a static page - is there good reasoning for hosting it on Heroku? Doesn't this cost money? Wouldn't it be free and less complex to host the dwyl website using Github Pages?

**Comment by Cleop** [comment]
At what point during the redesign do we want to discuss hosting? For now should we expect people to test it locally?

What's the relationship between the live and redesigned sites and hosting? Can we host them separately or do they need to be in the same place?

Shall we simply create a '/redesign' route?

@nelsonic what are your thoughts?

**Comment by markwilliamfirth** [comment]
@Cleop this wasn't updated back in March. As far as I understand from @nelsonic he wanted to keep it on Heroku as there is more functionality that can be achieved with a server, e.g.

Custom 404 pages
Detailed analytics
Real-time notifications
Cookies

**Comment by Cleop** [comment]
Thanks for the update @markwilliamfirth, so I guess now all we need to know is whether/how we want to host the redesign until it's live. @nelsonic

**Comment by markwilliamfirth** [comment]
Until it's live let's continue with local previews

When it's live it'll be on Heroku unless we later decide otherwise
