### ISSUE TITLE
Change to .com

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#210]
Alter .com and .io DNS and Heroku settings
Main site = .com
.io site = forwards to .com

**Comment by markwilliamfirth** [comment]
www.dwyl.com is now working
Next stage is to get the dwyl.com root domain to work without forwarding to www

iwantmyname said:
>You would need to check out one of the hosting providers that allow this feature:
>- CloudFlare
>- DNSMadeEasy
>- DNSimple
>- PointDNS
>- Amazon Route 53 (only for hosting on AWS)


Heroku instructions are also here:
https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain

@nelsonic do you have any thoughts or objections to us moving the hosting to Amazon Route 53/AWS?

**Comment by iteles** [comment]
@markwilliamfirth Only that we lose all the nice devops layer functionality of heroku.

What is the negative effect of having the www routing to the non-www? Does it cause any issues for SEO for example?

**Comment by nelsonic** [comment]
We aren't using AWS for the dwyl website. It's more expensive and slower than alternative IaaS providers.
If we moved to AWS _today_ we would spend more money on infrastructure, add complexity and have _zero_ added value.
When we move from Heroku we will do it _right_.

**Comment by markwilliamfirth** [comment]
Based on comments above, sticking with www subdomain for now
