### ISSUE TITLE
Product Development div not sized correctly in Our Offerings

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/dwyl-site#211]
As you can see in the image below, the sizing is inconsistent. 

<img width="1919" alt="screen shot 2017-03-17 at 15 35 10" src="https://cloud.githubusercontent.com/assets/2305591/24050670/7ab8e008-0b27-11e7-8c89-a2b0bbf19ca0.png">

**Comment by markwilliamfirth** [comment]
Closing as redesign will solve this
