### ISSUE TITLE
@cleop picture needs to be resized

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwyl-site#213]
and compressed to a few kb
![dwyl-team-picture](https://cloud.githubusercontent.com/assets/6057298/24113068/7074d6ce-0d93-11e7-95f4-a8ef4ef06797.png)

**Comment by markwilliamfirth** [comment]
@cleop I think it needs to be square

**Comment by nelsonic** [comment]
@SimonLab well spotted. thanks for opening issue. 👍

**Comment by nelsonic** [comment]
@Cleop also, remember to add 2nd-Factor-Auth for security:
![image](https://cloud.githubusercontent.com/assets/194400/24125303/f9876d42-0dbf-11e7-8def-1d218705a692.png)
