### ISSUE TITLE
This is one of the (many) reasons makes dwyl different from the rest.

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#22]
http://www.nytimes.com/2015/06/29/technology/when-a-company-goes-up-for-sale-in-many-cases-so-does-your-personal-data.html
We will _never_ be bought/sold so your data is not going to end up in some mega-corp!

https://twitter.com/nelsonic/status/615799935720554496

**Comment by Cleop** [comment]
@nelsonic - is this something you'd like included somewhere on the dwyl site (if so, where?) or is this better off in another repo?

**Comment by markwilliamfirth** [comment]
Closing as this does not appear relevant to the website project
