### ISSUE TITLE
Fields for Contact Us Form on Website?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#220]
The current "Contact Us" for mon the website: http://www.dwyl.com/#contact has the following fields:
![image](https://cloud.githubusercontent.com/assets/194400/25975083/259c2b04-36a4-11e7-90e5-205a01ce8982.png)

Question is: should we _reduce_ these to say just `name` and `email` to lower friction?
Or _increase_ to get people to be _more specific_?

We could go down the route of having _more_ fields:
https://dockyard.com/contact/hire-us
![image](https://cloud.githubusercontent.com/assets/194400/25975017/d73173d4-36a3-11e7-8d08-33f041118a48.png)

**Comment by markwilliamfirth** [comment]
I think there should be a dropdown for what service/product is being enquired about and then the form should dynamically change according to what the customer is looking for

General enquiry - name, email, message
product development - the above plus budget and timelines
coworking - a link to focus hub appears and form changes to ask fixed/hot desk daily/monthly tour booking times
training - what area of training
etc

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/27282151-b939f354-54e6-11e7-824b-6162e7de739f.png)
This is the design for the new site, @markwilliamfirth @nelsonic  - please let me know if any of the fields mentioned above need adding?

Otherwise please can you close this issue?

**Comment by markwilliamfirth** [comment]
@simonlab do you know how complex it would be to create a dynamic form? i.e. depending on the product/service the user selects the form fields change? (as described [here](https://github.com/dwyl/dwyl-site/issues/220#issuecomment-301025429))

Would you be able to give a rough time estimate?

**Comment by SimonLab** [comment]
If we use checkboxes to select the type of enquiry, I think changing dynamically the content of the form can be done only with css. I don't think the logic is too complicated but I'm not sure about the design and how it will affect the current one by adding a way to select a specific form. For just the logic I would say around 2h. @Cleop do you think the estimate is right (I think it's similar to the burger menu logic)?

**Comment by Cleop** [comment]
The css revealing should be fine. 

In terms of how the form sends off data, @SimonLab do you imagine there being just one form that has optional parts (that the user wouldn't be able to see all of) and so only the completed parts get submitted? Or do you imagine there being say 3 different forms according to which option is selected?

**Comment by SimonLab** [comment]
I think both options are fine really. If the form were sending the data to different emails I would suggest 3 different forms but the data is sent to the same email and we just want to filter the type of data the user can sent.

**Comment by Cleop** [comment]
So @SimonLab is the 2hrs estimate just for the css logic or for building the forms to send? As I'm yet to test the functionality of this form as it currently is, I just copied it from the old dwyl site as I've been starting with styling only.

**Comment by markwilliamfirth** [comment]
Let's go with the dynamic form then!

@cleop form works using this https://github.com/dwyl/html-form-send-email-via-google-script-without-server I think

**General Enquiry** - Name, Email, Message

**Digital Product Development** - the above plus Budget and Timelines questions

**Coworking** - a link to Focus Hub appears and form changes to ask:
When would you like to come for a free tour? (text box that allows them to enter any time)

**Agile & Technical Training** - checkboxes appear asking what area of training:

Agile development methodologies
User testing
Human-centred Design
Customer development
Product ownership
Code
Cyber Security
Advanced Analytics
Data Visualisation

+ a box for any other comments

**Comment by Cleop** [comment]
So would you like the first field to just be - What's your enquiry about? (with nothing visible underneath or with the compulsory fields visible already underneath?)

**Comment by markwilliamfirth** [comment]
So there should be a dropdown box that is set by default to "General Enquiry". If people want to click on it they are able to change it to one of the other more specific enquiries. This way we have the best of both worlds - a simple completely minimalist form that with very low barrier to complete, as well as a more detailed form for those customers who are willing to be more specific with their enquiries.

**Comment by markwilliamfirth** [comment]
#270 should be completed before this

**Comment by iteles** [comment]
I don't understand the dependency on templating here, could someone please clarify? :blush:

**Comment by markwilliamfirth** [comment]
@iteles it's not a dependency, but a build preference - otherwise the code will need to be updated on every single page the contact form is on and tested on every page and any bugs / issues etc will need to be changed on every page. Makes sense to do #270 first to save everyone time

**Comment by ZooeyMiller** [comment]
for the dynamic form, it will be done with front end javascript whether on templating or not, so we don't have to wait for #270 to get to work on this.

**Comment by markwilliamfirth** [comment]
@ZooeyMiller Simon and Cleo suggested a CSS revealing solution here: https://github.com/dwyl/dwyl-site/issues/220#issuecomment-309411376 - is JS definitely required?

**Comment by ZooeyMiller** [comment]
@markwilliamfirth Sorry, no it's not, it's definitely do-able with CSS. I mentioned the CSS way in the call but neglected it when typing, apologies. Either way, it's independent of templating.

**Comment by nelsonic** [comment]
Contact form will be phased out ASAP as the **`SPAM`** is killing me! 
`GOTO`: #487
