### ISSUE TITLE
A Call to Action

### ISSUE THREAD

**Issue by harrygfox** [dwyl/dwyl-site#221]
We need to sell something singular and compelling that will **introduce** everything else dwyl has to offer. 
This call to action should be the first things visitors to `dwyl.com` see. (It can change!)

It is more important to know what dwyl **does** than what dwyl **is**. 
We need to construct a statement of _**value to the user**_.

In the immediate term:
> start building a mailing list of people **who are interested in _beta testing_ our applications**
> _this is happening right now, are you interested in exclusive beta testing_

**Comment by markwilliamfirth** [comment]
This has been covered as part of the redesign - closing
