### ISSUE TITLE
dwyl Site Redesign

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#223]
A redesign of the dwyl site is required in order to give it a fresh, new look that matches our current offering

**Comment by markwilliamfirth** [comment]
@harrygfox have the alterations to the dwyl-site design been completed yet? If there's anything that's unclear please open an issue in this repo and link it back to this one! Once they're done can you share them here please?

**Comment by harrygfox** [comment]
@markwilliamfirth Alterations are incomplete. Will share once they have been completed.

**Comment by harrygfox** [comment]
I believe this to be completed, please close if you're satisfied, @markwilliamfirth

**Comment by markwilliamfirth** [comment]
Nice! I think there are just a few things:

1. With regards to the blog, do the authors link to an author page that shows all the posts by that author?

2. Mission and Values page (referenced in footer) is the same as the about page - is that right?

3. Careers page:

**Careers**

Build exceptional products with the world's most creative companies.

At dwyl, you’ll work with a team of collaborative problem-solvers who are thoughtful, and talented. You’ll also work with hand-picked clients who have a positive social impact.

**Learn**
We value learning and sharing our knowledge. We want everyone in our organisation to develop their skills and experience over time.

**An amazing environment**
Located in the heart of East London, we’ve designed the space ourselves to be the ideal spot to get your work done in a productive environment.

**Unlimited Holiday**
We really don't want you to work yourself into a stupor, so take holiday whenever you need it. All we ask is that you come back fresh and ready to do your best work.

**Remote-first**
Work from wherever you want, whenever you want. Want to go live in Thailand? Ok. Want to work full-time while you travel around Europe? Sure. Send us a postcard.

**Excellent benefits**
Our generous benefits package includes your own pair of state-of-the-art wireless headphones and a company retreat to the Portuguese coast once a year.

**Job Opportunities** 

No open positions at the moment

Don't see what you're looking for? Reach out to hello+careers@dwyl.io

**Comment by harrygfox** [comment]
@markwilliamfirth 
1. Sounds like a great little feature - As long as it is clear that the user has just filtered the entire blog by one author and has a simple way of removing that filter
2. Yeppers
3. Happy to add shapes and colours to this if this is necessary and can be signed off on, otherwise it'll be down to the developers to infer styles for it 😄

**Comment by markwilliamfirth** [comment]
This issue has been split out and covered into lots of different issues - closing

**Comment by iteles** [comment]
@markwilliamfirth "Unlimited holiday" is a goal but we haven't got there yet! We need to discuss this and set the expectations before making it an official company policy 👍

**Comment by markwilliamfirth** [comment]
@iteles isn't it already in the contracts?

**Comment by Cleop** [comment]
To keep this all in an open issue, please can you confirm these things on this issue: https://github.com/dwyl/dwyl-site/issues/334

**Comment by iteles** [comment]
@markwilliamfirth Ah, unlimited unpaid holiday, I see what you mean 👍 
Works for me.
