### ISSUE TITLE
Link to GitHub + Show Highly Rated Repos

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/dwyl-site#225]
What does everyone think of having a GH link on the site? and potentially showing some of our highly rated repos? 

- [x] Link to GitHub on site

- [x] Show highly rated repos on a new content page

**Comment by Cleop** [comment]
@markwilliamfirth - please can you clarify this further? ie. where/what exactly...

**Comment by markwilliamfirth** [comment]
I think for now this can go on our portfolio page

In addition to our client work we also build and maintain a number of open source projects that help people to learn and **d**o **w**hat **t**hey **l**ove. Check out some of most highly-rated repositories here:

<img width="995" alt="screen shot 2017-09-20 at 13 19 26" src="https://user-images.githubusercontent.com/5732209/30643335-5db0d746-9e06-11e7-9e6a-461ea834b7cd.png">

[repos are individual tiles that link to respective repos]
