### ISSUE TITLE
Testimony from Recent / Current Client

### ISSUE THREAD

**Issue by harrygfox** [dwyl/dwyl-site#226]
I think it would be a great idea to get a quote from Geoff Campbell of Oxford Abstracts along the lines of:

> This is what Dwyl **did** for us - this is specifically the value that we were able to get from working with Dwyl

**Comment by harrygfox** [comment]
Linked to #223

**Comment by iteles** [comment]
Agreed 👍 
Need to work on getting what we need from all of our clients this week actually. Linked to https://github.com/dwyl/hq/issues/274

**Comment by markwilliamfirth** [comment]
Closing in favour of #305
