### ISSUE TITLE
Remove Anita from list of members

### ISSUE THREAD

**Issue by heron2014** [dwyl/dwyl-site#228]
Hi guys! 
Please could someone remove me from the site. As you all know I do not work for Dwyl (list of members is quite outdated). Thanks.

**Comment by markwilliamfirth** [comment]
Hi @heron2014 sorry! It is a little outdated - we're actually redoing the site in two weeks
Have sent a PR for you https://github.com/dwyl/dwyl-site/pull/229

**Comment by iteles** [comment]
Agreed @heron2014, we haven't looked at this for so long! 
Thanks for doing this so quickly @markwilliamfirth, will take a look now 👍

**Comment by heron2014** [comment]
Great! Thanks.
