### ISSUE TITLE
Redesign: agree capital letter conventions

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#234]
**For the site redesign we need to agree a convention for capital letters in titles / buttons.**

As a starting point I would say that as a minimum the first letter of the first word of a button should be capitalised ie.
<img src="https://user-images.githubusercontent.com/16775804/26923739-f8af53bc-4c3a-11e7-8517-4298c1a2783e.png" width=200px />

**After this should all words be capitalised or just the first?**
<img src="https://user-images.githubusercontent.com/16775804/26923773-14facec0-4c3b-11e7-9b24-fc0fca76aa4c.png" width=130px />
**This example should either have all caps or just the first:**
<img src="https://user-images.githubusercontent.com/16775804/26923783-1a177fa2-4c3b-11e7-9b2c-849ed8b63207.png" width=150px />

The same goes for titles...
![image](https://user-images.githubusercontent.com/16775804/26923863-6c3f1ec0-4c3b-11e7-91d8-7beaa7c4876f.png)
![image](https://user-images.githubusercontent.com/16775804/26923874-733480c6-4c3b-11e7-88cb-3574ec9d93ca.png)

**Comment by nelsonic** [comment]
Prefer To Capitalise Each Word In Headings ...
But Happy For Someone Else To Decide. 👍

**Comment by Cleop** [comment]
@markwilliamfirth - are you happy with this convention? This is what I have executed so far for both buttons and headings. If you're happy then please test and close the issue 😄

**Comment by markwilliamfirth** [comment]
@Cleop I would say we should use the following convention for titles/buttons:

Always capitalise:
- The first letter of a title
- The last letter of a title
- Nouns
- Pronouns
- Verbs
- Adjectives
- Adverbs
- Subordinating conjunctions (as, because, that)

Do not capitalise:
- Articles (a, an, the)
- Coordinating Conjunctions (and, but, or, for, nor)
- Prepositions fewer than five letters (on, at, to, from, by)

Examples:
Portfolio
Values
Enquire Now
How Can We Help?
The Right Solution
We Make Excellent Products
But Happy for Someone Else to Decide

**Comment by Cleop** [comment]
Thanks @markwilliamfirth - think there was a typo on: 
>The last letter of a title
What was that bullet meant to read as?

**Comment by markwilliamfirth** [comment]
@Cleop I've updated 👍

**Comment by harrygfox** [comment]
food for thought @markwilliamfirth @nelsonic https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98
@markwilliamfirth the way you described above is the way my english teacher told me to do titles! (<3)

**Comment by markwilliamfirth** [comment]
@harrygfox thanks for the link! Yes - this could change in future. Ultimately this is a branding decision and may well change! dwyl is written in lowercase, as lowercase often appears friendlier, but this is still under review https://github.com/dwyl/hq/issues/249 it might make sense to move to sentence case in future if it's decided that we'll maintain the lowercase branding of our company name.

For now I think this convention is a good start, as the key issue here is agreeing on consistency and conventions. This should be reviewed again when we assess our overall brand guidelines 👍

**Comment by markwilliamfirth** [comment]
Closing as this has been agreed
