### ISSUE TITLE
Redesign: implement consistent call to action/pop colour

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#236]
Aside from the dwyl mint colour, we need to agree on a pop or call to action colour for buttons etc. Currently the designs feature:
<img src="https://user-images.githubusercontent.com/16775804/26925793-0bae4740-4c43-11e7-8720-318b706ea4a8.png" width=200px />
<img src="https://user-images.githubusercontent.com/16775804/26925868-4ca94a10-4c43-11e7-8085-c33e1f7bf702.png" width=100px />

and
<img src="https://user-images.githubusercontent.com/16775804/26925798-10e2f7ba-4c43-11e7-954c-debcdf8adce1.png" width=200px />

During our meeting @nelsonic @iteles @markwilliamfirth @SimonLab and I discussed the yellow as a pop colour. Although @SimonLab mentioned that yellow can be perceived as a warning colour.

This https://www.usertesting.com/blog/2014/12/02/color-ux-conversion-rates/ blog says yellow associates with: 
<img src="https://user-images.githubusercontent.com/16775804/26925961-9a0b4a74-4c43-11e7-8bb2-1f374da220ae.png" width=250px />

http://usabilitygeek.com/colour-user-experience-psychology/ suggests: yellow is associated with the sun and hence communicates confidence, positivity, light and warmth.

Although the same site does say: 'While **some utilize a yellow warning sign** (again, there is a little leeway), the **vast majority of error notifications are accompanied by a big fat red symbol** to drive home the point that you do not want this option or color to show up.'
 in a separate article: http://usabilitygeek.com/colour-user-experience-psychology/

**Comment by Cleop** [comment]
Having spoken with @harrygfox on a call, he (unprompted) agreed with @SimonLab regarding yellow as 'caution' and said he preferred the initial apple green he proposed.

@iteles, based on the research findings above would you like to make a call on this one?

or @nelsonic do you have any strong feelings?

**Comment by harrygfox** [comment]
Interesting reading, @Cleop I've been looking more into it too! I've discerned that the most eye-catching colours are... well it doesn't matter.
> The color of the button has little to no effect on it’s own. What is more important is how it changes the visual hierarchy of the whole page, how it makes the call-to-action stand out.
_- https://conversionxl.com/which-color-converts-the-best/_
The important thing is Standing out! So without in mind I'd like to retract what I said about the green button and instead go for something like this:
![image](https://user-images.githubusercontent.com/7805691/27089469-5287340c-5052-11e7-9453-d52de238cae0.png)

**Comment by harrygfox** [comment]
Also [these people love orange buttons](https://unbounce.com/conversion-rate-optimization/the-future-of-marketing-call-to-action-buttons/)

**Comment by Cleop** [comment]
Any thoughts @markwilliamfirth @iteles?

@harrygfox if we opt for orange buttons, shall we keep the highlight colour consistent and use this on the numbers in circles and for the BETA sign (see screenshots in issue description)?

**Comment by harrygfox** [comment]
@Cleop No. According to the literature above, for the greatest effect in standing out as **THE** call to action - it should be the only instance of that colour on the page.

**Comment by markwilliamfirth** [comment]
Let's trial the orange that Harry's suggested
dwyl teal is 4DB6AC

Previous dwyl colours before redesign were:
<img width="154" alt="screen shot 2017-06-15 at 17 17 20" src="https://user-images.githubusercontent.com/5732209/27191075-9058b218-51ee-11e7-8129-e6e12a18dc20.png">

**Comment by iteles** [comment]
Only just got to this issue, but I agree, that was my comment for the CTA, it just needs to stand out from everything else. This means we probably need to think about the play with the client logos as well 👍

**Comment by iteles** [comment]
I do also really like how the App immediately draws your attention because of the colour of the Beta banner and would be hesitant to lose this. @harrygfox What are your thoughts on a starting point for testing?

**Comment by harrygfox** [comment]
@iteles My initial thoughts are that we could a/b test conversion rates based on the colour of one button vs another colour. that would require randomly serving different pages to different people in a 50/50 split. That would also require that we have 2 things to test i.e. two colours. 
Personally I think this might be a waste of time. I don't think the evidence of other similar A/B tests strongly (if at all) supports the notion that A/B testing reveals the best colour for CTAs. 

What do you think needs testing?

**Comment by iteles** [comment]
> I don't think the evidence of other similar A/B tests strongly (if at all) supports the notion that A/B testing reveals the best colour for CTAs.

It might be worth it if we were testing pop colour vs 'standard button' colour, but I agree that there are probably more important things to A/B test in the short run 😊

**Comment by Cleop** [comment]
So to conclude: I am going to change the colour of the 'Say Hello' button to the orange chosen by @harrygfox. All other highlighting colours (beta, yellow number circles) will remain as they currently are.

**Comment by markwilliamfirth** [comment]
@cleop nice 👍 I think the one in the picture is #fc865b

**Comment by markwilliamfirth** [comment]
Tested 👍
