### ISSUE TITLE
Redesign: gh pages research

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#237]
The site redesign will be built on a new branch using gh pages. However, we need to research the compatibility of gh-pages with an existing node project. The idea is to create the new website in a folder within the existing directory.

**Comment by nelsonic** [comment]
@Cleop GH Pages will not give us the flexibility we'll need to run our (content) markdown pages through https://github.com/dwyl/amp-elixir to be mobile friendly. 

we will be using Phoenix _later_ but for now a simple HTML page will work.

**Comment by Cleop** [comment]
In which case I will begin building the html files alone and simply open them in the browser to view them. Thanks @nelsonic

**Comment by nelsonic** [comment]
@Cleop you _coudl_ use https://www.npmjs.com/package/live-server to speed up your dev. 👍
