### ISSUE TITLE
Possible Game Title/Name?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#24]
https://domainr.com/boredgame.org?q=boredgame
<img width="653" alt="domain-bored-game" src="https://cloud.githubusercontent.com/assets/194400/8613231/8e47334c-26d4-11e5-86eb-2fff9dce04f3.png">

**Comment by iteles** [comment]
I think this is a pretty cool name. We should probably make an effort to come up with a name that's a little more descriptive of the game itself as well (when it's a little more formed) and then we can compare the two :+1: 

This is **assigned** to me, but I'm not sure what the task is here - to think of names that have possible domains available?

**Comment by nelsonic** [comment]
There, unassigned. :+1:

**Comment by iteles** [comment]
Let's pick this up again in August of this year? We may find a better repo for it!

**Comment by Cleop** [comment]
@iteles - can you think of a better home for this issue now? 🏡

**Comment by iteles** [comment]
@nelsonic All yours 👍

**Comment by nelsonic** [comment]
I opened this issue. so I'm closing it. ✅ 
Apologies, this issue is from a Simpler Time ...
