### ISSUE TITLE
Redesign: landing page html and styling

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#241]
Implement the styling for the new design of the site landing page (mobile first):

NAVBAR
- [x] Create navbar with white text items on dark grey background
- [x] Alternate navbar between horizontal on desktop and vertical on mobile
- [x] Add dwyl logo to navbar
- [x] Add Beta symbol to App on navbar

TOP BANNER
- [x] Create top banner lighter grey
- [x] Add 'We Make Excellent Products' title in white, centred
- [x] Create 3 white testimonial squares (that stack on mobile), with rounded corners
- [x] Create horizontal divide inside squares
- [x] Add copy above divide x 3
- [x] Add logos below divide x 3
- [x] Create primary button 'Start Your Own Success Story'

MINT MVP BANNER
- [x]  Create mint banner
- [x]  Add static title in white 'We can make your MVP*  *Minimum Viable Product'

RIGHT SOLUTION SECTION
- [x] Add 'The Right Solution (in 3 easy steps)' title
- [x] Divide the section into 3 horizontally (stacked on mobile)
- [x] Add 3 numbers in yellow circles
- [x] Add 3 titles
- [x] Add 3 subtexts
- [x] Add 'Meet your needs quickly and without waste' copy in mint
- [x] Add 'By iterating over these 3 simple steps we maintain a tight feedback loop between the people building and the people using.'
- [x] Add 'How Can We Help?' primary button

TRAINING + WORKSHOPS BANNER
- [x] Create mint banner
- [x] Add 'Training + Workshops' title, accessibility issue?
TRAINING SECTION
- [x] Create title
- [x] Create sub-title
- [x] Add bullet sections in 3 columns (stacked on mobile)
- [x] Add 'Enquire Now' primary button

CONTACT SECTION
- [x] Create mint section
- [x] Divide section into 2 columns
- [x] Add white 'Let's talk' title
- [x] Add contact details below
- [x] Create white form section on the right (not currently functional)

FOOTER
- [x] Create grey footer
- [x] Add 5 links
- [x] Add white horizontal divide
- [x] Add copyright statement

**Comment by markwilliamfirth** [comment]
👍
