### ISSUE TITLE
Redesign: portfolio text size

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#242]
@harrygfox, in the designs I noticed the test fitting in the portfolio boxes like so:
![image](https://user-images.githubusercontent.com/16775804/26936194-d655b10a-4c65-11e7-9bc0-fb0942a43181.png)
What is the adaptation for this in cases where the text is longer? Would you like it to finish with a '...' or will be designing the copy explicitly not to extend beyond this? Or should the box grow to fit the copy? or should all the boxes always be the same size?

**Comment by harrygfox** [comment]
The properties of the text and the images here are those of a table cell - the content is vertically and horizontally centred and the text aligned to the left. As we said today, _perhaps_ it should then become middle-aligned on a mobile-sized screen (or, rather, when the content stacks on itself). 

All that being said, I think that we should aim to never have more than three lines of text here (between 8 and 13 words). Strategically I think this will force the copy-writer/designer/developer to needle in to the real value that clients want and write only that.

**Comment by markwilliamfirth** [comment]
Linked to #89 

Closing as question has been answered
