### ISSUE TITLE
Redesign: font throughout

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#245]
@harrygfox - what's the name of the font used throughout your design?

- [x] implement the required font across the redesigned site.

**Comment by harrygfox** [comment]
@Cleop 
You can discover the CSS properties behind the wireframes by using Invision's 'Inspect' Mode.
You can enter inspect mode by either hitting the `I` key on your keyboard, or clicking the `<>` symbol at the bottom of the page.
Here is an example:
![group 3](https://user-images.githubusercontent.com/7805691/27030847-b16b44c4-4f65-11e7-9079-11f1efc20e29.png)

**Comment by Cleop** [comment]
Thanks for the detailed response @harrygfox 👍

**Comment by markwilliamfirth** [comment]
Tested 👍 

Note: we used to use Cabin, so Montserrat is a new font for us
