### ISSUE TITLE
Redesign: missing dwyl logo assets

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#246]
- [x] Add grey dwyl logo to the footer (awaiting file from @harrygfox)
![image](https://user-images.githubusercontent.com/16775804/27031880-09c111e0-4f6a-11e7-82d9-1066a79166e0.png)
- Add grey dwyl logo background to top banner (awaiting file from @harrygfox)
![image](https://user-images.githubusercontent.com/16775804/27031922-33b2635a-4f6a-11e7-8cfc-8aae216a60f1.png)

**Comment by Cleop** [comment]
@harrygfox has added the heart logo to the invision assets.
The background image is no longer in the designs.

**Comment by markwilliamfirth** [comment]
Tested 👍
