### ISSUE TITLE
Add burger to mobile menu

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#249]
Using tachyons, without js.

- [x] Burger icon appears to open menu on mobile
- [x] Burger icon is not visible on desktop
- [x] Clicking on the burger hides the menu (when it is clicked when the menu is open)
- [x] On mobile menu does not appear by default
- [x] On mobile menu appears when burger is clicked

**Comment by Cleop** [comment]
What would we like to close the menu on mobile? An X (the letter):

![image](https://user-images.githubusercontent.com/16775804/27044427-761c8786-4f95-11e7-9baf-1076e585d874.png)

Or a cross from font awesome:
![image](https://user-images.githubusercontent.com/16775804/27044450-8827ae2e-4f95-11e7-817c-ac313d7f97e2.png)

Or another alternative? Positioning can also change...

**Comment by Cleop** [comment]
To fulfil this the design will now echo what was implemented on [Research Resource](https://research-resource.herokuapp.com/) using a custom checkbox and a dropdown menu

**Comment by markwilliamfirth** [comment]
Nice 👍
