### ISSUE TITLE
Redesign: centre all buttons on mobile

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#251]
Buttons are centred on mobile:
- [x] Enquire Now
- [x] Say Hello

**Comment by markwilliamfirth** [comment]
@Cleop how do I view properly in mobile? This doesn't let me scroll

<img width="758" alt="screen shot 2017-06-15 at 17 10 28" src="https://user-images.githubusercontent.com/5732209/27190806-96416ec8-51ed-11e7-9fa8-b4aaa08e59a6.png">

**Comment by Cleop** [comment]
@markwilliamfirth - you're right, the last merged in version has the height of the nav set to 100% and so you won't be able to see what else is there until https://github.com/dwyl/dwyl-site/pull/264 for the burger menu is merged in.

**Comment by Cleop** [comment]
@markwilliamfirth - you should now be able to test this as the last PR has been merged in

**Comment by markwilliamfirth** [comment]
<img width="453" alt="screen shot 2017-06-19 at 09 55 05" src="https://user-images.githubusercontent.com/5732209/27277210-7bff821c-54d5-11e7-802c-74d97c733201.png">

I think this button sits within another div and may require some more centring

**Comment by Cleop** [comment]
Thanks @markwilliamfirth, removed margin-left on mobile please test again.

**Comment by markwilliamfirth** [comment]
Tested 👍
