### ISSUE TITLE
Redesign: 'We can make your MVP' - discuss design options

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#255]
@harrygfox has provided a new svg of the 'We can make/be your MVP' image (one for mobile, one for desktop), implement these and replace the existing text:
- mobile - currently awaiting the file for this from @harrygfox 
- [x] desktop

**Comment by Cleop** [comment]
@harrygfox designed this section for the landing page:
![image](https://user-images.githubusercontent.com/16775804/27141454-1d67cbbe-5120-11e7-8aed-ecf901ba8284.png)
We need to agree on the best implementation for it:
- png (current implementation, @iteles has concerns about responsive quality)
- hover variation (reads 'make' initially, on hover changes to 'be', suggested by @markwilliamfirth )
- any others?

@markwilliamfirth do you have any other ideas or given @iteles' reservations shall I go ahead with your hover idea?

**Comment by harrygfox** [comment]
@Cleop I have reservations about revealing key messages on the off-chance that the user hovers (with a mouse) over the correct text element.
@iteles What are your concerns about quality?

**Comment by markwilliamfirth** [comment]
@Cleop I wouldn't say hover, but on scroll. i.e. when the user gets to a certain scroll point the word changes

**Comment by iteles** [comment]
@harrygfox Actually, my concerns were a little more that when I first opened the page in invision, that immediately struck me as looking `messy` rather than `quirky` and I know giving it personality was the idea. I showed it to a couple of people (who are quite techy) and they took quite a while to figure out what was meant here.

As such, I think it just need a little redesign to make the meaning clear as I still love the idea 👍

**Comment by harrygfox** [comment]
Thanks for the clarification @iteles! I totally take your point. 
I think we could perhaps do something like have:
"We Can Make Your MVP" as the title for this section
and
"We Can Be Your MVP"
as the title for Training and Workshops (without losing the words "Training and Workshops").

It portrays the company's core offering and expands more on how we can be actively involved **with** an external company or team.

**Comment by Cleop** [comment]
@iteles Apologies if I didn't clearly communicate what you meant, thanks for clarifying.

**Comment by iteles** [comment]
@markwilliamfirth Thoughts?

**Comment by markwilliamfirth** [comment]
My suggestion would be for the word in the sentence to change as the user scrolls past, but this is a design decision and so it belongs to @harrygfox

**Comment by harrygfox** [comment]
I've had an idea @markwilliamfirth which I think this could be a nice balance between the super-technically simple and the more attractive/engaging 
![ezgif com-optimize 3](https://user-images.githubusercontent.com/7805691/27393442-3e6702f4-56a1-11e7-8e60-a2eaf7a9d403.gif)
Imaging the pands are the words `make` and `be` 
what do you reckon?

**Comment by markwilliamfirth** [comment]
To be more clear about my suggestion before, it would be something like this:
https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_css_scrolltop_class

This appears to be more of a background layer repeatable image trick
@harrygfox happy for you to decide - certainly worthy of testing I think 👍

**Comment by harrygfox** [comment]
Right, I understand your suggestion. My concern for the need for "the super-technically simple" was to avoid any use of javascript of _newer_ css properties. Moreover, the purpose of having the `make` and `be` fight over the same space on the screen is to represent the duality of our roles with clients: one as a service provider, another as an expert team-member/trainer. For this reason I don't think one word should absolutely replace the other. I was hoping this could be a middle ground between our two positions, @markwilliamfirth ?

**Comment by markwilliamfirth** [comment]
>the purpose of having the make and be fight over the same space on the screen is to represent the duality of our roles with clients: one as a service provider, another as an expert team-member/trainer

@harrygfox this is almost poetic ✍️ 
This is up to you! Please make a horse 🐴 , we don't want to end up with a [camel](https://en.wiktionary.org/wiki/a_camel_is_a_horse_designed_by_a_committee) 🐫 .

**Comment by markwilliamfirth** [comment]
Closing as this was discussed and Harry made the call

**Comment by iteles** [comment]
What was the call? 
Would be useful to record the actual conclusion in issues.

**Comment by markwilliamfirth** [comment]
@harrygfox to summarise his decision here

**Comment by harrygfox** [comment]
@iteles [#issuecomment-310121714](#issuecomment-310121714)

**Comment by markwilliamfirth** [comment]
Thanks @harrygfox 

Closing as this is a discussion issue

**Comment by iteles** [comment]
@harrygfox And what would propose is the graceful degradation of this? (When no JS is available)

**Comment by harrygfox** [comment]
@iteles my example uses no js - it's all css background properties

**Comment by iteles** [comment]
🎉 If you have that code, would be ace to link to it (unless I've missed it somewhere in the endless scroll of comments 😳 )

**Comment by harrygfox** [comment]
@iteles here is an example I made https://jsbin.com/dadinagojo/1/edit?output
this one uses absolute positioning though I think there are other ways of achieving the effect.
It uses the [background-attachment Property](https://www.w3schools.com/cssref/pr_background-attachment.asp)
