### ISSUE TITLE
Redesign: 'Meet your needs' not displaying side by side 'by iterating over' on desktop

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#258]
- [x] Make 'Meet your needs' display side by side 'by iterating over' on desktop.

Should be: 
![image](https://user-images.githubusercontent.com/16775804/27080203-ce9e392a-5032-11e7-942c-4aa7d807b952.png)
Currently:
![image](https://user-images.githubusercontent.com/16775804/27080216-d8f3195e-5032-11e7-8b22-de02df4d66f2.png)

**Comment by markwilliamfirth** [comment]
Yep
