### ISSUE TITLE
Redesign: change navbar color for greater contrast?

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#268]
Following @SimonLab's feedback and @nelsonic's color suggestions in: https://github.com/dwyl/dwyl-site/pull/264#issuecomment-308665411

- [x] Add shadow to the navbar to improve contrast against page background color.

For context it's worth mentioning that @harrygfox's designs already have two variations of the navbar depending on the banner color that exists per page. A light version and a dark version. As we're reviewing the dark version, one option would be to have the light version throughout the entire site. Here are the visuals:

**White**
This is the white nav next to a white cover background (ignore the blue links in the navbar, they show up when you screengrab on invision)
![image](https://user-images.githubusercontent.com/16775804/27177594-cf02cbfa-51be-11e7-8b53-a13ab764dd83.png)
Which looks like this when put next to the pages with a grey cover image:
<img src="https://user-images.githubusercontent.com/16775804/27177501-82de84a8-51be-11e7-9028-7c757e70ffce.png" width=200px />
<img src="https://user-images.githubusercontent.com/16775804/27177513-8dd28418-51be-11e7-95da-f309bfe17f94.png" width=200px />

AND/ OR

@nelsonic 's **darker** (`near-black`) suggestion
<img src="https://user-images.githubusercontent.com/16775804/27177628-e0a2775c-51be-11e7-98f2-f3cff0ee7905.png" width=200px />

![image](https://user-images.githubusercontent.com/194400/27172341-c36eab72-51ac-11e7-9e1f-0d57f2ab2ed6.png)

So do we want one color variation for the navbar or two? And do we want light or dark for these? @iteles @markwilliamfirth @nelsonic @harrygfox @SimonLab

**Comment by markwilliamfirth** [comment]
Probably more apt to opt for a dark theme such as #403f3f

**Comment by Cleop** [comment]
@harrygfox would you be able to confirm which color your prefer given the feedback about the contrast of your existing design?

**Comment by harrygfox** [comment]
@Cleop I've checked all the colours for AAA standard and the black on white and white on black are the best in terms of contrast ratio. 
This is how I hope the menus to work and look:
https://projects.invisionapp.com/d/main#/console/11013483/240170538/inspect

**Comment by Cleop** [comment]
@markwilliamfirth - this issue is confused. The issue is not about the contrast of text on a background. The issue is about the colour of the dropdown menu background on top of the background of the homepage.
See the bit where contact ends and the page begins:
<img src="https://user-images.githubusercontent.com/16775804/30284796-db59c3be-9713-11e7-9769-f9058be90168.png" width=250px />
The designs that Harry outlined are already implemented so if that's what you want then this issue can already be closed. What remains a question is, are we happy that the menu doesn't contrast with the page it is resting on in the case of the homepage.

**Comment by markwilliamfirth** [comment]
@Cleop Harry's designs actually have some drop shadow on the menu - is it possible to add that?

<img width="880" alt="screen shot 2017-09-11 at 19 08 54" src="https://user-images.githubusercontent.com/5732209/30289645-c02d829a-9724-11e7-8e0e-fa87a70b8d3b.png">

**Comment by Cleop** [comment]
![image](https://user-images.githubusercontent.com/16775804/30323237-4daa8cd2-97b4-11e7-9527-ab7f35a8848d.png)
