### ISSUE TITLE
Redesign: block scrolling when burger menu is open?

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#269]
@SimonLab asked in: https://github.com/dwyl/dwyl-site/pull/264#pullrequestreview-44226036

- Do we want to block the scrolling of the page when the burger is open?

On an iPhone 5, currently the menu takes up this much of the screen when open:
<img src="https://user-images.githubusercontent.com/16775804/27180634-48142d10-51cc-11e7-80f5-334750329815.png" width=200px />

- As it is so obstructive, do we want to block the scrolling of the page when it's open?
- If yes, how would we like this to look? Would we make the height of the menu background cover the entire screen? Would we blur the content beneath the menu? Or any other suggestions?

@iteles @nelsonic @SimonLab @harrygfox @markwilliamfirth 

Time estimate dependent on chosen implementation.

**Comment by SimonLab** [comment]
I just check the burger menu on the Github website. They allow to scroll on the page but the menu is not fixed at the top of the page, maybe this can be another solution?

**Comment by markwilliamfirth** [comment]
Confirmed that scrolling is not blocked when burger menu is open
