### ISSUE TITLE
curl command for getting added to mailing list?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#27]
So much nerd-love for how @Marak is encouraging people to join the mailing list for hook.io using a `curl` command ... see: https://github.com/bigcompany/hook.io/tree/60f7525475184d257206165860ef18fbabe94e1a#interested-but-too-busy-to-read-this-now

``` sh
curl hook.io?signup=youremail@marak.com
```

**Comment by Marak** [comment]
:-)

We'll be rolling out the first version of our terminal interface for the platform this month.

The first version will give users a guided experience of using the hook.io service entirely from `cURL` commands starting with `curl http://hook.io`

**Comment by nelsonic** [comment]
Hats off @Marak your labour of love project is *awesome*! :wink:

**Comment by markwilliamfirth** [comment]
@nelsonic what are the requirements for this issue to be closed?

**Comment by iteles** [comment]
@cleop or @SimonLab Can you have a think about how to make this happen? 😊

**Comment by SimonLab** [comment]
My first idea is to store the emails in a secure database but maybe we can use directly google as a storage as our email service is already managed by them.

@markwilliamfirth @iteles do we have a place where we store our current contacts at the moment or should we explore how to add new emails as contact to a google contacts group? Do we have an existing mailing list already?

**Comment by markwilliamfirth** [comment]
@SimonLab we have a google spreadsheet with contacts at the moment

I'm not sure if this issue is needed as people can sign up and directly be added to the google spreadsheet via https://github.com/dwyl/web-form-to-google-sheet

**Comment by markwilliamfirth** [comment]
This issue is no longer necessary as we have implemented this functionality with https://github.com/dwyl/web-form-to-google-sheet
