### ISSUE TITLE
Redesign: Values Page: Create white cover banner with text and logo

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#271]
**Values Page:** Create white cover banner with text and logo 
This is to be completed once the navbar is already in place for this page, pending the outcomes of #268 and #270 

- [x] Create white cover banner
- [x] Add grey dwyl heart logo (**awaiting asset** from @harrygfox)
- [x] Add 'Driven By Our Values' text, centred

**Comment by harrygfox** [comment]
Asset is green and available on invision 👍
