### ISSUE TITLE
Redesign: Increase the size of the dwyl heart on the navbar

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#272]
Following @nelsonic's feedback: https://github.com/dwyl/dwyl-site/pull/264#issuecomment-308665411

- [x] Increase the size of the heart-tick logo on the navbar

This is something I had deliberated over myself due to the tachyons included sizes. Currently using `w1` it looks as follows:
Mob
<img src="https://user-images.githubusercontent.com/16775804/27182740-320e3b16-51d4-11e7-9e66-c899efc82a2b.png" width=200px />

Desktop
<img src="https://user-images.githubusercontent.com/16775804/27182727-25722d36-51d4-11e7-8860-5efead87a6b0.png" width=400px />
OR
Using `w2` on Mob
<img src="https://user-images.githubusercontent.com/16775804/27182695-092f1d32-51d4-11e7-83c6-739a4873c718.png" width=200px />
and on Desktop
<img src="https://user-images.githubusercontent.com/16775804/27182704-0dcb7980-51d4-11e7-8424-8caafa8bd1f9.png" width=400px />

But because the `w1` seems too small and the `w2` seems to big, I'll opt for a custom class to get closer to the size from invision.

**Comment by markwilliamfirth** [comment]
Tested 👍
