### ISSUE TITLE
Redesign: Values page: dwyl dictionary definition section

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#273]
<img src="https://user-images.githubusercontent.com/16775804/27182172-3aa5892a-51d2-11e7-8a4f-0eff1edb9af0.png" width=450px />

- [ ] Create mint banner
- [ ] Add dwyl title with white bottom border
- [ ] Add NOUN text in grey
- [ ] Add Pronunciation text in bold with other text in italics, Times New Roman and special characters for
<img src="https://user-images.githubusercontent.com/16775804/27188627-9f9e7f76-51e6-11e7-8f13-a4c7b4d91c26.png" width=50px />

- [ ] Add Short for text and other in italics, Times New Roman
- [ ] Add definition text in italics, TNR.

**Comment by markwilliamfirth** [comment]
@Cleop here are the characters: dwɪɫ

**Comment by iteles** [comment]
@markwilliamfirth You were undecided on this section before - what were your reservations?

@cleop This is no longer on the homepage, correct?

**Comment by Cleop** [comment]
@iteles - this is part of the design for the Values page, just trying to start putting together time estimates for it

**Comment by markwilliamfirth** [comment]
@iteles we need to decide whether we actually want to market dwyl as an acronym - from our conversations in February I was under the impression you wanted it to be its own word and not short for 'Do What You Love'?

Also the definition might need some work - this can always be changed later though and shouldn't hold up the design

**Comment by iteles** [comment]
Yes, exactly. Maybe rather than 'short for' we should have 'Origin'?

It's easier to remember and has more meaning if you know it's not just a random set of letters thrown together.

**Comment by Cleop** [comment]
Closing as now moved to #299
