### ISSUE TITLE
Redesign: Portfolio Page: copy

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#280]
This is an entirely new page (non-existent on the existing site) so the copy needs to be created from scratch. We currently have links to 3 clients on the landing page so I imagine we'll be using these and elaborating on them:
![image](https://user-images.githubusercontent.com/16775804/27282311-51a8d27c-54e7-11e7-9023-8f86a782129d.png)

@markwilliamfirth I will leave this in your hands as I believe you probably know more about what you're after than I do 😊 

Depending on when you're able to work on this, please as a first stage make clear roughly how much copy to expect and on what subjects so that @harrygfox may be able to work with this for design purposes.

**Comment by markwilliamfirth** [comment]
**Online Databank for Museum Collections**
Client: The Science Museum Group (SMG)
Project: Collections Online
Application: https://collection.sciencemuseum.org.uk/
Source: https://github.com/TheScienceMuseum/collectionsonline
 
**Start Date:**
14 Jun 2016 - 31 Oct 2016 (Sprint 1 - 10)
28 Nov 2016 - 9 Dec 2016 (Sprint 11)*
May 2017 - May 2017 (Sprint 12)*
*Additional sprints are commissioned to build additional functionality based on user feedback
End Date: Ongoing
Project Length: 22+ weeks
 
**Problem Overview**
The Science Museum Group (SMG) owns a wealth of data on objects, inventors and archived documents. The Group was already working to clean up their data, but had no way for the public to access this information. The dwyl team undertook an initial requirements transfer workshop with the product owner and the SMG’s designer to understand the work that the SMG designer had already carried out with users. We established that the problem faced by the SMG was not just how to give the public access to the data, but how to do so in a way that those who wanted to use the data could do so with ease.
 
**Solution Overview**
The dwyl team created an online records system with a simple search interface and API functionality.
 
**Implementation Team**
Scrum Master
System Architect
Mid-level Developer
Mid-level Developer
 
**Technologies**
Node.js
Hapi.js
Elasticsearch
 
**Key Functionality:**
- A search website, making all of the Science Museum Group's data and artefacts accessible to the public complete with detailed filtering, images and pagination
- Search by people (birthplace, date, occupation), objects (categories, date, location, maker, object type, material, display status), documents (image, license, people)
- Search and interactive features allow the public to gain a greater understanding of the museum’s full collection
- An API enabling developers to access the data and create projects, as demonstrated at the Science Museum Hack Day
<img width="315" alt="screen shot 2017-06-19 at 17 24 37" src="https://user-images.githubusercontent.com/5732209/27295263-32b7d9d0-5514-11e7-8a3f-631a8790c6c4.png">
<img width="314" alt="screen shot 2017-06-19 at 17 24 30" src="https://user-images.githubusercontent.com/5732209/27295264-32bd77f0-5514-11e7-9cbe-57ed235b90b7.png">

**Comment by markwilliamfirth** [comment]
**Data Collection & Graphical Data Representation**
Client: Inclusive Classrooms
Project: Skills Wheel
Application: Offline
Source: https://github.com/InclusiveClassrooms/skills-wheel
 
**Start Date:** 
Feb 2016 - Feb 2016 (Sprint 1)
Mar 2017 - Mar 2017 (Sprint 2 - 3)*
*Additional sprints are commissioned to build additional functionality based on user feedback
End Date: Mar 2017
Project Length: 6 weeks
 
**Problem Overview**
Inclusive Classrooms is a small not-for-profit who help teaching assistants work with and monitor children’s social aptitudes and progression. Aptitudes are measured using a questionnaire that is displayed visually as a wheel. Up until this point, Inclusive Classrooms had manually collected their data and manually transferred it to a spreadsheet for analysis.
 
**Solution Overview**
This was a very short project (1 sprint) enabling digital data collection in a format that would be most useful to those analysing it.
 
**Implementation Team**
Scrum Master
Mid-level Developer
Mid-level Developer
UX/UI Designer
 
**Technologies**
D3.js
Heroku
Phoenix
Elixir

**Key Functionality**
- Data collection through intuitive and beautifully-designed interface for teaching assistants
- Simple visualisations of all data collected for each child for teaching assistants
- Administration functionality to view, filter and download data collected
- Admin functionality limiting the email addresses of those who could log in (preferred to enforcing registration)
- Utilisation of a dwyl open-source module to automatically save data into a Google spreadsheet
- Data was backed up to a redis database to allow for future expansion of the app
- 100% automated tests
- Continuous delivery
- PDF downloads implemented using open source module html-pdf
- Deployed to Heroku during development

<img width="301" alt="screen shot 2017-06-19 at 17 26 22" src="https://user-images.githubusercontent.com/5732209/27295334-7094cc2c-5514-11e7-9f6d-7647bc2a9559.png">

**Comment by markwilliamfirth** [comment]
**Online Membership Platform**
Client: The Ellen MacArthur Foundation (EMF)
Project: CE100
Application: https://www.ellenmacarthurfoundation.org/ce100
Source: https://github.com/emfoundation/ce100-app
 
**Start Date:** 
Sep 2016 - Oct 2016 (Sprint 1 - 2)
Dec 2016 - Jan 2017 (Sprint 3 - 4)*
Feb 2017 - Feb 2017 (Sprint 5)*
May 2017 - May 2017 (Sprint 6)*
*Additional sprints are commissioned to build additional functionality based on user feedback
End Date: Ongoing
Project Length: 12+ weeks
 
**Problem Overview**
The Ellen MacArthur Foundation’s (EMF) CE100 membership programme fosters collaboration among their members to discuss challenges and share insights, with the interaction among members being mostly contained to three physical events a year. Members of the dwyl team led an initial problem workshop to help the EMF team understand the pain points across the organisation and narrow down the area of focus to where the most value would be added - in this case, by solving the problem of lack of continuous engagement in their CE100 programme. This was then followed by two detailed design and technical workshops.

**Solution Overview**
A digital membership platform which allows members to share challenges and respond to challenges faced by other members.
 
**Implementation Team**
Scrum Master
System Architect & QA
Mid-level Developer
Mid-level Developer
 
**Technologies**
Node.js
Hapi.js
PostgreSQL
Redis
Amazon S3
Heroku
 
**Key Functionality**
- Member organisation directory + profiles (including mission statements and key contacts), created and maintained by the members themselves
- Creation and sharing of challenges with other members, increasing collaboration within the network
- Ability to add tags to your organisation and challenges, facilitating search functionality
- Exploration of challenges shared by other organisations
- Administration layer, allowing the EMF team to create new members, adjust their permissions, tie them to specific organisations and upload articles and resources to be shared on the platform
- Integrated email functionality for registration and password resets
- Highly modular architecture, ensuring new features could be added quickly and with minimal risk of impact on existing features
- A rigorous code review process was also put in place
<img width="177" alt="screen shot 2017-06-19 at 17 28 22" src="https://user-images.githubusercontent.com/5732209/27295406-bc7af710-5514-11e7-94f6-f1ed0063e8dc.png">
<img width="204" alt="screen shot 2017-06-19 at 17 28 12" src="https://user-images.githubusercontent.com/5732209/27295407-bc7c01aa-5514-11e7-8f84-74d0b97c71e1.png">

**Comment by markwilliamfirth** [comment]
With regards to the lists of technologies, let's not do these as a list. Let's do them as a row of tech icons:
<img width="628" alt="screen shot 2017-06-19 at 17 31 48" src="https://user-images.githubusercontent.com/5732209/27295562-3e7b8734-5515-11e7-95ef-30aeffc7c9e6.png">
<img width="643" alt="screen shot 2017-06-19 at 17 31 35" src="https://user-images.githubusercontent.com/5732209/27295564-3ea5dc96-5515-11e7-84d3-6537970b65ad.png">
<img width="641" alt="screen shot 2017-06-19 at 17 31 31" src="https://user-images.githubusercontent.com/5732209/27295565-3eaa47c2-5515-11e7-9252-b18aa8c1e15a.png">

**Comment by harrygfox** [comment]
Brilliant, @markwilliamfirth , thanks!

**Comment by markwilliamfirth** [comment]
Copy provided - closing
