### ISSUE TITLE
Redesign: Portfolio Page: design

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#281]
Once @markwilliamfirth has set out at least the type/ format of copy to expect (relates #280) for the Portfolio page, then @harrygfox can create the designs for this page.

At present, as mentioned in #280, the site will refer to work done with the Science Museum, inclusive classrooms and the Ellen MacArthur Foundation. @markwilliamfirth will indicate in #280 what else there will be copy for on this page.

- [x] Copy existing portfolio boxes
- [x] Set them against a white background
- [x] Add the 'Portfolio' title

![image](https://user-images.githubusercontent.com/16775804/28208772-4cd8314e-6887-11e7-9e31-da58bbb9f208.png)

**Comment by markwilliamfirth** [comment]
<img width="1065" alt="screen shot 2017-08-23 at 14 03 56" src="https://user-images.githubusercontent.com/5732209/29617198-f50b8c28-880b-11e7-8cd4-f4a21e0a1e87.png">

This needs to be in-line

**Comment by markwilliamfirth** [comment]
Tested 👍 

http://dwyl.github.io/dwyl-site/portfolio
