### ISSUE TITLE
Redesign: Team Page: copy

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#282]
@markwilliamfirth the existing Team page has no real copy (aside from team member names/ roles). We did discuss having a bio or similar for team members at one point. Is this still something you'd like to include? If so, will you be writing them or should we give people pointers to write their own?

**Comment by markwilliamfirth** [comment]
I think there are still a range of ideas surrounding the team page

I think we're going to need two pages

1. Community Page dwyl.com/join

**Our Community**

dwyl is a worldwide community of over 350 creative technologists that continues to grow.
 
We have people contributing remotely to our open-source projects from Angola, Argentina, Australia, Bali, Belgium, Brazil, Canada, China, Colombia, Estonia, Kenya, New Zealand, The Netherlands, Portugal, South Africa and the USA.

[Button] Join Us (links to GitHub join link)

Our development services are led by our core team[links to meet the team] based in London, UK. This is a troupe of 20 talented individuals with diverse backgrounds and a range of experiences and technical expertise. 

With something like this underneath/in the background: https://github.com/dwyl/stars/issues/18#issuecomment-309279708


2. Meet the Team Page

**Meet the Team**

image
name
job title
twitter
GitHub
Bio (50-100 words each in first person) - similar in length to https://buffer.com/about/team
bio can perhaps appear on hover/click on desktop or click on mobile?
I like this: https://pusher.com/team

**Comment by Cleop** [comment]
Thanks for this @markwilliamfirth - would you like both to be individually accessible from the navbar or will they both come under Team and then be accessed/ flicked back and forth from the team page?

**Comment by markwilliamfirth** [comment]
Twitter handles:

cleopearson
harrygfox
iteles
justenbarget
mskatbow
markwillfirth
nelsonic
robstaIIion
simon_lbd
shouston33
conorc1000
carlisle_jack
daniel_whyte
naazahmed11
inbarnoga

**Comment by markwilliamfirth** [comment]
https://github.com/dwyl/dwyl-site/issues/282#issuecomment-309474368

I think there should be an 'About' in the nav bar, this folds down into

- Our Mission (this is the page with the dictionary definition on)
- Our Community (but this also has a link to meet the team as described above)
- Meet the Team

Kinda like this
<img width="294" alt="screen shot 2017-06-19 at 16 45 30" src="https://user-images.githubusercontent.com/5732209/27293575-c0e6ebca-550e-11e7-91f3-7698eb30354a.png">

**Comment by Cleop** [comment]
Thanks @markwilliamfirth  - when you say 'Our Mission', would you like this to replace the values page? or just take the dictionary bit from the values page and the rest of the values page exist separately?

Also, how would you like this to look on mobile for the mobile navbar as that already drops down vertically?

**Comment by markwilliamfirth** [comment]
Yes - let's move that page under this umbrella

Let's call them:

Mission & Values
Our Community
Meet the Team

^This will likely evolve - we might have a partnerships section in future for example

Happy for hear feedback from you or @harrygfox here with regards the infrastructure architecture

>Also, how would you like this to look on mobile for the mobile navbar as that already drops down vertically?

This is a good solution for now:
<img width="482" alt="screen shot 2017-06-19 at 17 09 53" src="https://user-images.githubusercontent.com/5732209/27294658-48cdaa94-5512-11e7-8879-a9ff312b78c3.png">

On click:
<img width="479" alt="screen shot 2017-06-19 at 17 09 58" src="https://user-images.githubusercontent.com/5732209/27294646-378ab9fc-5512-11e7-9cac-fead8f255a24.png">

With regards to using this design as a reference:
Don't make everything uppercase - keep capitalisation consistent as we discussed #234 
Having a subcategory nav colour to signify difference to the user will be useful (doesn't have to be red obviously)
Please also indent subcategories slightly to show this more

**Comment by harrygfox** [comment]
@markwilliamfirth I've had a good old think about this (again, thanks for everything you've put in to it) and here's the long/short of it:
> I think we should consolidate these three pages into a single point of entry: an About page acting as a Values & Mission page, containing links to the (separate) Community and Meet the Team pages (not forgetting the sitemap links in the footer). 

- **Fewer links in the navbar is generally a good thing for conveying a clear 'call to action'** - ours, right now, being 'sign up'. My understanding from the last design meeting I attended was that streamlined focus on the goal du jour is a necessary business decision (@nelsonic). 
a good example of this is seen on duolingo:
Navbar
![image](https://user-images.githubusercontent.com/7805691/27348808-383e09e0-55ed-11e7-943a-64f116e6cf0c.png)
Footer
![image](https://user-images.githubusercontent.com/7805691/27348830-47f0c6d4-55ed-11e7-9545-de48fe139146.png)
Duolingo's website is SO focused that there is only one link on the navbar. We'll get there eventually! 👍 

- **Asking the user to reveal content to them creates usability/acces'ty issues.** 
I know this is one of the simplest of all: tab to reveal, hover to reveal, click to reveal etc. My concern is that resolving each of these and their various conflicts/browser support etc AND adding a vertical accordion to the navbar is going to add unwanted and unpredictable development time in build and maintenance. 

What dya reckon?

**Comment by markwilliamfirth** [comment]
@harrygfox happy for you to override any design decisions above as you are the Design Lead - do you know when @cleop can expect the final site designs? She's currently in active development, so would be good if we could get them to her soon.

**Comment by markwilliamfirth** [comment]
Closing as complete
