### ISSUE TITLE
Redesign: App Page: copy

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#284]
A new page, non-existent on the current site, so new copy. @markwilliamfirth please set out the copy for Time app and discuss or ask @sohilpandya to collaborate if/where necessary for added details.

**Comment by markwilliamfirth** [comment]
Inspired by this: https://www.tryflux.com/

**Time**
 
Time makes you more productive by tracking and analysing your daily activities.
 
Get started with Time
[First Name]
[Last Name]
[Email address]
[Submit]
 
[After Submit:]
Thank you for expressing your interest. We’re currently in alpha and will be releasing our beta product to a select number of people shortly. We’ll reach out to you when we’re ready to launch
[Image of rocket]

--

Content here is reliant on:
https://github.com/dwyl/time/issues/192
https://github.com/dwyl/hq/issues/328

**Comment by markwilliamfirth** [comment]
Closing as complete
