### ISSUE TITLE
Redesign: App Page: design

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#285]
A new page, non-existent on the current site, so new designs from @harrygfox . See #284 for copy advice and talk to @sohilpandya for any advice on visuals/ screenshots etc.
![image](https://user-images.githubusercontent.com/16775804/28209980-2393b8f2-688d-11e7-85b4-c15ac8aab762.png)
- [x] Light grey background
- [x] Title, subtitle and tag line on the left
- [x] Dark grey box on the right
- [x] Text on sign up box
- [x] Input fields on sign up box
- [x] Button on sign up box

Create this section but not the functionality.
<img src="https://user-images.githubusercontent.com/16775804/28215169-ec97bd0e-68a4-11e7-8ddf-14c08d4bce12.png" width=250px />
- [x] Add rocket 🚀 
- [x] Add thank you copy 
- [x] Add mint copy

**Comment by markwilliamfirth** [comment]
Closing as complete

**Comment by iteles** [comment]
I don't understand this issue (and a few others like it). It has design in the title, was closed then reopened without explanation and now code has been added. I'm assuming this is no longer about design?
