### ISSUE TITLE
Add bios for the team

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#288]
Linked to: https://github.com/dwyl/dwyl-site/issues/282

Hey everyone! We're adding bios to the new site! Exciting times. 🌠 

Please can you write a short bio in first person between 50-100 words? Some examples of what you could write are here: https://buffer.com/about/team

Don't worry too much about it, can always be edited later! I will check for spelling and grammar. Please post them in here 👍

**Comment by Cleop** [comment]
I'm going to work on mine now. Having had a little read of the buffer link, some recurring themes are:

- What do you do at dwyl?
- Why do you like working at dwyl? in particular, what about the culture?
- What do you like to do when you're not at dwyl? ie. hobbies / passions

**Comment by sohilpandya** [comment]
Hey! I’m Sohil and I’m a product developer and the resident videographer at dwyl. I love working with people who really care about education, open source ecosystem and drones! 

My day to day role at dwyl involves devloping for our product ‘time’, creating tutorials from the learnings whilst developing and producing video content for our YouTube channel. This flexibility and the ability for me to work with the people I love is what keeps me safe and happy at dwyl. 

Did I say that I Referee Beach Volleyball at a National level. 🤐😊

**Comment by shouston3** [comment]
I'm a developer for our dwyl client projects. I enjoy learning about new technologies day, as well as being able to see all of the different open source projects that are happening here at dwyl.

My day to day roles involve planning, scoping projects and delivering the goods. I like the organisation of dwyl's processes and being around so may people who I can bounce my ideas off of.

I used to sell door stops at University. 🚪 :stop_sign:

**Comment by Danwhy** [comment]
I'm a full stack developer at dwyl, where I love solving real, interesting problems with a variety of technologies. Constant learning and being around a diverse range of smart and interesting people is what makes working at dwyl amazing. Away from the computer, you'll usually find me drinking coffee and reading a good book.

**Comment by harrygfox** [comment]
Harry solves your problems and draws pictures so that dwyl developers can make those solutions. This level 3 unicorn loves semantics, making obscure cultural references, games, and the oxford comma. 
"Dwyl is great because they're a bunch of lovely nerds."

**Comment by markwilliamfirth** [comment]
Hi 👋 I'm Mark, the ops guy at dwyl. I manage our money 💰 , legals 📝  , hr 👨‍👧‍👦 , company admin 📜 and office 🏢 . I also oversee some of our internal and external projects 👨‍💻 👩‍💻. I probably do too many things, so we'll likely be hiring soon to deal with that; if you'd like to work with us then [get in touch with me](mailto:mark@dwyl.com) ✉️ ! I like things too, here are some of them: 🏓 🏂 📸 

--

[...probably overdid the emojis, but gonna roll with this for now 👍 ]

**Comment by markwilliamfirth** [comment]
@iteles @nelsonic @katbow @roryc89 @SimonLab @naazy @Conorc1000 @jackcarlisle @nogainbar @RobStallion 

Reminder to everyone to submit your bios! These aren't set in stone - you can make a PR and edit them as much as you want later on, we just need copy for the website design asap! Please submit them by the end of this week at the latest! 📪 

@edwardcodes @Jbarget @ZooeyMiller and @finnhodgkin you are also welcome to submit too (we can't assign you until other people have completed theirs - GitHub has a 10 people assignee limit per issue)

**Comment by iteles** [comment]
I can't believe how awesome you all are <3

@nogainbar is on holiday right now, I'll get mine done asap 👍

**Comment by naazy** [comment]
Hi I'm Naaz 👩🏽   and I'm one of DWYL's (_best_)  full stack developers.
I 💜  DWYL because I get to work with people who make me feel warm :fire: and fuzzy 👹  and I get paid 💰  to do what I love every day.

**Comment by edwardcodes** [comment]
Hey! I am a dwyl´s apprentice and learning materials reviewer 👍 i love dwyl´s goals and how they see education!
Away from keyboard i´m usually with friends on the beach or learning *new* things!😊

**Comment by naazy** [comment]
Hi I'm Naaz 👩🏽  and I'm one of DWYL's full stack developers.
I 💜  DWYL because I get to work with people who make me feel warm :fire: and fuzzy :bear: and I get paid 💰  to do what I love every day (_the dream_ 🌈). I'm also a killer 🔫  dodgeball :running_woman: :1st_place_medal: captain and a lover of wholesome fun ✨ 🍭

**Comment by Cleop** [comment]
OMG @naazy loving the magician's assistant fact ❤️

**Comment by ZooeyMiller** [comment]
I'm Zooey :wave: I'm a Graduate Apprentice with dwyl, I spend my time working on our open source learning resources and internal projects. I love helping other people learn, riding bicycles and eating hummus.

**Comment by jackcarlisle** [comment]
Hey, I'm Jack. I'm a full stack developer at dwyl and I love empowering people through technology. My day to day roles include working on client projects and building internal applications. When I'm not at the keyboard you can find me flying planes, eating and travelling.

Fun fact: I've ridden on an ostrich

**Comment by finnhodgkin** [comment]
I'm Finn :man_technologist: One of dwyl's Graduate Apprentices. I work with my buddy Zooey on internal projects and the dwyl learning resources, keeping everything up to date and bug free :no_good_man::bug:. In my spare time I climb, play table tennis and talk to the Elm compiler.

**Comment by markwilliamfirth** [comment]
Thanks @ZooeyMiller @jackcarlisle @finnhodgkin for posting today!

Just @nelsonic @iteles @katbow @roryc89 @SimonLab @Jbarget @Conorc1000 @nogainbar @RobStallion left to go! 🚀

**Comment by nogainbar** [comment]
I'm Noga, a Painter 🎨 turned Designer ✏️ turned Sculptor ⚒ turned Developer 💻 and back to UX and UI designer 💻 + 🖍✏️📌📎 = 🏛. This synaptic mishmash serves me quite well (🤹‍♀️)! especially when I need to express creative ideas to the brill devs at dwyl. I 💚 people and nature 🌴.

**Comment by roryc89** [comment]
Hi I'm Rory and I'm a dev at dwyl. I love the constant learning culture, friendly colleagues and possibilities for remote work! Been working with @Conorc1000 and @naazy  on a client project since I joined dwyl and very happy with the move :)

**Comment by iteles** [comment]
I'm co-founded dwyl because I wanted to use technology to help people and organisations realise their potential and make the world a little brighter in the process!
I make sure we're working with people doing great things, help our clients problem solve, provide training, try to make dwyl a little better every day, scrum master, and whenever I can, make time to code on our open source projects.
dwyl's values closely match my own :tada: and it makes me so happy to work with such amazing people every day!
I :heart: accessibility, sustainability, education and advocating for women in tech.

<hr>
This could do with shortening!

> I have made this longer than usual because I have not had time to make it shorter.
_Blaise Pascal_

**Comment by markwilliamfirth** [comment]
Thanks @nogainbar @roryc89 @iteles !

Now just @nelsonic @katbow @SimonLab @Jbarget @Conorc1000 @RobStallion ! 🚀

**Comment by RobStallion** [comment]
Hey, I'm Robert and I am a courier turned full stack developer. I love working with DWYL because I get to help build interesting projects that could really help a lot of people, while also allowing me to learn cool new technologies. The cherry on top is that I get to work with a diverse, smart and interesting group of people on a daily basis. Just an amazing combo!!! 🎉🎉

**Comment by markwilliamfirth** [comment]
Thanks @RobStallion !

@nelsonic @katbow @Conorc1000 @SimonLab @Jbarget left to go! 🚀

**Comment by Conorc1000** [comment]
Hi 👋  my name is Conor, I am a full stack developer at DWYL. My favourite part of working here is the DWYL Summer experience, where we all decamp to a lake house in Portugal for 2 weeks. Its at great chance to get to know the rest of the team better and catch some rays 🌞. The relaxed culture here makes it easy to get along with everyone.
I have also enjoyed the emphasis DWYL puts on personal responsibility, we get to play pivotal roles in projects from an early stage. We are also given lots of freedom to work remotely which has opened up so many great opportunities for me to travel more (Scotland, Spain, France, Mexico, Columbia) .
Outside of DWYL I am a keen boxer and motorcyclist 🏍.

**Comment by Jbarget** [comment]
Hello! Justen here 😄 ...
Im a full stack developer who likes to force myself into doing things that make me feel uncomfortable for the better, which has led me to: skydiving, boxing and colonic irrigation to name a few. I'd like to learn 4 languages 💬  before I die and I enjoy cooking 🍯 . I also like Groupon adventures. Things I like about DWYL: the general appreciation for hummus, interesting people, stimulating conversation and Elixir

**Comment by katbow** [comment]
Hey, I'm Katherine and I don't like writing bios. In another life I was a teacher and that's nudged it's way into my role as a developer at dwyl. I mostly write code for cool, socially impactful projects, but also love getting involved in client workshops. It's a great feeling to help people learn new things so they can be more involved in their own projects!

**Comment by naazy** [comment]
@Jbarget where's the 💩 github reaction when I need it??

**Comment by nelsonic** [comment]
"Short" Bio ...

```
"From phones to cars to medicine, technology touches every part of our lives.
If you can create technology, you can change the world!" ~ Susan Wojcicki

Hi! I'm Nelson and I'm on a quest to change the world with technology!
I systematically catalog & share everything I learn so that 
anyone can learn what I know fast and for FREE: https://github.com/dwyl?q=learn

My job is to write & review code, help others learn & grow and "unblock" things.

Interests: Any Technology or Idea that improves the lives of of people, animals and the environment.
e.g: "agritech" to improve food supply and eliminate hunger & malnutrition in the world, 
"medtech" to help people get/stay healthy and "edtech" to help everyone learn anything!

I've worked at/with/for over 40 organisations over the last 17 years 
on projects ranging duration from a few of weeks to couple of years 
and have a built a wide variety of systems from e-Commerce to e-learning platforms! 

I feel like I'm just getting started both in learning and making things!
```

Perhaps not especially "short". 
Feel free to edit it down to the number of words/characters you need.

**Comment by markwilliamfirth** [comment]
Thanks @Conorc1000 @Jbarget @katbow @naazy @nelsonic 

Just @SimonLab to go now and then we're done!

**Comment by markwilliamfirth** [comment]
@SimonLab a nudge on this one!

**Comment by markwilliamfirth** [comment]
@SimonLab please 🙏 submit a bio if you can even if it's only a couple of sentences. It would be great to have one from everyone on the dwyl team on the website

**Comment by iteles** [comment]
Done! Thanks @SimonLab and all!

**Comment by Rupeshiya** [comment]
@iteles  
Hi,I am Rupesh and I am a contributor in dwyl group and love to work in the group of people  who enjoy their work and finishes it off with all efforts.
