### ISSUE TITLE
Redesign: Create Community Page

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#289]
Designs from @harrygfox:
<img src="https://user-images.githubusercontent.com/16775804/27476950-90967c14-5802-11e7-80be-4f07cabe5292.png" width=500px />

- [x] Banner image
- [x] White section
- [x] Title
- [x] Subtext
- [x] Countries para
- [x] Join us button
- [x] Add github logo to button
- [x] Core team <p> with link
- [x] Regular page setup with navbar, contact us and footer
- [x] Mobile and desktop

- Where should the join us button go to?
- Font width issue with Montserrat, fw9 not the same as Harry's version.
- How would we like the banner image to look on mobile? It will be quite hard to tell what the image is meant to be of...

**Comment by iteles** [comment]
How do people navigate to this page?

**Comment by harrygfox** [comment]
@iteles from the About page

**Comment by markwilliamfirth** [comment]
love the community banner @harrygfox 

thanks @nelsonic for making this 🌈 👌

**Comment by markwilliamfirth** [comment]
@Cleop how do I access this?
<img width="338" alt="screen shot 2017-06-26 at 12 56 17" src="https://user-images.githubusercontent.com/5732209/27538226-e31fe5ec-5a6e-11e7-9eb8-e88e02a633ee.png">
<img width="1219" alt="screen shot 2017-06-26 at 12 56 07" src="https://user-images.githubusercontent.com/5732209/27538225-e31f26fc-5a6e-11e7-835b-9646b69ac20a.png">

**Comment by markwilliamfirth** [comment]
Inês just informed me it's http://127.0.0.1:8000/redesign/community.html

Looks good 👍 

Low-priority stretch goal for after site is published: https://github.com/dwyl/dwyl-site/issues/295
