### ISSUE TITLE
Redesign: Create Portfolio Page

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#291]
Create the first of our portfolio pages (EMF)
<img src="https://user-images.githubusercontent.com/16775804/27480814-9c8e8e6c-5811-11e7-9c6e-6795506f561f.png" width=400px />

- [x] Top white banner section with logo and titles x 2, 
- [x] shadow on bottom of first section
- [x] White body section
- [x] 1 column for app images
- [x] 1 column for copy
- [x] 2 buttons to App and Code
- [x] Copy paras
- [x] Technology section w images - awaiting hapi (ext dependency)
- [x] Align both columns at the top
- [x] Ensure all copy is the right typeface - Istok Web (for `<p>`'s)
- [x] Mobile / Responsive

**Comment by markwilliamfirth** [comment]
@harrygfox nice designs 👌

**Comment by markwilliamfirth** [comment]
This still requires links to repo and live app:

https://github.com/emfoundation/ce100-app

https://www.ellenmacarthurfoundation.org/ce100

**Comment by Cleop** [comment]
Can't add live link yet @markwilliamfirth: 
![image](https://user-images.githubusercontent.com/16775804/30274397-1bc74be8-96f5-11e7-96c2-fb4b5ee4bdb9.png)

**Comment by markwilliamfirth** [comment]
Blocked by https://github.com/dwyl/dwyl-site/issues/304
