### ISSUE TITLE
Redesign: Thank you for contacting us message

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#293]
At the moment in the redesign when a message is sent via the contact form, we get this:
<img width="674" alt="screen shot 2017-06-23 at 20 39 21" src="https://user-images.githubusercontent.com/4185328/27497870-90d18690-5854-11e7-9157-e95d90ae9694.png">

The styling here probably needs some more thought! Even if it's just moving the second sentence onto a separate line.

**Comment by markwilliamfirth** [comment]
@Cleop let's timebox to just spend one pomodoro updating this and see if that's enough for now

**Comment by Cleop** [comment]
First implementation, open to more instruction:
<img src="https://user-images.githubusercontent.com/16775804/30208044-af994614-9489-11e7-8d37-8509ff48bfdc.png" width=300px />

**Comment by iteles** [comment]
Works for the MVP 👍
