### ISSUE TITLE
Font weight is lighter compared to Invision designs

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#294]
Montserrat font used from google fonts can be downloaded at different font weights. Currently it is downloaded at default however, when thickening it to `font-weight: 900` using tachyons, it is still not replicating the thickness of some of @harrygfox's designs. If however, I alter the link that's being used to access it then this can be changed. However, I will have to go around and alter the elements that don't want to be made thicker!

@markwilliamfirth @harrygfox @iteles is this something you'd like to be prioritised?

E.g. Invision designs:
<img src="https://user-images.githubusercontent.com/16775804/27538088-5b59f0b2-5a6e-11e7-86f3-87128666a1c3.png" width= 480px />
Maximum thickness currently being done on site:
<img src="https://user-images.githubusercontent.com/16775804/27538094-600a1a38-5a6e-11e7-8d1d-725edd6f6ca4.png" width=400px />

**Comment by markwilliamfirth** [comment]
<img width="626" alt="screen shot 2017-06-26 at 13 07 01" src="https://user-images.githubusercontent.com/5732209/27538543-6008cd98-5a70-11e7-995a-8c42701401dd.png">

Perhaps use a bolder version of the Montserrat for these parts (not sure if this is a viable solution)? Whatever makes more sense - let's try and get as close to Harry's designs as possible, but if pixel perfect will take significant effort then we can take some shortcuts and mark it as a lower priority issue to fix later. We should try and get the site up and running as soon as possible and we can then continue to iterate on it.

**Comment by harrygfox** [comment]
I 100% concur @markwilliamfirth Progress over pixel perfection
