### ISSUE TITLE
Interactive Community Banner

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#295]
Building on https://github.com/dwyl/dwyl-site/issues/289

Let's explore some ideas around making the static-image community banner more interactive. Perhaps moving / live / animated / linking to people's profiles?

This is a stretch goal to be actioned after initial site design has been pushed up

**Comment by Cleop** [comment]
@markwilliamfirth - who would you like to be coming up with these ideas? you? Harry? Can you clarify this so the issue is ready to go?

**Comment by markwilliamfirth** [comment]
Harry hasn't been commissioned yet for additional work on this, at the moment this is just an idea and doesn't require additional design work

In terms of this idea, at the moment the MVP would be that the community banner profile pics link through to our actual community members
