### ISSUE TITLE
Redesign: Case Study pages: how to show the mobile screens on mobile view

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#296]
How should the mobile app demos be shown on mobile screens?
**Full size means it's readable but takes up almost the entire iPhone 5 screen:**
<img src="https://user-images.githubusercontent.com/16775804/27544007-cbb63478-5a83-11e7-866f-64fe7bf0311d.png" width=200px />
**Smaller means it takes up less space but isn't very readable (obviously would be centred):**
<img src="https://user-images.githubusercontent.com/16775804/27544034-d7023480-5a83-11e7-9500-23adc6e979cf.png" width=200px />
**@sohilpandya suggested having a half screen view of full size, something like this:**
<img src="https://user-images.githubusercontent.com/16775804/27543991-c2e4a532-5a83-11e7-8ff7-5755ddb92563.png" width=200px />

**Comment by harrygfox** [comment]
Here is an example of a combination of uses http://www.inktrap.co.uk/work/nomorefiling

This site uses full screenshots 3 in a row as well as larger cropped acreenshots and animated gifs of notable interactions

**Comment by markwilliamfirth** [comment]
@harrygfox happy for you to decide here 👍

**Comment by harrygfox** [comment]
@markwilliamfirth @Cleop Let's start small (in content terms) and grow from there. We currently only have two, maybe three screenshots per portfolio piece so let's just try to display those as cleanly and clearly as possible. We can come back later when there's time and money and improve with more variation and animation etc. 
I'd be tempted to go bold and big, @Cleop. Make them full sized and force the user to scroll past them. It may be an usability no-no but I would bank that users would comfortably scroll through all the content.

**Comment by Cleop** [comment]
@iteles suggested we just show one of the 3 images that are visible on desktop, how do you feel about that @harrygfox?

Happy to go ahead with the large size which means at least people will be able to see what the phones actually have on them!

**Comment by harrygfox** [comment]
@Cleop @iteles I think it underestimates how much people value design fidelity. we're visual creatures and pictures of apps makes them more tangible than descriptions of apps.

**Comment by markwilliamfirth** [comment]
Closing as question has been answered
