### ISSUE TITLE
Create low fidelity wireframes for remaining dwyl site pages

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#297]
As a developer working on the dwyl site and who already has a style guide as well as several high fidelity designed pages, I would like to have some wireframes for the remaining pages asap so that I can get going with building these and launching the site. 

@harrygfox As discussed, these will then be reviewed by you from a design standpoint and refined once the MVP is built :+1: 
Please feel free to edit this comment to add a checklist of pages so we know what's required!

**Comment by harrygfox** [comment]
@iteles Admittedly these were **higher-fidelity than agreed** (reasons available on request), but completed within the requisite time.

**Comment by markwilliamfirth** [comment]
These have been completed bar #306 

Closing this issue in favour of that one
