### ISSUE TITLE
Blog: Individual blog post page

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#301]
![image](https://user-images.githubusercontent.com/16775804/28217160-136a1632-68ac-11e7-9f37-154432632afa.png)
![image](https://user-images.githubusercontent.com/16775804/28217210-45b5a462-68ac-11e7-807f-a933b330711c.png)
![image](https://user-images.githubusercontent.com/16775804/28217196-368d6d9e-68ac-11e7-894f-5e38e01d51ad.png)
![image](https://user-images.githubusercontent.com/16775804/28217220-52340698-68ac-11e7-8ddc-3c68fa6968a2.png)

- [x]  Title text
- [x] Subheader
- [x] Author and date
- [x] Body
- [x] Thanks for reading!
- [ ] Share buttons
- [ ] Disqus section
- [ ] You might be interested in... (other blog post section)

**Comment by markwilliamfirth** [comment]
Personally I think it would be quite nice to also pull in the author's profile picture

**Comment by markwilliamfirth** [comment]
@cleop this will need to be created once I've done this https://github.com/dwyl/blog/issues/1

**Comment by Cleop** [comment]
Leaving share buttons, disqus reviews and 'you might also be interested in' section for another time.

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/dwyl-site/issues/355
