### ISSUE TITLE
Obtain permission to share existing case studies on our new site

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#304]
We have some case studies which are under review as per https://github.com/dwyl/hq/issues/274

We need written confirmation that these can be shared.

Assigning `p1` as the website should go live by mid-September at the latest.

- [ ] Confirmation that these can be shared
- [ ] Logo sign-off e.g. https://github.com/dwyl/dwyl-site/issues/331

**Comment by markwilliamfirth** [comment]
@iteles have we had any responses from clients?

**Comment by markwilliamfirth** [comment]
@iteles is there any update on this? We are currently working on EMF and speaking with them frequently so perhaps it might be easy to get this one approved quite fast?

**Comment by iteles** [comment]
I will post an update as soon as there is one 👌🏻

**Comment by iteles** [comment]
On this, a note that there are two questionnaire replies that are not in my chaser list. 
@Cleop Any updates from Elle on the questionnaire we sent at the 'official' end of LDMW? (The public launch of this is yet to happen but it might be good to nudge)
@markwilliamfirth I understand this is not the right time to chase Amanda for the questionnaire as you're working out the next steps but Im assuming this hasn't been filled in yet?

**Comment by markwilliamfirth** [comment]
@iteles i'm just conscious that this p1 was opened on 23 Aug and it's now 3 Nov with no movement - is there anything I can do to help? Is there anything in particular that is holding up the clients? Are they facing the same issues with approval? This feedback could help with regards to getting approval for tilr and OA too

**Comment by markwilliamfirth** [comment]
@iteles on BE questionnaire - the project is still in progress so we should get Amanda to fill it out after completion of this next sprint / next sprints

**Comment by iteles** [comment]
The vast majority of these were obtained at the time. No longer relevant.
