### ISSUE TITLE
Get quotes from clients for website!

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#305]
Needs to be done with #304 and for #88 

Assigning `p1` as the website should go live by mid-September at the latest.

**Comment by markwilliamfirth** [comment]
@iteles have we had any responses from clients?

**Comment by rub1e** [comment]
Draft saved [here](https://docs.google.com/document/d/1RgzBI8w3DKZQbY6lmO-2csVLIoArTfEaYByFizLGX0g/edit?usp=sharing) - please let me know your thoughts @iteles 💭

**Comment by iteles** [comment]
We got a few from this which I have archived but not relevant to our current iteration.
See https://github.com/dwyl/home
