### ISSUE TITLE
Careers Page Design

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#306]
Linked to #223 #297 

@harrygfox following your comment here https://github.com/dwyl/dwyl-site/issues/223#issuecomment-319080702

Please could you make a quick mockup of the careers page?

(copy is on the issue linked above)

**Comment by iteles** [comment]
Note: We're not hiring anyone outside of the people we already work with for the rest of the calendar year, so I would suggest this is considerably lower priority.

**Comment by markwilliamfirth** [comment]
@iteles we need a careers page regardless of how our hiring plans change, agreed it's not a massive priority now :)

**Comment by markwilliamfirth** [comment]
@harrygfox could you send us a quick design for this one in order to complete the set of initial wireframes? ( #297 )

**Comment by iteles** [comment]
Harry isn't currently doing further design work on the site and I'm not sure where this time estimate comes from.

We can re-open this when we need it.
