### ISSUE TITLE
Optimise dwyl site SEO

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#307]
Linked to https://github.com/dwyl/dwyl-site/issues/31

- [x] Decide what we want to optimise for
- [x] Implement optimisation

**Comment by ZooeyMiller** [comment]
What kinds of phrases are we looking to optimise for? @finnhodgkin and I are looking into doing some SEO on the site today, but we need to know what to optimise for in order to alter the copy.

The site already shows as the first result for `dwyl`, but what about more general search terms?

**Comment by markwilliamfirth** [comment]
Linked to: https://github.com/dwyl/hq/issues/328 https://github.com/dwyl/hq/issues/379 https://github.com/dwyl/hq/issues/157

**Suggestions:**
- app development
- mobile app
- mvp
- health
- medical
- education
- app developers
- website developers
- startup
- build an app
- development agency
- application
- applications
- apps
- need
- bespoke
- best
- london
- build
- developed
- developers
- development
- digital
- agile
- time
- tracking
- code
- technical training
- digital product development
- product development
- co-working
- design

@iteles what do you think?

**Comment by ZooeyMiller** [comment]
So, if we want to be present in searches for these kinds of terms then our content needs to reflect that, and we need to use these terms in our copy. 

Using meta keywords in not really relevant for SEO anymore so we can't just bung them all in as a list (#343), so in regards to these words they would have to be put into our copy, are @finnhodgkin and I okay to edit the copy? Or should we just raise issues related to SEO?

**Comment by markwilliamfirth** [comment]
@ZooeyMiller yep - the website copy on the redesign site is recent and will probably need to be changed several times over as we iterate so please augment the copy as you think appropriate, don't just put all of the suggestions in there though, only where they fit and make sense and then assign the PR for myself or Inês to review

**Comment by markwilliamfirth** [comment]
Also if there are other keywords and/or copy changes that you think might be good please suggest them as well!

**Comment by markwilliamfirth** [comment]
This was done 👍
