### ISSUE TITLE
Create list of SEO actions

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#31]
Create a list of what needs to be done to start showing up in the first page of Google search results by the end of August.

**Comment by iteles** [comment]
https://www.google.com/webmasters/tools/home?hl=en

- [x] Verify site using Google Search Console for more access to data (not strictly SEO, but still)

**Comment by iteles** [comment]
http://joshpitzalis.com/seo is a great resource!

**Comment by Cleop** [comment]
@iteles - when you say Google search results do you mean for searches of 'dwyl'? In which case - as we are now at the top of this, are you happy for this issue to be closed? Or were you referring to another search?

**Comment by iteles** [comment]
@Cleop This is a terribly described issue!
Let's close this in favour of one to determine what we want to optimise _for_ (if one doesn't already exist).

**Comment by markwilliamfirth** [comment]
Closing in favour of https://github.com/dwyl/dwyl-site/issues/307
