### ISSUE TITLE
Contact Form is Being Spammed

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#310]
<img width="783" alt="screen shot 2017-09-08 at 11 30 48" src="https://user-images.githubusercontent.com/5732209/30207922-315dc068-9489-11e7-9824-52016db8195f.png">

Not possible to block spam as from email address belongs to Nelson and the entered email address changes

**Comment by markwilliamfirth** [comment]
@Cleop is this due to testing? https://github.com/dwyl/dwyl-site/issues/309

<img width="779" alt="screen shot 2017-09-08 at 11 35 03" src="https://user-images.githubusercontent.com/5732209/30208092-de25c502-9489-11e7-8661-d5da126ececa.png">

**Comment by Cleop** [comment]
Yes it's me

**Comment by iteles** [comment]
Removed screenshots so as not to make email addresses unnecessarily publicly available.
