### ISSUE TITLE
Contact form email address

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#311]
Linked to https://github.com/dwyl/dwyl-site/issues/310

Update contact form email address from Nelson's to hello@dwyl.com

**Comment by iteles** [comment]
@markwilliamfirth It already sends to that email address, does it matter where the email comes from?

**Comment by markwilliamfirth** [comment]
@iteles yes because when we reply to the email thread, potential clients see the email address and it doesn't look professional, nor would I think that Nelson would want his personal email shared with clients

**Comment by iteles** [comment]
Ah, I tend to edit the reply because the format (no line breaks etc) looks bad to me anyway so this isn't a pain point for me 👍

**Comment by markwilliamfirth** [comment]
I think we should still update this as it's good to have it functioning from a company email as opposed to a personal email

Not a high priority though

**Comment by markwilliamfirth** [comment]
This can now be switched to hello@dwyl.com

**Comment by iteles** [comment]
This was done.
