### ISSUE TITLE
Host site on gh-pages

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#314]
Server is required for analytics and other issues such as https://github.com/dwyl/dwyl-site/issues/23

Nelson has expressed an interest for the site to be in Phoenix
https://github.com/dwyl/dwyl-site/issues/237#issuecomment-307075623

Cleo has confirmed Phoenix is likely to be a faster implementation than Node
+ this is also beneficial for Cleo to have more experience with our official new stack

Requirement: build the back end server in Phoenix to connect with HTML

@nelsonic (I know you're unavailable right now so I don't expect a response at the moment) and @iteles if you see this and have any input please let me know

**Comment by iteles** [comment]
@markwilliamfirth We don't actually need a server for the issues you have mentioned above (analytics and page load time), but rather just that the website is hosted somewhere where it can be tested (testing page load time locally isn't useful). 

I suggest we contain the redesign on a branch and deploy that to gh-pages very temporarily for ease of testing.
@Cleop If you go down this route, please ensure this URL is still available: https://github.com/dwyl/html-form-send-email-via-google-script-without-server/pull/148/files#diff-04c6e90faac2675aa89e2176d2eec7d8R286

@markwilliamfirth If there are any issues other than these that you reckon we do need a back end for, please let me know and we can review this position. 👍

**Comment by Cleop** [comment]
Having discussed this with some other dwylers I'm happy and understand this suggestion and think it will be fastest. I know speed is what @markwilliamfirth had as highest priority.

**Comment by Cleop** [comment]
Redesign is now available at http://dwyl.github.io/dwyl-site/

**Comment by iteles** [comment]
👍 @Cleop @markwilliamfirth Let me know when you need my review

**Comment by markwilliamfirth** [comment]
Closing as now on GH pages - top comment outdated, phoenix discussion will be revisited at a later date
