### ISSUE TITLE
How should/shouldn't javascript be used across the site?

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#317]
So far with the site redesign I've been working using the simplest solutions where possible. I know that not using js has accessibility advantages and we chose not to use it for creating the burger menu where there was a feasible non js alternative available. 

Now working on the team page I've tried to follow this avoidance of js which is looking to be possible. However my concern is with the state of the code without it. The team page is almost 600 lines long and now I need to add an adjustment to make my existing working version match the designs more closely: https://github.com/dwyl/dwyl-site/issues/283#issuecomment-329128896

I can foresee making this change to each of the 28 team members taking a while and increasing our already long file by another 150 lines of code. Before I plough ahead and do this I wanted to check in to see whether this non js ethos was to be applied across the entire site and if not, on which occasions we're happy to use js? The other alternative of course is to alter the designs which don't have to require this behaviour.

This is what we get without the extra work:

![image](https://user-images.githubusercontent.com/16775804/30374575-52b0d334-987d-11e7-8088-700bdf38fb18.png)

The extra work is to not push other team members down so the description sits on top of them and also to create a border around the whole of the card.

I think this issue somewhat depends on when #270 is put into play as well. They're both questions of - do we do what is fastest or simplest or when do we scale up more?

**Comment by iteles** [comment]
@Cleop Happy to use JavaScript to enhance the UX, but it *must* gracefully degrade to what you have above when JS is switched off 👍 
The important thing is that if JS is useful to make things clearer for the person viewing the site, a non-JS fallback must exist.

**Comment by iteles** [comment]
It's worth flagging in the issue when JS will be used @Cleop 👍

**Comment by Cleop** [comment]
Closing as answer provided.
