### ISSUE TITLE
Initiate process for acquiring dwyl.com ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#32]
@iteles following on from Sebastião's question:
Visiting dwyl.com today
re-directs to http://www.desiringgod.org/ which is http://www.desiringgod.org/about/overview

Sadly, no direct contact info ... http://whois.domaintools.com/dwyl.com

**Comment by enociz** [comment]
Do you guys really need to change to .com? I personally think that .io fits what you're doing better than a .com could ever do. Also, your audience is probably smart enough to Google "dwyl" instead of taking a stab at dwyl.com.

**Comment by nelsonic** [comment]
.com acquired. ✅
