### ISSUE TITLE
Usage of colour for CTA on app page

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#323]
Moved from https://github.com/dwyl/dwyl-site/pull/302#discussion_r137953274

**Comment by iteles** [comment]
@markwilliamfirth To clarify intention with that comment was not about the colour itself, it was about the quantity of colours and whether this was the right usage of the orange.

Propose a title change to: 'Usage of colour for CTA on app page' or something of the sort

**Comment by nelsonic** [comment]
**`ghost`** indeed ... 👻 
The internet doesn't forget even if you want it to. 🤷‍♂️ 
**`Web3`** will be _so_ much worse as distributed copies of _everything_ will persist for ever. 🕸️ 

https://twitter.com/iamdevloper/status/1085191415401897986
![image](https://user-images.githubusercontent.com/194400/195073538-344c927d-d256-4fb4-bb39-574caba306b1.png)
