### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#326]
- [x] Copyright 2017 © DWYL LTD, company number 09525434. Registered in England & Wales at Focus Hub, Unit 16 Palmers Road, London, United Kingdom, E2 0SY. All rights reserved.

**Comment by Cleop** [comment]
Is it dwyl ltd or DWYL LTD? @markwilliamfirth

**Comment by markwilliamfirth** [comment]
@Cleop 

everywhere dwyl is referred to in the site use lowercase dwyl

when it's the legal name revert to uppercase DWYL LTD like here https://beta.companieshouse.gov.uk/company/09525434
