### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#327]
- [x] IC and SMG don’t link from portfolio page
- [x] IC, SMG and EMF don’t link from home page

- [x] start your own success story doesn’t link to contact form
- [x] neither does how can we help
- [x] or enquire now

**Values page** - these don't work:
- [x] Join Our Community 
- [x] Meet the Team
- [x] Sound like somewhere you’d like to work? - should link to careers

- [x] Careers link doesn't work

**Team page**
- [x] Mark  - get in touch with me ✉️  should be a mailto to my email

- [x] Simon is not clickable - can we make him clickable with a blank bio so his github and twitter appear and add the bio later?

- [x] Contact link doesn't work

**Comment by Cleop** [comment]
We don't yet have a careers page @markwilliamfirth see: #306 - what would you like me to do for those links for the time being?

**Comment by markwilliamfirth** [comment]
@cleop please just push up this copy (https://github.com/dwyl/dwyl-site/issues/223#issuecomment-319077516) onto a new page and link it and we'll see if harry comes back with a design

It's not a massive priority so it doesn't matter if it's really pretty, we just need something there

**Comment by finnhodgkin** [comment]
Pretty sure none of the `img`s are going to work for nested pages.

They're all declared with relative paths `./img/...`. We could change all links including `img src`s from `/dwyl-site/` to just `/` and then it should work for images too.
