### ISSUE TITLE
IC and SM case study pages

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#328]
Linked to https://github.com/dwyl/dwyl-site/issues/327

Copy here:
https://github.com/dwyl/dwyl-site/issues/280#issuecomment-309492720
https://github.com/dwyl/dwyl-site/issues/280#issuecomment-309493158

**Comment by Cleop** [comment]
@markwilliamfirth - I need screenshot images of the app on a mobile phone

**Comment by markwilliamfirth** [comment]
@cleop is that a blocker or can we use the other images in the meantime?

**Comment by Cleop** [comment]
I'm uploading with the existing images. I just wanted to give you the chance to source alternatives if you have the time/ depending on how high a priority it is for you.
![image](https://user-images.githubusercontent.com/16775804/30479636-0806ab50-9a0e-11e7-899c-7c488bce1b0e.png)

For the technology icons I will currently only put in those we have. It's up to you how much this is an issue for you. On the IC page we currently will only have heroku listed.
