### ISSUE TITLE
Journalist App Reviews

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#33]
Should we collect a list of all the places apps get reviewed for when we get our app out?
e.g: http://www.theguardian.com/technology/2015/aug/14/best-android-apps-games-ninja-jamm-fallout-shelter

**Comment by iteles** [comment]
:+1: This seems as good a place as any!

**Comment by iteles** [comment]
+ [ ] https://makerba.se/

**Comment by iteles** [comment]
Added issue #36 on getting the word out instead of mixing things up here.

**Comment by Cleop** [comment]
@nelsonic - would this one be better off in the time repo?

**Comment by markwilliamfirth** [comment]
Closing in favour of https://github.com/dwyl/time/issues/200
