### ISSUE TITLE
Create Careers Page

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#334]
- [ ] Create careers page with the following copy and minimal styling

**Copy:**

Careers

Build exceptional products with the world's most creative companies.

At dwyl, you’ll work with a team of collaborative problem-solvers who are thoughtful, and talented. You’ll also work with hand-picked clients who have a positive social impact.

Learn
We value learning and sharing our knowledge. We want everyone in our organisation to develop their skills and experience over time.

An amazing environment
Located in the heart of East London, we’ve designed the space ourselves to be the ideal spot to get your work done in a productive environment.

Unlimited Holiday
We really don't want you to work yourself into a stupor, so take holiday whenever you need it. All we ask is that you come back fresh and ready to do your best work.

Remote-first
Work from wherever you want, whenever you want. Want to go live in Thailand? Ok. Want to work full-time while you travel around Europe? Sure. Send us a postcard.

Excellent benefits
Our generous benefits package includes your own pair of state-of-the-art wireless headphones and a company retreat to the Portuguese coast once a year.

Job Opportunities

No open positions at the moment

Don't see what you're looking for? Reach out to hello+careers@dwyl.io

**Comment by markwilliamfirth** [comment]
In response to https://github.com/dwyl/dwyl-site/issues/223#issuecomment-329764004

I think the unlimited holiday is correct as it is already in our contracts - @iteles to confirm
