### ISSUE TITLE
New SMG images

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#336]
Requested as per https://github.com/dwyl/dwyl-site/pull/333/files/02ddcbbb57b249d8c1994ce55eb1e9d9d9d4572b#r139168261

**Comment by iteles** [comment]
@cleop Took me one minute, so thought I'd do it, 2 to choose from:

<img width="1164" alt="screen shot 2017-09-15 at 16 31 11" src="https://user-images.githubusercontent.com/4185328/30490909-5e39e08a-9a33-11e7-8d2e-0d8d550dba09.png">

<img width="1133" alt="screen shot 2017-09-15 at 16 32 00" src="https://user-images.githubusercontent.com/4185328/30491071-f1f66cf8-9a33-11e7-8294-0fd905e024dc.png">

**Comment by markwilliamfirth** [comment]
@iteles these will need to be replaced by mobile ones as well

**Comment by iteles** [comment]
Sure! Took another couple of minutes:

<img width="346" alt="screen shot 2017-09-15 at 17 36 27" src="https://user-images.githubusercontent.com/4185328/30493563-72ca2ed4-9a3c-11e7-8e97-2f4479c1a11b.png">
<img width="344" alt="screen shot 2017-09-15 at 17 36 02" src="https://user-images.githubusercontent.com/4185328/30493564-72e81c28-9a3c-11e7-9fbb-001a4458ca68.png">

**Comment by markwilliamfirth** [comment]
@iteles should we not have two separate images with one showing search results maybe?

**Comment by iteles** [comment]
We can have whatever you think works well @markwilliamfirth, but the comment I made in the PR which is the only thing referenced in the description of this issue was just about this particular image being cut, so that's what I went on :blush:

**Comment by iteles** [comment]
Now a little time has passed, we could probably do with another update to the page to include something more like:
<img width="232" alt="screen shot 2018-02-12 at 18 02 13" src="https://user-images.githubusercontent.com/4185328/36111767-23c737a6-101f-11e8-9673-9ddc7d00f396.png">

**Comment by rub1e** [comment]
Answered by #445
