### ISSUE TITLE
Titles and descriptions on each page should be unique

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#344]
The titles and descriptions for each page should be unique, and should contain the kinds of terms we want to optimise for (in terms of SEO).

Having unique titles and descriptions makes it easier for search engines to distinguish between each page, and allows us to use the terms/queries we want to show up for, in a nice way.

**Comment by iteles** [comment]
Linked to https://github.com/dwyl/dwyl-site/pull/333#discussion_r139167661

**Comment by finnhodgkin** [comment]
https://github.com/dwyl/dwyl-site/pull/347#issuecomment-330883526

**Comment by markwilliamfirth** [comment]
👍
