### ISSUE TITLE
Accessibility: language attribute

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#345]
We need to add a language attribute to the HTML tag at the top of each HTML page. It's really important for accessibility. 
e.g. `<html lang="en">`

**Comment by ZooeyMiller** [comment]
@finnhodgkin has this been done on all HTML files now? Is this ready to be closed?

**Comment by finnhodgkin** [comment]
I think it should remain open until all the waiting changes from master are merged to gh-pages. Some pages exist in multiple places, one copy with the tag and one copy without.

Once this final merge is in we should stick to making PRs to the gh-pages branch rather than master.

**Comment by markwilliamfirth** [comment]
I've added this to every page on the gh branch so it should be fine now 👍
