### ISSUE TITLE
URLs should be relevant for SEO purposes 

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#348]
As mentioned in https://github.com/dwyl/dwyl-site/pull/333#discussion_r139167661 we need to make sure that the URLs for all of the pages are descriptive of the page, both for the sake of SEO and for the user. 

Since we're not using a server these need to be the file names.

**Comment by ZooeyMiller** [comment]
The only suggestions I have for now would be to change `app.html` to `time-app.html`, but we need to keep this in mind for any new pages we create.

**Comment by markwilliamfirth** [comment]
👍
