### ISSUE TITLE
app_google_form_handler.js fails linter

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#349]
The pre-commit/linter fails on the `app_google_form_handler.js` file. 

I think it's been missed up to this point as if you commit from withing the `redesign` directory then the pre-commit doesn't seem to run.

**Comment by ZooeyMiller** [comment]
Do we want to set up the linter to run on the  `app_google_form_handler.js` or should I just remove it from the linter? It seems to be doing quite a specific thing and I'm not sure if the goodpart linter is that relevant to it.

**Comment by markwilliamfirth** [comment]
@ZooeyMiller is this issue still needed? Not sure if removal of redesign means that it now works?

**Comment by ZooeyMiller** [comment]
@markwilliamfirth Now that we no longer have a package.json in master, we don't have any scripts, so it's not relevant. 

If we do want to enforce goodparts then it could be something that we look at adding back in, but currently, not really relevant.
