### ISSUE TITLE
Blog: Blog post: Read up on opposing views

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#35]
We need to have an even **better notion of views opposing #dwyl** (given it's our brand) so that we can form a constructive and cohesive set of thoughts on the subject.

[This](https://www.jacobinmag.com/2014/01/in-the-name-of-love/) is an interesting piece that should be read for example.

> There’s little doubt that “do what you love” (DWYL) is now the unofficial work mantra for our time. The problem is that it leads not to salvation, but to the devaluation of actual work, including the very work it pretends to elevate — and more importantly, the dehumanization of the vast majority of laborers.

**Comment by nelsonic** [comment]
The journos who are writing this have a *lot* of sand in their pants... :confused:

**Comment by iteles** [comment]
https://m.signalvnoise.com/do-you-have-to-love-what-you-do-762fa0a50bad#.h2gu5le6h

**Comment by Cleop** [comment]
@iteles - Would this be better off in another repo? Or would you like this idea to be conveyed at all somewhere on the dwyl site?

**Comment by iteles** [comment]
@cleop This is essentially a blog topic.

Having thought about this, we might end up with a separate repo for the blog, so let's park a blog label on this for now and move it once we finalise where to?
