### ISSUE TITLE
Contact anchor link not working. 

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#350]
The anchor link in the navbar for `Contact` has a href of `#contact`. In order for this to work the container we're linking to needs to have an id of `contact`, currently it has a `name` of `contact`.

**Comment by markwilliamfirth** [comment]
This should have been covered in #327

**Comment by ZooeyMiller** [comment]
Sorry, should I have added it to that issue? Just saw it and thought I'd quickly fix it.

**Comment by markwilliamfirth** [comment]
@ZooeyMiller no this is fine, just making a not to link them together
