### ISSUE TITLE
Individual blog pages functionality

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#355]
![image](https://user-images.githubusercontent.com/16775804/28217160-136a1632-68ac-11e7-9f37-154432632afa.png)
![image](https://user-images.githubusercontent.com/16775804/28217210-45b5a462-68ac-11e7-807f-a933b330711c.png)
![image](https://user-images.githubusercontent.com/16775804/28217196-368d6d9e-68ac-11e7-894f-5e38e01d51ad.png)
![image](https://user-images.githubusercontent.com/16775804/28217220-52340698-68ac-11e7-8ddc-3c68fa6968a2.png)

- [ ] Share buttons
- [ ] Disqus section
- [ ] You might be interested in... (other blog post section)

**Comment by markwilliamfirth** [comment]
Linked to #357

**Comment by nelsonic** [comment]
Good idea. No follow through. Closing. ✅
