### ISSUE TITLE
Add Live App Links to Portfolio

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#356]
Linked to https://github.com/dwyl/dwyl-site/issues/291

Add live app links

Blocked by https://github.com/dwyl/dwyl-site/issues/304

**Comment by markwilliamfirth** [comment]
Blocked by https://github.com/dwyl/hq/issues/377

**Comment by Rupeshiya** [comment]
From where to get live app link ?

**Comment by iteles** [comment]
They're not up yet @Rupeshiya, we're waiting for permission to share a couple of these still!

**Comment by Rupeshiya** [comment]
ok @iteles  waiting for link.!

**Comment by Rupeshiya** [comment]
@iteles  Can you provide the link now?

**Comment by iteles** [comment]
@Rupeshiya Are you looking for any in particular?

**Comment by nelsonic** [comment]
https://youtu.be/ns4TC_hEGKk
![image](https://user-images.githubusercontent.com/194400/45261258-61446880-b3f6-11e8-825c-9a3102a55d06.png)

**Comment by nelsonic** [comment]
No longe relevant as we are not going to focus on a "portfolio". 
We are 100% All-in on building our **`App`** now. 

**`GOTO`**: https://github.com/dwyl/mvp/issues/140
