### ISSUE TITLE
Getting the word out

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#36]
A collection of places where we can possibly get the word out about dwyl. Added to as we come across new things!
- [ ] http://onboarded.co/
- [ ] https://makerba.se/

**Comment by iteles** [comment]
Also, bloggers who blog about tools and workflows, e.g. https://webdesignledger.com/5-non-design-tools-your-design-business-needs

**Comment by Cleop** [comment]
@iteles - have these yet been actioned? Would you like this issue to be moved to a different repo? hq?

**Comment by markwilliamfirth** [comment]
Closing in favour of https://github.com/dwyl/hq/issues/157
