### ISSUE TITLE
Make Home Page Responsive

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#362]
https://github.com/dwyl/dwyl-site/pull/359#issuecomment-331206895

**Comment by iteles** [comment]
@markwilliamfirth This is actually a deployment blocker, especially if it's also the case with pages other than the homepage.

**Comment by markwilliamfirth** [comment]
@finnhodgkin could you take another look at further improving the responsiveness?

**Comment by iteles** [comment]
Disclaimer: I haven't pulled this down to review myself, I'm just going on the issue title.

**Comment by finnhodgkin** [comment]
@markwilliamfirth Sure thing. I'll just go page by page - good to get some tachyons practice :smile:.

**Comment by finnhodgkin** [comment]
Still  working on this.  It's taking longer than I thought to cover everything, mostly because it involves so much copy/pasting between pages.

**Comment by markwilliamfirth** [comment]
Thanks @finnhodgkin !

Linked to #354 #270

**Comment by finnhodgkin** [comment]
Took an extra 2h on top of my already underestimated previous estimate, partly due to the distraction of having Ed Miliband downstairs talking to Founders & Coders - strange day...

**Comment by markwilliamfirth** [comment]
Still to do:

As per https://github.com/dwyl/dwyl-site/pull/364#issuecomment-331963954

MVP section at medium scale requires revision - might require custom css

@finnhodgkin can you take a look at this when you have time?

**Comment by finnhodgkin** [comment]
@markwilliamfirth I can't get this to break on the live site. Are you looking at the latest version? Otherwise I guess it could be differences in browsers.

![selection_050](https://user-images.githubusercontent.com/22300773/30868212-e1b2a3ca-a2d5-11e7-80f1-ce057f07f923.png)

**Comment by markwilliamfirth** [comment]
@finnhodgkin I was just going by your comment, just looked at it myself on the live site and it looks like it works fine - I guess that means we can close this one now. Thanks for fixing the responsiveness! 🎉
