### ISSUE TITLE
Collected site fixes (responsiveness/tweaks)

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/dwyl-site#365]
I keep finding minor things that need updating around the site. Will keep a to-fix list here.

### Portfolio page:
The links are displaying in blue and there are responsiveness issues
![selection_028](https://user-images.githubusercontent.com/22300773/30804924-2c7e8134-a1e7-11e7-8e64-40dfdacae497.png)

### Values:
The definition section scales very strangely, jumping between too small when large and too large when small...

**No favicon for this page**

![selection_029](https://user-images.githubusercontent.com/22300773/30805274-9c107d58-a1e8-11e7-9505-24216b1b789a.png)

Can't tell if the left, right column adjustments are intentional or an unintended consequence of wrapping. Also on medium devices this padding is a bit too large:
![selection_025](https://user-images.githubusercontent.com/22300773/30805434-4a74e80c-a1e9-11e7-9a26-36ed7e98dcab.png)

Should have a max width for large format displays:
![selection_030](https://user-images.githubusercontent.com/22300773/30805517-a72599de-a1e9-11e7-97c7-8f6f9fdf8aa9.png)

### Team:
Padding problems at medium size:
![selection_032](https://user-images.githubusercontent.com/22300773/30806263-fbe0e084-a1ec-11e7-994e-cf99e064a675.png)

Because tachyons just has three breakpoints, the only way I could fix this was to display just one person per line all the way up to the large breakpoint. With two faces the bio becomes really thin and goes off screen:

![selection_032](https://user-images.githubusercontent.com/22300773/30806853-456cec00-a1ef-11e7-9a03-c0225bbdbce0.png)

Also Nelson's bio contains a link that's not clickable.

### Time app

The app section look strange above the contact section because it follows the same design (form on the right, text left) but isn't at all aligned with the contact section:

![selection_036](https://user-images.githubusercontent.com/22300773/30807170-9d3b3c7e-a1f0-11e7-8f94-6d5118fe3d99.png)

Not functional on medium devices:

![selection_037](https://user-images.githubusercontent.com/22300773/30807262-febfcc30-a1f0-11e7-9634-d287f4771391.png)

**No favicon**

**Comment by finnhodgkin** [comment]
I'm not sure about the fixes on the team page. I'll come back to them when I'm done with everything else and see if I can see a nicer solution. Maybe scaling up the profile images for the medium tachyons breakpoint will help.

**Comment by markwilliamfirth** [comment]
@finnhodgkin I was actually wondering if we should have 4 people per row on desktop as opposed to 3 to make the best use of space - is this easy to change?

**Comment by finnhodgkin** [comment]
@markwilliamfirth Done :smile:

**Comment by finnhodgkin** [comment]
Looks a bit squashed when the breakpoint is first hit:

![selection_039](https://user-images.githubusercontent.com/22300773/30815011-bfa11eaa-a209-11e7-802c-c2f33123f1ca.png)
