### ISSUE TITLE
Squashed text on the team page

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/dwyl-site#367]
The team bios get really thin when displayed at medium resolution:

![selection_039](https://user-images.githubusercontent.com/22300773/30852554-0cc440b4-a2a4-11e7-8050-058050ade131.png)

IMO it looks neater with a row of three breakpoint for this size:

![selection_049](https://user-images.githubusercontent.com/22300773/30852612-4620aeec-a2a4-11e7-8d60-a60804005e3c.png)

Could maybe even go down to two.

**Comment by markwilliamfirth** [comment]
👍
