### ISSUE TITLE
'Contact' covered by hamburger nav on mobile

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/dwyl-site#369]
Would be nice to have the hamburger menu close when contact is clicked, as is the case for all the other actual links:

![contact](https://user-images.githubusercontent.com/22300773/30855342-877987d0-a2ac-11e7-8acb-214d0c5976e7.gif)

**Comment by finnhodgkin** [comment]
Pretty sure this can't be achieved without JS...

**Comment by iteles** [comment]
Nice gif @finnhodgkin, what did you use to make it?

**Comment by finnhodgkin** [comment]
@iteles [Peek](https://github.com/phw/peek). It's crazy nice but unfortunately Linux only 😕

**Comment by markwilliamfirth** [comment]
This works!
