### ISSUE TITLE
Take recent changes to master and add them to gh-pages

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#373]
Due to @finnhodgkin and I not realising we should have been working off of gh-pages as a base branch we have made changes for the redesign which have been merged into master, there have also been different changes merged into gh-pages, meaning that the previous idea of merging master into gh-pages and then copying the bodies of the files in the redesign subdirectory into the files in the root directory won't work, and will require a huge amount of code reading.

Luckily, the changes merged into master are all quite small, so I am instead reading through the changes made in #347 #346 and making them manually in a branch to be merged into GH pages.

**Comment by markwilliamfirth** [comment]
Completed
