### ISSUE TITLE
Remove redesign folder from gh-pages branch

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#375]
The only purpose for the redesign folder in gh-pages (as far as I can see) is to allow for merging master into the branch, since we will be removing this process, so that for people to work directly on the redesign they will work from gh-pages as a base branch, I think we should remove the redesign folder. 

It is the source of all of the merge conflicts, and as of #374 will be out of  date.

**Comment by markwilliamfirth** [comment]
Completed
