### ISSUE TITLE
dwyl.com is down

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#377]
The github pages PR #316 was merged into master without switching off automatic deployment and the build failed so the website is now down.

![screen shot 2017-09-29 at 10 33 28](https://user-images.githubusercontent.com/4185328/31010276-3cdfdd2a-a502-11e7-94e3-004a3b0a077d.png)

We need to:
+ [x] Give @finnhodgkin and @ZooeyMiller access to the dwyl heroku app
+ [ ] Roll back to the previous version of the website
+ [ ] Diagnose the issues causing the site to be down and open separate issues on thes
+ [ ] Fix these
+ [ ] Deploy to gh-pages again for a final check
+ [ ] Once the green light is given, move the DNS over to gh-pages

**Comment by ZooeyMiller** [comment]
The old dwyl site is now hosted on http://dwylio.herokuapp.com/, with automatic deploys disabled and deploying from the rollback-to-old-version branch.

The DNS needs changing so that dwyl.com points to the heroku app instead of GH pages.

**Comment by ZooeyMiller** [comment]
it seems that as of 54d8d91c4344ebb826d6cdb182b028cbc0b3d676 the new version of the site is up with working links on http://dwyl.com

Should we still look into redirecting to the old site on http://dwylio.herokuapp.com/ or leave this as is?

**Comment by markwilliamfirth** [comment]
This appeared as it was down for a few minutes because I switched the DNS to gh pages - everything is working!
