### ISSUE TITLE
Goodbye Native

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#38]
![native](https://dh1rvgpokacch.cloudfront.net/atavist/26514/image/raw/iosandroid-1442172007-98.png)
https://atavistinsider.atavist.com/goodbye-native-mobile-apps

**Comment by sofer** [comment]
@nelsonic This looks totally sensible for publishers. The reasoning is less clear for the 10,001 startups aiming to be the next Tinder-for-X or Uber-for-Y.

**Comment by Cleop** [comment]
@nelsonic - Would you like to keep this open but perhaps in another repo? or is there any particular action you'd like to be taken for/from this?

**Comment by markwilliamfirth** [comment]
Closing as not related to site project
