### ISSUE TITLE
Unclear that title on blog page is a link

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#380]
On dwyl.com/blog we have the title of the blog post, and a short description. The title of the blog is a link to the full blog, but from the styling, to me, it's unclear that this is a link leading to more content.

![the blog web development agile methodologies and more dwyl - google chrome_038](https://user-images.githubusercontent.com/21139983/31012435-b247e128-a509-11e7-9659-51487f8618c3.png)

**Comment by markwilliamfirth** [comment]
Linked to this: https://github.com/dwyl/dwyl-site/issues/299#issuecomment-315331781

We need link conventions

**Comment by finnhodgkin** [comment]
I reckon also make the whole block a link and add '...' to the end of the summary. Or possibly even add some kind of arrow or a `read more` link at the end of the summary.

**Comment by markwilliamfirth** [comment]
Closed due to https://github.com/dwyl/dwyl-site/pull/392

Rest of discussion moved to https://github.com/dwyl/dwyl-site/issues/394
