### ISSUE TITLE
Inconsistent favicons

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#381]
I'm unsure if this is just standard favicon weirdness or not, but I'm getting inconsistent favicons across the pages.

![the blog web development agile methodologies and more dwyl - google chrome_041](https://user-images.githubusercontent.com/21139983/31013051-38ed745c-a50c-11e7-9637-9b03b3f88b24.png)

![the team product developers ux-ui designers scrum masters and more dwyl - google chrome_042](https://user-images.githubusercontent.com/21139983/31013058-3d9261e8-a50c-11e7-95ab-198bb7f94b88.png)

Is anyone else getting the same problems?

I would also suggest changing the teal heart with a white background to having a transparent background, the white background looks a bit weird on a browser tab in my opinion.

**Comment by markwilliamfirth** [comment]
Linked to #329

**Comment by markwilliamfirth** [comment]
done
