### ISSUE TITLE
Relative links no longer necessary

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/dwyl-site#383]
Now that the site is no longer hosted on a subdomain we can change most of the links from relative to absolute. So for example on the nested pages instead of a link to the homepage looking like:

```html
        <li class="ph4-l ph5-xl ph5 pt5 pb2 tl dn-l"><a href="../../../" class="white link">Home</a></li>
```

It can look like this

```html
        <li class="ph4-l ph5-xl ph5 pt5 pb2 tl dn-l"><a href="/" class="white link">Home</a></li>
```

**Comment by markwilliamfirth** [comment]
@finnhodgkin I didn't realise this worked (https://github.com/dwyl/dwyl-site/pull/382#pullrequestreview-66122029)

does the change only break local viewing?

<img width="1072" alt="screen shot 2017-09-29 at 12 12 42" src="https://user-images.githubusercontent.com/5732209/31013784-9517c3e2-a50f-11e7-88e7-b8d416d63b6b.png">

**Comment by finnhodgkin** [comment]
Yeah unfortunately absolute links won't work without live-server, which acts similarly to GH-pages in the way that it serves files (though links to other pages still won't work because they don't include .html). 

I would advise using `live-server` in development anyway because hot reloading makes everything speedier.

**Comment by markwilliamfirth** [comment]
solved by https://github.com/dwyl/dwyl-site/pull/385
