### ISSUE TITLE
Remove link to Blog

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#384]
Until we have blog posts, this doesn't make sense (and looks bad).

I suggest we remove the link to the blog from the nav temporarily.

<img width="986" alt="screen shot 2017-09-29 at 12 26 26" src="https://user-images.githubusercontent.com/4185328/31014180-853842ba-a511-11e7-83b3-38f794aa773e.png">

**Comment by markwilliamfirth** [comment]
I don't think it looks bad - it's a new blog, it's only supposed to have 1 blog post?

**Comment by markwilliamfirth** [comment]
Solved by https://github.com/dwyl/blog/issues/19

**Comment by iteles** [comment]
https://github.com/dwyl/hq/issues/247#issuecomment-281499493

**Comment by markwilliamfirth** [comment]
@iteles I'm not sure what you mean by your comment above
