### ISSUE TITLE
Add All Technologies Icons to Case Studies

### ISSUE THREAD

**Issue by ghost** [dwyl/dwyl-site#390]
Add all technologies icons to respective case studies

**Comment by ZooeyMiller** [comment]
From looking at the repos for the case studies, and looking at the readmes to see which technolgies have been used, all of them are now covered, apart from [wkhtmltopdf](https://wkhtmltopdf.org/). We don't have an asset for this in the invision design so I'm not sure if this is something we want a logo for.

**Comment by ZooeyMiller** [comment]
Links to the live pages for anyone wanting to take a look:
http://dwyl.com/case-studies/inclusive-classrooms/skills-wheel

http://dwyl.com/case-studies/ellen-macarthur-foundation/CE100

http://dwyl.com/case-studies/inclusive-classrooms/skills-wheel

The only one I've added logos to is Inclusive Classrooms.

**Comment by markwilliamfirth** [comment]
@ZooeyMiller please take a look at https://github.com/dwyl/dwyl-site/pull/414 :)

**Comment by markwilliamfirth** [comment]
@iteles as per https://github.com/dwyl/dwyl-site/pull/414#issuecomment-334201162 would you be able to advise if these are all of the technologies for these projects?

https://dwyl.com/case-studies/inclusive-classrooms/skills-wheel
https://dwyl.com/case-studies/ellen-macarthur-foundation/CE100
https://dwyl.com/case-studies/science-museum-group/online-collections

Linked to https://github.com/dwyl/hq/issues/377, #304

**Comment by rub1e** [comment]
Looks like the case studies on the site have all relevant technologies included.

Ready to close @iteles?
