### ISSUE TITLE
Time Beta App form email notification not working

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwyl-site#396]
Emails via the google app script form are meant to go to hello@dwyl.com but I received this email when someone recently tried to sign up:

![image](https://user-images.githubusercontent.com/16775804/31070753-6d28664c-a759-11e7-8cdf-511e29eff33c.png)

@ZooeyMiller @finnhodgkin - please can you look into this and check that names are also successfully being recorded on the spreadsheet?

**Comment by ZooeyMiller** [comment]
I don't think we have access to the spreadsheet? We'll be happy to look into it if someone shares it with us though.

**Comment by markwilliamfirth** [comment]
This is because hello@dwyl.com doesn't exist yet...making it now

**Comment by ZooeyMiller** [comment]
The info is being successfully recorded in the spreadsheet, from the test @finnhodgkin just did.

**Comment by finnhodgkin** [comment]
The time app form works but the success message really doesn't look great:
![selection_056](https://user-images.githubusercontent.com/22300773/31071785-46b796c8-a75d-11e7-832a-b6b345b50ce2.png)

**Comment by iteles** [comment]
YIKES! I'm surprised this wasn't tested!
![screen shot 2017-10-02 at 12 43 40](https://user-images.githubusercontent.com/4185328/31075827-5c51c4d8-a76f-11e7-97bf-7d2b342a22f8.png)

@finnhodgkin This is an 'easy' fix, looks like it was Part 2 of https://github.com/dwyl/html-form-send-email-via-google-script-without-server#part-two---make-it-look-good- that was not implemented (or has a bug and isn't working).

Could you look into this as a matter of urgency please?

**Comment by Cleop** [comment]
It should change to the rocket, I did implement and test this. Might this have got lost when @markwilliamfirth merged things in?

**Comment by ZooeyMiller** [comment]
@iteles sorry, we have been working on this, forgot to add in-progress label. PR is imminent.

**Comment by markwilliamfirth** [comment]
@Cleop perhaps

I remember this working before too and I think this is the commit? https://github.com/dwyl/dwyl-site/commit/b5a69e4a5c8bc0a9d065b2b5bc8f85e9d9b8707f

**Comment by finnhodgkin** [comment]
It's in the accessibility PR #391 

The rocket is back :rocket: 

I can't double check that the normal contact form still works but otherwise it's all in shape.

**Comment by iteles** [comment]
Still works @finnhodgkin , got the email 👍

**Comment by markwilliamfirth** [comment]
Success message now works

**Comment by markwilliamfirth** [comment]
Email notification for time app sign-up still doesn't work

Email for normal contact form does work

**Comment by finnhodgkin** [comment]
The time app signup form is working in that it updates this spreadsheet. Should it also be pinging an email? 

https://docs.google.com/spreadsheets/d/1PfPRD54M6K2hiN-1IkTC7IkJVRMAuEGoX1qz2cK5HrQ/edit?ts=59d204cc#gid=0

**Comment by markwilliamfirth** [comment]
@finnhodgkin I didn't think that was part of the original plan, but that's what the issue title says

**Comment by markwilliamfirth** [comment]
@cleop (to clarify) is the intention for the form to also ping an email every time someone signs up?

**Comment by markwilliamfirth** [comment]
hello@dwyl.com has now been set up

**Comment by markwilliamfirth** [comment]
<img width="547" alt="screen shot 2017-10-03 at 14 39 02" src="https://user-images.githubusercontent.com/5732209/31128083-a10f1628-a848-11e7-8b6a-2e1330f9a7e5.png">


This works now!

@Cleop can we change the script to come from hello@dwyl.com ?

**Comment by iteles** [comment]
@markwilliamfirth Can we please close the original issue and open as a new issue for clarity? https://github.com/dwyl/dwyl-site/issues/396#issuecomment-333844810

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/dwyl-site/issues/416
