### ISSUE TITLE
Improve dwyl Portfolio GitHub Repo Cards

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#401]
Linked to #399 , https://github.com/dwyl/dwyl-site/issues/225

Ideas from @finnhodgkin 
- http://lab.lepture.com/github-cards/#dwyl/learn-elm-architecture-in-javascript|default That way the stars would update and it would display as text (better for SEO)
- Would be better to make html cards for these with text. They don't resize very well at smaller resolution
- Wait for #389 until the site has a backend and then use the GH api to display nicely formatted cards with updating stars/watchers

**Comment by finnhodgkin** [comment]
Having a go at converting these to hard-coded html. The github-cards thing I linked before seemed to get rate limited very quickly, and was also stuck to a sub-par design that doesn't really fit with the dwyl.com aesthetic

**Comment by finnhodgkin** [comment]
The links were breaking on mobile because they weren't set to `display: block` when not `table-cell`.

**Comment by markwilliamfirth** [comment]
looks great
