### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID connection is not private

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#405]
Anyone `else` seeing "***Your connection is not private***" when visiting: https://www.dwyl.com/
![image](https://user-images.githubusercontent.com/194400/31119465-73d256fa-a831-11e7-9430-6a3ff3ff3be0.png)

**Comment by nelsonic** [comment]
After refreshing the page it _appears_ to be working:
![image](https://user-images.githubusercontent.com/194400/31119578-c47925e8-a831-11e7-9219-ab9c3ae797be.png)

Closing.

**Comment by nelsonic** [comment]
Nope, a minute later the Privacy issue is still there:
![image](https://user-images.githubusercontent.com/194400/31119872-ba7d2c64-a832-11e7-959e-96a406922d8b.png)

**Comment by nelsonic** [comment]
More detail:
```
dwyl.com uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
![image](https://user-images.githubusercontent.com/194400/31119916-f1b45270-a832-11e7-97d6-6a191182a3a8.png)

Using GitHub pages with custom domain is causing the fail.

**Comment by ZooeyMiller** [comment]
Related to #378.
We need to set up the [cloudflare hack](https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html) in order to use https AFAIK.

**Comment by markwilliamfirth** [comment]
@nelsonic yes it's not a secure connection - closing in favour of https://github.com/dwyl/dwyl-site/issues/378
