### ISSUE TITLE
Differences between InVision design and live site

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/dwyl-site#407]
## Home page

The navbar is quite different on the live site:
- There's a shadow https://github.com/dwyl/dwyl-site/issues/268#issuecomment-328611498
- It's a different colour from the background https://github.com/dwyl/dwyl-site/issues/268
- It doesn't change colour depending on the background colour of the page
- There's more spacing between links (though it's also larger because there are now more links)

The title is larger and has more padding in the designs. Also different capitalisation https://github.com/dwyl/dwyl-site/issues/234#issuecomment-308735303

The portfolio logos are smaller and the font size is larger. https://github.com/dwyl/dwyl-site/issues/294#issuecomment-312851776

![selection_062](https://user-images.githubusercontent.com/22300773/31119976-c8f2b83e-a82a-11e7-9111-d2fb0261c4e0.png)
![selection_063](https://user-images.githubusercontent.com/22300773/31119985-cac1bda4-a82a-11e7-8479-eec342f475b5.png)

### MVP section:
- Background colour not the same 
- The content isn't contained in a box
- Title text not centered
- Text a different colour
- Button and follow-up text not in a separate section

![selection_064](https://user-images.githubusercontent.com/22300773/31119990-d1f98048-a82a-11e7-900a-e852a6579599.png)
![selection_065](https://user-images.githubusercontent.com/22300773/31119991-d429a1e0-a82a-11e7-84b2-bf6c1b9c69c9.png)

### Training section
- Content not contained in a box
- List not styled
![selection_066](https://user-images.githubusercontent.com/22300773/31119994-d8826f7e-a82a-11e7-8cea-4201cb76be81.png)
![selection_067](https://user-images.githubusercontent.com/22300773/31119998-d9c1824e-a82a-11e7-8a00-6016d0a74ef2.png)

**Comment by finnhodgkin** [comment]
# Portfolio page:
- As above, white nav on white background.
- Smaller portfolio cards
- Thinner max width

![selection_068](https://user-images.githubusercontent.com/22300773/31120557-c8ee58e6-a82c-11e7-8f32-263f1db5777a.png)
![selection_069](https://user-images.githubusercontent.com/22300773/31120559-caaccb5e-a82c-11e7-8819-9682ff80c61f.png)

**Comment by finnhodgkin** [comment]
# Values:
- Larger shadow as a separator
- Much larger top padding
- White nav
- Off-white background

![selection_071](https://user-images.githubusercontent.com/22300773/31120763-95ab74ae-a82d-11e7-8364-8d5b9e1c0ca0.png)
![selection_070](https://user-images.githubusercontent.com/22300773/31120765-972748c6-a82d-11e7-9054-548fb666885a.png)

**Comment by finnhodgkin** [comment]
# Blog
- Much more padding
- Larger title font size
- Larger copy font size

![selection_072](https://user-images.githubusercontent.com/22300773/31120911-1534e502-a82e-11e7-908a-5ebe0ad5357c.png)
![selection_073](https://user-images.githubusercontent.com/22300773/31120914-171641ea-a82e-11e7-93f2-a89a7df93c92.png)

**Comment by markwilliamfirth** [comment]
@finnhodgkin some of these difference might have been for speed of getting the site up, the ones that have reasons I've edited your comments to add the respective piece of information

**Comment by finnhodgkin** [comment]
@markwilliamfirth Yeah for sure, I was more raising this issue as a place to discuss/document the changes rather than as something I would work on now.  :+1:

Some changes like the colour of the nav on white pages and the training section of the homepage I think _should_ be changed to be more in line with the original designs.

**Comment by finnhodgkin** [comment]
I'm going to make a test branch with a few of the easier design fixes like the nav bar and background colour.

**Comment by iteles** [comment]
@finnhodgkin I believe the change in nav was for a specific purpose: https://github.com/dwyl/dwyl-site/issues/268

I would also say that I much prefer the clean white than the bluey-greyey background colour you mentioned [here](https://github.com/dwyl/dwyl-site/issues/407#issuecomment-333800649)
 for example (though I don't think that was deliberate).

The blog ones are the ones that most annoy me!

The rest I'll leave to your and @markwilliamfirth 's discerning eye

**Comment by markwilliamfirth** [comment]
Has been merged with https://github.com/dwyl/dwyl-site/pull/419
