### ISSUE TITLE
Remove travis.yml

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#408]
Since this is no longer a node project, are we okay to delete the travis.yml? We also no longer have tests so the CI itself is moot, so perhaps we can remove that as well?

**Comment by Rupeshiya** [comment]
@ZooeyMiller Removed .travis.yml #451

**Comment by nelsonic** [comment]
We _may_ end up needing the `.travis.yml` file to run our "Sonarwhal" tests see: #450 
but it will need to be re-written, so "OK" to remove now. 👍
