### ISSUE TITLE
Remove pre-commit

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#409]
Since this is no longer a node project, and has no package.json or node_modules, our precommit now errors when trying to commit: `.git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook: No such file or directory`.

This means every commit has to be run with `--no-verify`. I think we should just remove this pre-commit and add it in again if it becomes necessary.

**Comment by iteles** [comment]
@ZooeyMiller Though it might be worth considering adding a pa11y pre-commit hook? What are your thoughts?

**Comment by ZooeyMiller** [comment]
@iteles I would 100% agree. I do think that this only really makes sense once we have a server set up, and not for the current static GH pages site.

**Comment by ZooeyMiller** [comment]
Couldn't see the pre-commit in the hook section on github, so I removed my local files and re-cloned, and the pre-commit hook was gone. @finnhodgkin isn't getting this either so this can be closed.
