### ISSUE TITLE
Transfer Spreadsheet ownership to hello@dwyl.com

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#417]
From: https://github.com/dwyl/dwyl-site/issues/309#issuecomment-333513808

https://docs.google.com/spreadsheets/d/1PfPRD54M6K2hiN-1IkTC7IkJVRMAuEGoX1qz2cK5HrQ/edit?ts=59d204cc#gid=0

@Cleop Please could you transfer ownership rights to hello@dwyl.com?

**Comment by Cleop** [comment]
done, please test and close @markwilliamfirth
