### ISSUE TITLE
Intentions

### ISSUE THREAD

**Issue by notenociz** [dwyl/dwyl-site#42]
Hey, you might think this a stupid question but, what exactly is dwyl?

I was thinking about this when doing the keywords used in #41.

My question can also be furthered upon as follows: is dwyl.io the website for your app called time or is it the site for dwyl (which is an organisation of open source contributing developers and designers making things to help them make things if I am right)?

Thanks in advance for answering, I really need this cleared up 😀

**Comment by nelsonic** [comment]
@enociz `!stupidQuestion` at all! *Thank you for asking it*!
Its one we are in the process of *addressing* in the next 24h. :+1:

**Comment by markwilliamfirth** [comment]
@notenociz to answer your question (albeit a bit late) it's both!
