### ISSUE TITLE
Notify user of set cookie (compliance with EU law)

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/dwyl-site#420]
We are using Google Tag Manager, which sets a cookie. Under EU law, we must notify a user that we are setting a cookie. We do not currently do this. 

We probably need to add a small bit of Javascript, such that we have some kind of notification to the user that we are setting a cookie, and when they click "Ok" we set a cookie (or use local storage) that makes it so that the notification doesn't show again. We don't have to give them the option for a cookie-less site as far as I know, we just need to notify the user that we _are_ using cookies, and they can choose not to use the site if they don't like that.

(more on the cookie law: https://www.cookielaw.org/the-cookie-law/)

**Comment by markwilliamfirth** [comment]
This was merged in
