### ISSUE TITLE
29th October | Check analytics stats for 1st month of new site

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#422]
As a site owner, 
I would like to know how the new website has been performing in its first month
So that we can determine what we want to A/B test and improve.

## Acceptance Criteria
A comment noting:
+ [ ] Which of the tracked data have improved and which have gone down over the month?
  + [ ] Brief analysis of why any deteriorations may have happened
+ [ ] What insight are we getting from the new metrics we are tracking #222   
  + [ ] Brief analysis of whether they are useful and how we can improve what is being tracked
+ [ ] Any feedback we have received on the new site

**Comment by markwilliamfirth** [comment]
@iteles I don't think I have access to this yet (https://github.com/dwyl/dwyl-site/issues/218)

Do you?

**Comment by iteles** [comment]
Just logged into the analytics and checked, you definitely do:
<img width="746" alt="screen shot 2017-11-03 at 15 57 33" src="https://user-images.githubusercontent.com/4185328/32383390-c91afb8a-c0af-11e7-84b5-a074f33345ac.png">

I gave you, Cleo and Harry permissions at the same time.

**Comment by markwilliamfirth** [comment]
<img width="641" alt="screen shot 2017-11-03 at 16 31 52" src="https://user-images.githubusercontent.com/5732209/32385002-9fcdadae-c0b4-11e7-94b5-b5df6097af31.png">
<img width="972" alt="screen shot 2017-11-03 at 16 33 36" src="https://user-images.githubusercontent.com/5732209/32385059-d953e976-c0b4-11e7-8fce-6c4906455bdd.png">
<img width="306" alt="screen shot 2017-11-03 at 16 33 04" src="https://user-images.githubusercontent.com/5732209/32385060-d973b99a-c0b4-11e7-91d2-afc0b1953424.png">
<img width="300" alt="screen shot 2017-11-03 at 16 33 50" src="https://user-images.githubusercontent.com/5732209/32385061-d98f3ddc-c0b4-11e7-9ae1-86055155ee1e.png">
<img width="973" alt="screen shot 2017-11-03 at 16 33 25" src="https://user-images.githubusercontent.com/5732209/32385062-d9aaed48-c0b4-11e7-8bf3-b56dd08d6152.png">
<img width="973" alt="screen shot 2017-11-03 at 16 33 16" src="https://user-images.githubusercontent.com/5732209/32385063-d9cedb4a-c0b4-11e7-9bfa-2a1a3f2762fb.png">
<img width="304" alt="screen shot 2017-11-03 at 16 34 01" src="https://user-images.githubusercontent.com/5732209/32385064-d9f810f0-c0b4-11e7-8477-3b4f8318235c.png">

**Comment by markwilliamfirth** [comment]
Number of people from US is interesting

**Comment by markwilliamfirth** [comment]
Start of Oct is higher probably because we were still working on the site

**Comment by markwilliamfirth** [comment]
I've only received feedback from one person - they told me it wasn't clear what we do and it took them a while to find out - they also thought it was weird we didn't have an about page

**Comment by markwilliamfirth** [comment]
I don't think the last month can tell us much else - https://github.com/dwyl/dwyl-site/issues/222 should cover us improving the analytics. Regardless of when 222 is implemented we should review these next month as well

**Comment by iteles** [comment]
Do we want to capture this in a less ephemeral way (i.e. a quick md file)?

Are there any actions that come out of this other than opening an issue to check this next month?
Researching how our competitors are clarifying what they do and thinking about how to integrate this into our site for example?

**Comment by markwilliamfirth** [comment]
@iteles 

1st point - the data is captured in GA so I don't see a need to duplicate screenshots into MD files - we should be finding a way to make the data public instead https://github.com/dwyl/dwyl-site/issues/218

2nd point - that issue is here https://github.com/dwyl/dwyl-site/issues/175

With regards to competitors specifically, this cannot be assessed properly until https://github.com/dwyl/hq/issues/328 https://github.com/dwyl/hq/issues/75 https://github.com/dwyl/hq/issues/379 have been resolved to establish our specific offerings and target market(s), which will then infer who our competitors are
