### ISSUE TITLE
Add Cloudflare setup to the readme

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/dwyl-site#426]
To add to the readme:
- [x] Moving a domain to Cloudflare
- [x] Enabling https for custom domains with GitHub pages
- [x] Adding subdomains
- [x] Adding github pages subdomains
- [x] Creating a pagerule for always https
- [x] Creating a pagerule for subdomain redirects

**Comment by markwilliamfirth** [comment]
Please ensure this covers:

https://github.com/dwyl/dwyl-site/issues/413#issuecomment-334760893
https://github.com/dwyl/dwyl-site/issues/413#issuecomment-334786661

as I'm closing that issue in favour of this

**Comment by markwilliamfirth** [comment]
Has been merged with https://github.com/dwyl/dwyl-site/pull/419
