### ISSUE TITLE
Improve design of Cookie Notification

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#427]
Not sure exactly what needs to change, but this could probably be improved somewhat

Perhaps the initial step is to make it stand out more with a different background colour as it's not completely clear that it is separate from the page design and it needs to divert user attention

<img width="1247" alt="screen shot 2017-10-09 at 11 16 56" src="https://user-images.githubusercontent.com/5732209/31333818-77d3f3e2-ace3-11e7-8e64-6f60ea0b51cb.png">

**Comment by ZooeyMiller** [comment]
On my machine the notification is over the dwyl-mint background, so we probably can't use one of our preset colours. I've put some box shadow on it to define it a bit more. Let me know what you think. (screengrab in PR).

**Comment by markwilliamfirth** [comment]
Has been merged with https://github.com/dwyl/dwyl-site/pull/419
