### ISSUE TITLE
Share Access to Cloudflare

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/dwyl-site#429]
As per https://github.com/dwyl/dwyl-site/issues/378#issuecomment-335114032

**Comment by finnhodgkin** [comment]
Non-enterprise Cloudflare accounts can only have one email address. Which dwyl email would you like me to transfer it to @markwilliamfirth ?

**Comment by finnhodgkin** [comment]
Probably best to talk about account things over gitter :)

**Comment by finnhodgkin** [comment]
Fixed :+1:
