### ISSUE TITLE
Blog: Enable Twitter cards for the Blog

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#43]
https://dev.twitter.com/cards/overview

Example implementation on http://www.smashingmagazine.com/
<img width="1287" alt="how-smashing-magazine-implement-twitter-cards" src="https://cloud.githubusercontent.com/assets/4185328/10633469/be76fd18-77e2-11e5-84f4-d7bc33e6464c.png">

**Comment by nelsonic** [comment]
Oh... this is your "*experiment*"... fair enough. look forward to seeing it. :+1:

**Comment by iteles** [comment]
It's not! 
<img width="222" alt="screen shot 2015-10-21 at 11 07 02" src="https://cloud.githubusercontent.com/assets/4185328/10633613/e50a710c-77e3-11e5-8f2e-d8c69488b614.png">


I came across this again when I was researching something in the `<meta>` tags yesterday and wanted to keep it somewhere to be done at a later date. It's pretty cool and will be way useful when we have a blog people are going to link to in tweets.

**Comment by nelsonic** [comment]
No longer relevant. 
We may revisit displaying specific tweets in the future as "social proof" e.g: https://trezor.io/

![image](https://user-images.githubusercontent.com/194400/195070425-7acfd87b-ce6d-4418-a392-a18ea115a7d5.png)

But for now this is not our focus.
Closing.
