### ISSUE TITLE
Keep card styling consistent

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/dwyl-site#432]
The portfolio section has two different types of cards- solid bordered github cards and drop shadowed portfolio cards. IMO one consistent card type looks a lot nicer:

![selection_096](https://user-images.githubusercontent.com/22300773/31381958-f7daec9c-adad-11e7-9dda-5620190b4f59.png)

**Comment by markwilliamfirth** [comment]
Has been merged with https://github.com/dwyl/dwyl-site/pull/419
