### ISSUE TITLE
Get feedback.dwyl.com back online

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#433]
Currently unreachable, needs to be set up on Cloudflare #426 

![screen shot 2017-10-19 at 11 38 15](https://user-images.githubusercontent.com/4185328/31767252-3e60f588-b4c2-11e7-9c08-fae5437996da.png)

**Comment by iteles** [comment]
dwyl-feedback.herokuapp.com

**Comment by nelsonic** [comment]
Heroku is no longer viable for Hobby Apps. We need to re-build and re-deploy to Fly.io ...
