### ISSUE TITLE
Populate case studies template and push to site

### ISSUE THREAD

**Issue by rub1e** [dwyl/dwyl-site#437]
Once @iteles has amended & approved copy for case studies in Google Slides, @rub1e will flesh out copy (so it's more suited to website than deck) and then sit down with @Cleop to get them up on the site.

This will happen on Weds 13th Dec.

This is the latest commit - https://github.com/dwyl/dwyl-site/commit/f962169c2c0cc3ec9942c1e7db0ded4af9b4ac67

**Comment by rub1e** [comment]
@iteles Will we need to wait for clients to take a look over them as per #304?

**Comment by iteles** [comment]
We have approval from EMF, SMG & OA, confirming IC.

**Comment by rub1e** [comment]
@Cleop I've updated the copy and recreated the last commit as discussed, so all we need to do is merge and update all the classes to match the current site. We can do this on Thurs 14th Dec or in pre-xmas week, depending on your commitments.

**Comment by iteles** [comment]
This is done for the ones we have! 👍

**Comment by nelsonic** [comment]
Case studies are now legacy. 
All-in on building the **`App`**.
`GOTO`: https://github.com/dwyl/mvp/issues/140
