### ISSUE TITLE
Copy on 404 page

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#448]
As a visitor to the site, if I land on a 404 page, I'd like to be promoted with what to do next so it doesn't feel as jarring on my journey. 

<hr/>

We're missing the 'remedy' section of https://code.likeagirl.io/the-perfect-apology-7d09ac34eed9

**Comment by Dana94** [comment]
@iteles I'd like to take this on. Are you looking for something specific for the 'remedy' part? Like a button returning to the home page?

**Comment by iteles** [comment]
Hi @Dana94, that would be awesome!  🎉 
At this stage maybe contacting us is the right remedy? But if you have any other thoughts, super happy to hear them.

Please do include a screenshot in your PR too!

**Comment by Dana94** [comment]
@iteles I didn't make a PR yet, but I wanted to ask about the dwyl color being used for the link. I'm following what was done on the page in the second image. I noticed that the contrast ratio is too low. I was wondering if I change the 404 link to a more readable color, should other pages with a link on the white background follow this change? Or should I just keep the links as the dwyl color no matter what?
![image](https://user-images.githubusercontent.com/20132264/66085807-42080400-e540-11e9-8b47-dc69c6372309.png)

![image](https://user-images.githubusercontent.com/20132264/66085867-6b289480-e540-11e9-9bfe-92305f22feb4.png)

**Comment by iteles** [comment]
@Dana94 This is a great catch, we definitely want to make sure we have enough contrast for accessibility. Could you please open a separate issue on this as it's relevant to all link across the site? Hopefully will be a quick fix in the CSS.
