### ISSUE TITLE
Know concepts of Google analytics.js inside out

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#45]
We're currently doing [basic web tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/#what_data_does_the_tracking_snippet_capture).

But see [that sidebar](https://developers.google.com/analytics/devguides/collection/analyticsjs)? We have to make sure we know it like the back of our hand. #transferableconcepts
<img width="225" alt="screen shot 2015-10-21 at 17 47 27" src="https://cloud.githubusercontent.com/assets/4185328/10643660/e535a06a-781b-11e5-9a86-229752fe444e.png">

**Comment by iteles** [comment]
Also, https://mixpanel.com/ (from #19 )

**Comment by nelsonic** [comment]
The time to learn GA was 2008 with *occasional* top-ups in 2011 and 2014.
Now that there is ***Kibana 4*** we can keep all our insights in-house (*i.e. not give* ***all*** *our people's personal data to google if they don't want to be tracked...*)

**Comment by Cleop** [comment]
Is this and #222 an overlap? #222 is more recent however it does not mention Kibana 4, @nelsonic would you prefer use of Kibana 4 over Google Analytics?

**Comment by markwilliamfirth** [comment]
Decided to use google analytics. Closing in favour of #10 #218 #222
