### ISSUE TITLE
Update copyright date on website

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#454]
We need to update this from 2017 to 2018 😊 
<img width="202" alt="screen shot 2018-07-12 at 11 58 51" src="https://user-images.githubusercontent.com/4185328/42629372-00a703ba-85cb-11e8-926f-e2209ee59210.png">

**Comment by Cleop** [comment]
Closing as I can see this now on the site
![image](https://user-images.githubusercontent.com/16775804/53021253-b332f500-3450-11e9-8071-e97b59844ac7.png)
@rub1e has opened: https://github.com/dwyl/dwyl-site/issues/473 for 2019 versions.
