### ISSUE TITLE
Broken link for Healthlocker in portfolio

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#464]
Whilst reviewing PR https://github.com/dwyl/dwyl-site/pull/459 I updated a couple of client routes but forgot to update them _all_ in `portfolio.html` 🤦‍♀️ 

![image](https://user-images.githubusercontent.com/4185328/44549882-d8091280-a722-11e8-981c-0f6cd563ba13.png)

The link for Healthlocker is broken.

**Comment by nelsonic** [comment]
@iteles well-spotted.
