### ISSUE TITLE
Merging without a review

### ISSUE THREAD

**Issue by rub1e** [dwyl/dwyl-site#470]
I've just noticed that you can merge into master without having your PR reviewed in this repo - is that deliberate or an oversight?

Is there a set process for the permissions in dwyl repos?

**Comment by nelsonic** [comment]
https://github.com/dwyl/protect-master-branch

**Comment by nelsonic** [comment]
Assigned to Inês, because I am not the "owner" of this project. 
If it were up to me the dwyl "site" would be a landing page for our _product_.

**Comment by iteles** [comment]
`master` branch now protected.
![image](https://user-images.githubusercontent.com/4185328/48843695-ab02e500-ed8f-11e8-951f-9f0570b4a422.png)

Now we have discussed that we will be moving back to product and we have a clear path to it (https://github.com/dwyl/technology-stack/issues/67), we can start working on our product landing page again 🎉
