### ISSUE TITLE
"On-boarding" people into the dwyl org on github

### ISSUE THREAD

**Issue by rub1e** [dwyl/dwyl-site#471]
Currently the invitation to `join us` on the dwyl site (https://dwyl.com/community) just links to the [list of members](https://github.com/orgs/dwyl/people) and so needs to be updated.

Currently, we point people to [this issue](https://github.com/dwyl/start-here/issues/143) when they ask about joining, so we should probably think of what a better `on-boarding` experience might look like, but in the meantime I think it makes sense to just update the link on the /community page to issue 143.

* [x] Await approval from the site owners
* [x] Change `join us` link to https://github.com/dwyl/start-here/issues/143
* [ ] Discuss best way to `on-board` new people

**Comment by rub1e** [comment]
Now that we have [a stopgap](https://github.com/dwyl/dwyl-site/pull/472), we can have a think about the best way of welcoming people into the organisation, while reducing the amount of admin / monitoring required

Other than people just not reading the instructions and emailing `hello@` to get an invite, what are some of the pain points?

I was thinking that we do get a handful of approaches asking for a job / freelance work etc. - could be nice to have a line explaining that this is just about joining the github org rather than working with us as an agency?

Any other things to think about?

**Comment by nelsonic** [comment]
This will be resolved by: https://github.com/dwyl/start-here/issues/255 👨‍💻
