### ISSUE TITLE
2019ing the site

### ISSUE THREAD

**Issue by rub1e** [dwyl/dwyl-site#473]
It's 2019!

Thanks to @Cleop for pointing out the below at https://dwyl.com/values

![screenshot 2019-01-02 at 16 26 58](https://user-images.githubusercontent.com/11595920/50601272-9dbb3900-0eab-11e9-9d38-d0f794d154b2.png)

This needs updating generally, rather than just changing 2018 > 2019. I'd make a suggestion but I don't really know where we are / want to be with our carbon 👣 

I've also spotted ©️ 2018 in the footer, but that's just a simple `find & replace`

I can't change them from this computer so I'll do it from home - so do shout if anyone notices anything else that's out of date (but obviously I'll do a search for 2018 anyway)

* [x] Identify copy that needs changing
* [ ] Discuss what to change it to
* [ ] Change 2018 > 2019 in the footer

**Comment by rub1e** [comment]
* **Values**
  * "We recycle and plan to be carbon neutral by 2018, but it’s not just the planet’s environment we want to improve. We love projects that have a positive effect on the world."
* **Home**
  * "We expect the building works to be done by the end of September and the first "MVP" members to join us in October 2018. We are able to "Alpha UX Test" the app with friends & co-workers before we open the physical home."

☝️ These are the two bits of copy that I think need changing. If you could let me know what you'd like to change them to (and I'm of course happy to write the words if you give me the message), I'll update these and the ©️ 2018 footer at the same time.

**Comment by nelsonic** [comment]
Thanks for making these updates at the time @rub1e 👍 
Closing. ✅
