### ISSUE TITLE
Broken link for Quodl case-studies page "visit the site" button link

### ISSUE THREAD

**Issue by manfordbenjamin** [dwyl/dwyl-site#475]
On the Quodl case-studies page, the button to visit the external link is broken and returns a 404.

**Comment by iteles** [comment]
Good catch @manfordbenjamin ! 
Thanks for raising the issue.

Should be an easy fix, it's a link issue on our side:
![image](https://user-images.githubusercontent.com/4185328/62318114-f9c25c00-b492-11e9-9010-92d260fb7ae2.png)

**Comment by manfordbenjamin** [comment]
Thank you @iteles

**Comment by iteles** [comment]
Hey @manfordbenjamin, this should not be fixed! Could you please test it and if fixed, close this issue? 😊

**Comment by manfordbenjamin** [comment]
@iteles Thank you for the fixed :)
