### ISSUE TITLE
Can anyone add him/herself to the teams page

### ISSUE THREAD

**Issue by manfordbenjamin** [dwyl/dwyl-site#485]
@nelsonic @iteles I wanted to find out if anyone at all can add him/herself to the teams page or it's limited to core team members only??

**Comment by iteles** [comment]
@manfordbenjamin For now, core team members only ☺️ We’ll be altering the website soon as we evolve what dwyl does with http://www.github.com/dwyl/home and will have more of an ‘active community members’ type page, at which point we can open a new issue on this! I’ll make sure I tag you 😁

Thanks for asking 🎉
