### ISSUE TITLE
Contact Form `SPAM` 😢 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#487]
Just got 12 identical emails:
![image](https://user-images.githubusercontent.com/194400/136422742-0730fc67-5b65-4a92-9e31-076edb580a9c.png)

All the same ... this person "_chasing_" to be given write-access to on of our GitHub repos:
<img width="780" alt="spam-email-probrem" src="https://user-images.githubusercontent.com/194400/136423737-7291a660-d418-426a-ad57-e31e1c7ed7f4.png">

But we get a _lot_ of spam through our contact-us form ...

![image](https://user-images.githubusercontent.com/194400/136422888-f18bdc98-0292-46b7-9c9a-33d1d9448458.png)

@iteles guessing you get these too as they go to the "shared" email address. Do you just ignore them? 💭 

This has been an issue for a while https://github.com/dwyl/dwyl-site/issues/310 and has never been _fully_ resolved.
But rather than re-opening the old issue I'm opening this focussed one.

The contact form: https://dwyl.com/#contact allows people to _easily_ submit a message:

<img width="1080" alt="dwyl-contact-us-form" src="https://user-images.githubusercontent.com/194400/136425180-1aecc55e-8f91-4252-90ea-c1fdd4271727.png">

I'm actually a _fan_ of having this kind of immediately accessible contact form on a website from a UX perspective. 👍 
It's **_zero_ friction** which is great for legitimate contacts. 🎉 
But the downside is that it makes **`SPAM`** _very_ easy too. 😢 

# Todo

+ [ ] Investigate alternative high-privacy options for _managing_ contact form submissions.

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/213371850-2764c0d7-8b7f-42a4-aca8-82b1fe68fb25.png)

This bugs me _multiple_ times a day. This morning I got spam on my wrist (Apple Watch) at 05:30 while reading ... 😢 
It needs to stop. Now. 🙅

**Comment by nelsonic** [comment]
Removing the Contact page from the website:

![image](https://user-images.githubusercontent.com/194400/213372238-b6fc1ef9-d42e-4072-ad7b-3877e0a1a9b9.png)

**Comment by nelsonic** [comment]
PR: #500 @SimonLab 🙏

**Comment by nelsonic** [comment]
No more Contact Form on any of the pages and updated the "App" Page:

![image](https://user-images.githubusercontent.com/194400/213425368-001e9057-f2a8-4c45-a86c-0e36666a9183.png)

Hopefully the `SPAM` can stop now. 🤞

**Comment by nelsonic** [comment]
Bulk deleting the  `SPAM`:

![image](https://user-images.githubusercontent.com/194400/213432854-b8d957fa-2650-4c83-b269-db3806561b5c.png)

**Comment by nelsonic** [comment]
1300 messages in 2022. 3.56 / day. Enough! 😡

**Comment by iteles** [comment]
Sounds like a plan. People can reach us on GH if they need to. 
We don't _need_ tonbe reached just now and when we do, we can do this right. 

FYI I just had a filter which skipped the inbox and went through the folder once every couple of weeks. Also, I don't get email notifications on my phone. Ain't nobody got time for that.

**Comment by nelsonic** [comment]
I had notifications on in case legit people contacted us, which they did. 🔔 
But ever since the bots discovered our website / form it's been _constant_ `SAPAM`. 👎 
A filter _could_ have been a good `<option>`, but I consider it a bit of a _bandaid_ 🩹 
This makes it _very_ clear to spammers/scammers that we aren't open for that crap anymore. 🙅
