### ISSUE TITLE
Blog: Blog Page: Copy / write first blog article

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#5]
What about?

**Comment by enociz** [comment]
Maybe make a milestone for setting up a blog, assign some issues and let's get started!

**Comment by nelsonic** [comment]
I *like* the way you think @enociz :wink:

**Comment by Cleop** [comment]
Updating this issue for the site redesign. Over to @harrygfox to mock up a design for this.

@markwilliamfirth @iteles @nelsonic:
- Do any of you have strong feelings about what the first blog post should be about?
  - Should it be an introductory focussed topic? ie. what the blog is for/about? or the ideas behind the dwyl site redesign/stack?
  - Or just a random topic not specific to the fact it's the first post?
- Should @markwilliamfirth or @iteles or someone else be responsible for the copy of this? I'm also happy to put something together given some indication for subject matter if you'd like.

**Comment by markwilliamfirth** [comment]
@cleop yep I'll be managing this - I imagine the first post will be something like a welcome to the new website / new blog / what to expect kinda thing

Do you have a time estimate for when the blog should be done by? (i.e. the deadline for the content for the first post)

**Comment by Cleop** [comment]
Providing there's no other copy that we need for the blog page, then we'll only need the post in time for the site to be put live. So for now this copy will be lower priority than the other copy on the site as it will not influence the designs ie. the blogs will be of varying length and so the designs should be able to cater for this. For other pages, the copy will shape the designs more directly.

I will be able to give a more accurate estimate for the time until the site goes live once you and @harrygfox have added time estimates on the copy and design issues and then I can create issues/ add estimates to the technical issues needed to create them 🕥

**Comment by Cleop** [comment]
@markwilliamfirth, following our call earlier today, this page is now being built. Time to get started on copy for this. As you've seen the design for the page and that it features multiple articles, do we have copy pre-made for any other blogs too so that we start off with more than just one?
