### ISSUE TITLE
GitHub Actions CI Failing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#505]
CI hasn't passed for a `while` ...  [![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/dwyl/dwyl-site/ci.yml?label=build&style=flat-square&branch=main)](https://github.com/dwyl/dwyl-site/actions)
https://github.com/dwyl/dwyl-site/actions/workflows/ci.yml
<img width="1693" alt="image" src="https://github.com/dwyl/dwyl-site/assets/194400/eb47edae-6002-485f-ac1f-b695a1cf4bd5">

It's using: https://github.com/Cyb3r-Jak3/html5validator-action
https://github.com/dwyl/dwyl-site/blob/9b35b2d05bc885634a16b9a7e7786913d678795a/.github/workflows/ci.yml#L15

# Todo

+ [ ] Get this working again.

**Comment by nelsonic** [comment]
@LuchoTurtle please spend `T10m` on this when you have finished your "work work" 
and just leave a comment as to what you _think_ the problem is. 💬 🙏

**Comment by LuchoTurtle** [comment]
<img width="731" alt="image" src="https://github.com/user-attachments/assets/f7a8b590-fe1e-477a-a981-2e91ef019a28">

The CI file is invalid.

**Comment by nelsonic** [comment]
Ok. So fixable. 👌 thanks. 🙏
