### ISSUE TITLE
List of Companies we have Worked With

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#58]
We need a collection of logos of companies we have worked with for the site.
- Burberry
- Groupon
- OneFineStay
- Oxfam
- Santander
- CAF

_Please_ add to this list.

**Comment by nelsonic** [comment]
![caf_logo](https://cloud.githubusercontent.com/assets/194400/10891685/39249062-8197-11e5-9f47-26088d69a6d6.gif)
![burberry-logo-609x350](https://cloud.githubusercontent.com/assets/194400/10891729/79d7e294-8197-11e5-8754-d12728e8c1f7.jpg)
![nhs-scotland-600x403](https://cloud.githubusercontent.com/assets/194400/10891897/74cb4358-8198-11e5-8303-600101ea3d0e.png)
![301px-groupon_logo svg](https://cloud.githubusercontent.com/assets/194400/10891917/8bb2e5e4-8198-11e5-96eb-ca012d06f97d.png)
![onefinestay-logo](https://cloud.githubusercontent.com/assets/194400/10891946/b90da63c-8198-11e5-801e-df0dac925818.png)
![banco_santander svg](https://cloud.githubusercontent.com/assets/194400/10892049/4dd50792-8199-11e5-86b2-f032415f0b9f.png)
![pearson-logo](https://cloud.githubusercontent.com/assets/194400/10892101/826123e2-8199-11e5-86b7-d36e75e12444.png)
![cancer-research-logo](https://cloud.githubusercontent.com/assets/194400/10892135/a4c18b98-8199-11e5-9852-19bc69ecd311.png)
![oxfam-logo](https://cloud.githubusercontent.com/assets/194400/10892158/cb3ba204-8199-11e5-823b-0b590c9a834f.jpg)
![foundation-logo](https://cloud.githubusercontent.com/assets/194400/10892199/068ce854-819a-11e5-8187-422448ee33a4.jpg)

**Comment by iteles** [comment]
+ [Global Alliance for Clean Cookstoves](http://cleancookstoves.org/)
+ [Opportunity International](http://opportunity.org.uk/)
+ [Plan International](https://plan-international.org/)
+ [IFC - International Finance Corporation](http://www.ifc.org/wps/wcm/connect/corp_ext_content/ifc_external_corporate_site/home) (World Bank Group)
+ [DFID - Department for International Development](https://www.gov.uk/government/organisations/department-for-international-development)
+ [Visionfund](http://www.visionfund.org/)
+ NHS Scotland
+ [Equal Exchange](http://www.equalexchange.co.uk/)
+ [Kiva](http://www.kiva.org/)

**Comment by markwilliamfirth** [comment]
Mark to add to this list with the list he's compiled

**Comment by markwilliamfirth** [comment]
Science Museum
Global M
Ellen Macarthur Foundation - CE100 Platform
Thomas Cook
Safe Lives
City University
Age UK
Oxford Abstracts
ART
Inclusive Classrooms
Odysseon
Yoti
Oxfam
Mindwave - Healthlocker
Mindwave - FREED
Airsupply
Mindwave - Medcheck (Dementia)
Risk Resource
iOS development
One Fine Stay

**Comment by markwilliamfirth** [comment]
@iteles is this correct? Please can you let me know of any omissions and incorrect placement in the two lists?

**These companies worked with Nelson / Inês before dwyl:**
Global Alliance for Clean Cookstoves
Opportunity International
Plan International
IFC - International Finance Corporation (World Bank Group)
DFID - Department for International Development
Visionfund
Scottish School for Primary Care
Equal Exchange
Kiva
Burberry
Groupon
onefinestay
Oxfam
Santander
Charities Aid Foundation
NHS Scotland
Fairtrade Foundation
Cancer Research UK


**These companies worked with the dwyl brand:**
Science Museum
Global M
Ellen Macarthur Foundation
Thomas Cook
Safe Lives
City University
Age UK
Oxford Abstracts
ART
Pearson Education
Odysseon / Adventure Goat
Yoti
Airsupply
Mindwave Ventures

Not sure if I'm missing some or if some of these are in the wrong list

**Comment by iteles** [comment]
No longer relevant
