### ISSUE TITLE
Hook up blog as sub-domain or root?

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#6]
blog.dwyl.io or www.dwyl.io/blog?

@nelsonic  Any preferences?

**Comment by enociz** [comment]
I might not be @nelsonic but I think that blog.dwyl.io is better than dwyl.io/blog/. However, /blog/ will be easier to configure if you're using CNAME as you only have to create the repo and make a gh-pages branch and you're ready to go.

**Comment by iteles** [comment]
@enociz That's my current preference as well :wink:  Thanks for adding your voice to this :blush: 
Just building up the content in the background!

**Comment by nelsonic** [comment]
Any reason we can't alias one to the other and have the load balancer see which one gets more hits?
![a-b-test-all-the-things](https://cloud.githubusercontent.com/assets/194400/10220334/922e58f4-683e-11e5-8ef3-9d2fb1fd6d25.jpg)
> Don't Ask me to Chose Between Pizza and IceCream when I can *easily* have both. :wink:

**Comment by enociz** [comment]
That sounds like a good idea! A little testing _will_ go a long way.

**Comment by iteles** [comment]
@markwilliamfirth Did we reach a resolution on this issue before closing?

**Comment by markwilliamfirth** [comment]
From post above it sounds like the resolution was to link both together and do an a/b test - is that right?

If you're interested in what I think, personally I'm more in favour of a subdomain (blog.dwyl.io) with dwyl.io/blog forwarding to it
