### ISSUE TITLE
Who do we *want* to work with?!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#68]
Should we be _specific_ about who we _Want_ to work with?

**Comment by thegsi** [comment]
British Museum
British Library
Victoria and Albert Museum
Bodleian Library
National Archives

**Comment by nelsonic** [comment]
Great list @thegsi these are great organisations who we should be working with! :+1: 
@dwyl/ateam if anyone else has a list of companies we should be working with please add!

**Comment by rjmk** [comment]
[These guys?](http://www.opencompany.org/directory/)

**Comment by nelsonic** [comment]
@rjmk :+1:

**Comment by iteles** [comment]
@thegsi @rjmk Thanks for these! So good to see people bringing this thread back to life! :heart:

**Comment by markwilliamfirth** [comment]
Closing in favour of https://github.com/dwyl/hq/issues/379
