### ISSUE TITLE
Should we include the fact that we train people up?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#70]
@iteles thoughts?

**Comment by iteles** [comment]
I think we need to include a whole lot more about our philosophy, it's what sets us apart.

We need to include that we both that we train the developers (I mentioned `continuous learning` in [this comment](https://github.com/dwyl/dwyl.github.io/pull/56#issuecomment-153564767)) _and_ clients in lean methodologies (MVPs and prototyping) and in other things they may need (e.g. Github).

**Comment by nelsonic** [comment]
Do you have time to spec this?

**Comment by hdrdavies** [comment]
@iteles would you like to have this included in the current iteration?

**Comment by iteles** [comment]
Have a think about where and whether it might fit in. We can keep the issue open for next week's iteration ;)

**Comment by markwilliamfirth** [comment]
Closed due to redesign

**Comment by iteles** [comment]
Was this question considered in the redesign? I suspect @harrygfox may not have seen it.
It may still be an open question.

**Comment by harrygfox** [comment]
There are definitely places for this kind of information to go - the careers page, when it exists, the values page perhaps (if it can be considered that important). You're right though @iteles I didn't see this during my time on the project

**Comment by markwilliamfirth** [comment]
@iteles it's me/you that decide on the copy - do you want it on there?

Linked to #306 

Copy here: https://github.com/dwyl/dwyl-site/issues/223#issuecomment-319077516
