### ISSUE TITLE
Really Good "Hero" Image of Messenger on Various Devices

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#76]
![yahoo_messenger_hero_image 0 0](https://cloud.githubusercontent.com/assets/194400/11569414/a77b0fcc-99e9-11e5-9049-68a717110ac5.png)

[Original Source](https://cdn1.vox-cdn.com/thumbor/MGuVW2QunQVvTi373X1usk4D2nM=/69x0:2447x1585/2050x1367/cdn0.vox-cdn.com/uploads/chorus_image/image/47788639/Yahoo_Messenger_Hero_Image.0.0.png)

**Comment by iteles** [comment]
Linked to #26 .

**Comment by markwilliamfirth** [comment]
Closing due to redesign
