### ISSUE TITLE
Repo is Huge? why?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#80]
Why is the Github repo for our website so big...?
![dwyl-website-repo-huge](https://cloud.githubusercontent.com/assets/194400/12341397/37b31d64-bb19-11e5-89ff-e4bc240f8cfd.png)

**Comment by iteles** [comment]
I haven't figured it out yet. The images are still the temporary un-optimised ones which means there are about 6MB in the `img` folder but that doesn't account for the rest. No idea where it's coming from.
<img width="433" alt="screen shot 2016-01-14 at 23 55 23" src="https://cloud.githubusercontent.com/assets/4185328/12341566/809bf20c-bb1a-11e5-9b93-1eb4a8d6b1f5.png">

**Comment by FilWisher** [comment]
The pack file ".git/objects/pack/pack-f8681b55442fab51e3fe1f1e489b5f1861e1bdda.pack" is 28M. It seems likely that some images (or other large files) have been committed and now removed so git is still tracking them.

**Comment by nelsonic** [comment]
sweet investigation skillz @FilWisher  :wink:
Do you know if there is anything we can do to clean it up? :question:

**Comment by markwilliamfirth** [comment]
@cleo to see if this is still an issue in the redesign

**Comment by Cleop** [comment]
<img src="https://user-images.githubusercontent.com/16775804/30266261-addafa80-96d6-11e7-826c-8da0a8f52b0f.png" width=400px />
<img src="https://user-images.githubusercontent.com/16775804/30266288-c69ced26-96d6-11e7-9a9a-2aedb51c8658.png" width=400px />
<img src="https://user-images.githubusercontent.com/16775804/30266292-cdc3f9be-96d6-11e7-8ad8-756c0498501a.png" width=400px />

**Comment by markwilliamfirth** [comment]
Let's optimise this one at a later date

**Comment by nelsonic** [comment]
We will be wiping this repo and starting fresh soon. 🔜 
Closing my own issue. ✅
