### ISSUE TITLE
What our clients say...

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#88]
[Reason.Factory](http://reasonfactory.com/) have a nicely designed minimalist site, which isn't far from the design that dwyl.io currently uses. They _do_ have a 'what our customers say' section which I think would be a great addition to the dwyl website. 

![whatourcustomerssay](https://cloud.githubusercontent.com/assets/13098199/12723546/c99c3508-c901-11e5-9329-dba8cb8456fc.png)

**Comment by iteles** [comment]
Agreed! The second we get some testimonials, they should go on the site. I favour adding a photo of the person's face with a link to their LinkedIn/Twitter profile instead of just the quote where possible; there are many great examples of this!

**Comment by nelsonic** [comment]
@hdrdavies for sure. can you prepare a request for feedback email we can send to our previous clients?

**Comment by hdrdavies** [comment]
@nelsonic sure can!

**Comment by hdrdavies** [comment]
Copy is here:

https://docs.google.com/document/d/1dKKgMM3nvdfNr2b51O1l1ADNfn4tOlIjCVoBOuqwPnU/edit?usp=sharing

At current, there's 10 questions. We'd probably like to shave this down to no more than 7, if that - could you comment on which ones might not be as important as other?

**Comment by hdrdavies** [comment]
Also going to add *'What do you think makes dwyl different from other web agencies?'*

**Comment by hdrdavies** [comment]
Currently have 3 images of clients with names and quotes in #96

**Comment by iteles** [comment]
:laughing: I think we might need to be careful to maybe _not_ push those placeholders to production :wink:

**Comment by hdrdavies** [comment]
:wink:

**Comment by hdrdavies** [comment]
@iteles left a few comments on the Google doc if you don't mind responding.... (particularly concerning google forms one) :+1:

**Comment by iteles** [comment]
Linked to #58.

**Comment by markwilliamfirth** [comment]
Closing in favour of #226 and #305
