### ISSUE TITLE
Portfolio page

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#89]
tbc.digital (of #86 fame)... have a cool layout for their work [portfolio](http://tbc.digital/our-work), which is similar to a few other agency portfolio pages.

![portfolio](https://cloud.githubusercontent.com/assets/13098199/12723821/fe866cd8-c902-11e5-8212-d63a696ccd8d.png)

**Comment by hdrdavies** [comment]
I'm also a fan of [codescrum's](http://codescrum.com/startups/#works) projects section, which displays the *sectors* of clients they've worked with. May be a good way to emphasise that we've worked with charities, health services etc. 

![codescrumprojects](https://cloud.githubusercontent.com/assets/13098199/12724139/76abdd14-c904-11e5-8786-14049c15b971.png)

**Comment by hdrdavies** [comment]
Not currently featured in #96, has a link at the top right of the page

**Comment by nelsonic** [comment]
http://www.makeusproud.com/

**Comment by markwilliamfirth** [comment]
Closing in favour of #280 #281
