### ISSUE TITLE
Find out who made this image!

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#95]
![image](https://cloud.githubusercontent.com/assets/13098199/12852799/bb59d836-cc28-11e5-910d-0928e02751b1.png)

...and ask them if they don't mind us re-using it...

related to #60

**Comment by iteles** [comment]
@hdrdavies - let me know if you have any questions about the label @nelsonic just added. It means it's not a task for you or @mantagen to waste time on!

**Comment by hdrdavies** [comment]
What does va stand for :question:

**Comment by iteles** [comment]
Virtual assistant 😊

**Comment by nelsonic** [comment]
@hdrdavies i.e. *anyone* can do this task, it does not have to be done by someone with great JS/CSS skills ...

**Comment by hdrdavies** [comment]
:+1:

**Comment by Cleop** [comment]
I'm going to close this issue as this concept was included in the last dwyl site I'm assuming that this issue was resolved/ overcome.

Equally, it's not in the new site designs so in theory is no longer of importance.
