### ISSUE TITLE
Take a few exciting new photos for our website 'hero image'

### ISSUE THREAD

**Issue by iteles** [dwyl/dwyl-site#97]
As per [this comment](https://github.com/dwyl/dwyl.github.io/issues/93#issuecomment-180883909), it would be great to try a few different ideas for hero images for our new website. 

We don't _need_ one of course, but I still think it would be a fun exercise.

For example, a nice wooden table with laptops open, a plant in the middle, a few cups of tea, wireframes on the table and various hands coding away (from our actual dwyl team!). 
<img width="1631" alt="idea-for-dwylio-her-image" src="https://cloud.githubusercontent.com/assets/4185328/12870023/f287aac6-cd28-11e5-8b1c-4d46a9aaba41.png">

We could maybe look to take a photo like this at the next dwylhq lunch dwyl/hq#89.
@sohilpandya, wanna help? :wink: :camera: :bulb:

**Comment by sohilpandya** [comment]
Absolutely! :+1:

**Comment by mantagen** [comment]
@sohilpandya Would be awesome to have a few of this style image to choose from for various parts of the site!

**Comment by hdrdavies** [comment]
Exactly @mantagen.

Where we have segments which are in grey- Our Process, Contact us, and maybe even values, we could have images behind the grey overlay.

**Comment by iteles** [comment]
@sohilpandya We never got round to this! Must remember for the next dwyl lunch/dinner

**Comment by Cleop** [comment]
@iteles is this still something you'd like to see featured in the new site design? Anywhere in particular?

**Comment by markwilliamfirth** [comment]
Closing due to redesign
