### ISSUE TITLE
Redesign: Blog Page: design

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/dwyl-site#98]
A lot of web-agency blogs present their blogs in squares and allow for click throughs:
## [Blueegg](http://bluegg.co.uk/blog)

![blueeggblog](https://cloud.githubusercontent.com/assets/13098199/12917504/b3b36c4e-cf31-11e5-83d0-483b39d3e8c3.png)
## [Steve-edge](http://www.steve-edge.com/blog/)

![steve-edgeblog](https://cloud.githubusercontent.com/assets/13098199/12917511/c03c107e-cf31-11e5-9ece-cc861b68356e.png)
## [Jump](https://www.wesayhowhigh.com/blog/web-design)

![wesayhowhighblog](https://cloud.githubusercontent.com/assets/13098199/12917523/d082edae-cf31-11e5-940d-0ad05eea68c2.png)

Jump is my favourite - I think lots of images can be quite busy, and we might not want to spend time trying to find images for each respective blog post!

**Comment by iteles** [comment]
Agree, especially for the first iteration let's keep this simple.
Relatively low priority as we don't have content yet - keen to get the other pages up first.

**Comment by Cleop** [comment]
Not creating a new issue for this as this one already existed. @harrygfox over to you for designs.

**Comment by harrygfox** [comment]
@Cleop it's _displayed_ by columns, but is still meant to be _ordered_ in rows. I think it would be confusing / frustrating for users to see posts of varying ages when they scan across the page, and more so to have to click the load button to find only the fourth most recent article

**Comment by Cleop** [comment]
@harrygfox - good, that's what I was thinking for users being confused, thanks for clarifying. It will be harder to inject the content into columns if chronologically it's running horizontally as rows but we can give it a shot.

**Comment by Cleop** [comment]
@harrygfox - just to make sure my understanding is right:
 - should the titles of a row of posts be inline with one another vertically?
- How much copy should each blog post show, is it capped at a certain number of characters (because this page is only showing say the first para right? you click on the title to see the full blog post?)?
- Are the names of the authors links? If so, where does clicking on them take you?

**Comment by harrygfox** [comment]
@Cleop 
Everything is determined by content.
- Yes everything is vertically aligned in each column
- I hadn't imagined any programmatic limit to the blurb beneath the title, but rather the post creator would be able to determine what does into the blurb hence the staggered display
- Names _could_ be links if we had somewhere for them to go. One option right now would be to go to the highlighted view of that author on the team page. Another would be to show only the posts by that author. Right now though, not links

**Comment by Cleop** [comment]
Thanks @harrygfox 👍

**Comment by Cleop** [comment]
The designs have dwyl with a capital D, but I think it's either DWYL or dwyl but not half half. Generally I thought the consensus was all lowercase. Does this look weird:

**Comment by harrygfox** [comment]
@Cleop only if you over-think it 🍷

**Comment by markwilliamfirth** [comment]
It's always dwyl regardless of where it is in a sentence

This is still under review https://github.com/dwyl/hq/issues/249

**Comment by markwilliamfirth** [comment]
Nice! 👍
